# -*- coding: utf-8 -*-
from string import punctuation, whitespace, digits


def convertTounicode(source_text, filtered=False, debug=False):
    translated = source_text
    # Independent Vowels
    translated = translated.replace(u"", u"அ")
    translated = translated.replace(u"‚", u"ஆ")
    translated = translated.replace(u"ƒ", u"இ")
    translated = translated.replace(u"„", u"ஈ")
    translated = translated.replace(u"…", u"உ")
    translated = translated.replace(u"†", u"ஊ")
    translated = translated.replace(u"‡", u"எ")
    translated = translated.replace(u"ˆ", u"ஏ")
    translated = translated.replace(u"‰", u"ஐ")
    translated = translated.replace(u"Š", u"ஒ")
    translated = translated.replace(u"‹", u"ஓ")
    translated = translated.replace(u"Šã", u"ஔ")
    translated = translated.replace(u"Œ", u"ஃ")

    # க Family
    translated = translated.replace(u"", u"க்")
    translated = translated.replace(u"—ã", u"கௌ")
    translated = translated.replace(u"þ‘", u"கோ")
    translated = translated.replace(u"—‘", u"கொ")
    translated = translated.replace(u"€", u"கை")
    translated = translated.replace(u"þ", u"கே")
    translated = translated.replace(u"—", u"கெ")
    translated = translated.replace(u"˜", u"கூ")
    translated = translated.replace(u"", u"கு")
    translated = translated.replace(u"", u"கீ")
    translated = translated.replace(u"Ž", u"கி")
    translated = translated.replace(u"‘", u"கா")
    translated = translated.replace(u"", u"க")

    # ங Family
    translated = translated.replace(u"›", u"ங்")
    translated = translated.replace(u"—šã", u"ஙௌ")
    translated = translated.replace(u"þš‘", u"ஙோ")
    translated = translated.replace(u"—š‘", u"ஙொ")
    translated = translated.replace(u"€š", u"ஙை")
    translated = translated.replace(u"þš", u"ஙே")
    translated = translated.replace(u"—š", u"ஙெ")
    translated = translated.replace(u"š", u"ஙீ")
    translated = translated.replace(u"š", u"ஙி")
    translated = translated.replace(u"š‘", u"ஙா")
    translated = translated.replace(u"š", u"ங")

    # ச Family
    translated = translated.replace(u"¢", u"ச்")
    translated = translated.replace(u"—œã", u"சௌ")
    translated = translated.replace(u"þœ‘", u"சோ")
    translated = translated.replace(u"—œ‘", u"சொ")
    translated = translated.replace(u"€œ", u"சை")
    translated = translated.replace(u"þœ", u"சே")
    translated = translated.replace(u"—œ", u"செ")
    translated = translated.replace(u"¡", u"சூ")
    translated = translated.replace(u"Ÿ", u"சு")
    translated = translated.replace(u"", u"சீ")
    translated = translated.replace(u"", u"சி")
    translated = translated.replace(u"œ‘", u"சா")
    translated = translated.replace(u"œ", u"ச")

    # ஜ Family
    translated = translated.replace(u"ô", u"ஜ்")
    translated = translated.replace(u"—óó", u"ஜௌ")
    translated = translated.replace(u"þó‘", u"ஜோ")
    translated = translated.replace(u"—ó‘", u"ஜொ")
    translated = translated.replace(u"€ó", u"ஜை")
    translated = translated.replace(u"þó", u"ஜே")
    translated = translated.replace(u"—ó", u"ஜெ")
    translated = translated.replace(u"ó•", u"ஜூ")
    translated = translated.replace(u"ó”", u"ஜு")
    translated = translated.replace(u"ó", u"ஜீ")
    translated = translated.replace(u"ó", u"ஜி")
    translated = translated.replace(u"ó‘", u"ஜா")
    translated = translated.replace(u"ó", u"ஜ")

    # ஞ Family
    translated = translated.replace(u"¤", u"ஞ்")
    translated = translated.replace(u"—£ã", u"ஞௌ")
    translated = translated.replace(u"þ£‘", u"ஞோ")
    translated = translated.replace(u"—£‘", u"ஞொ")
    translated = translated.replace(u"€£", u"ஞை")
    translated = translated.replace(u"þ£", u"ஞே")
    translated = translated.replace(u"—£", u"ஞெ")
    translated = translated.replace(u"£", u"ஞீ")
    translated = translated.replace(u"£", u"ஞி")
    translated = translated.replace(u"£‘", u"ஞா")
    translated = translated.replace(u"£", u"ஞ")

    # ட Family
    translated = translated.replace(u"ª", u"ட்")
    translated = translated.replace(u"—¥ã", u"டௌ")
    translated = translated.replace(u"þ¥‘", u"டோ")
    translated = translated.replace(u"—¥‘", u"டொ")
    translated = translated.replace(u"€¥", u"டை")
    translated = translated.replace(u"þ¥", u"டே")
    translated = translated.replace(u"—¥", u"டெ")
    translated = translated.replace(u"©", u"டூ")
    translated = translated.replace(u"¨", u"டு")
    translated = translated.replace(u"§", u"டீ")
    translated = translated.replace(u"¦", u"டி")
    translated = translated.replace(u"¥‘", u"டா")
    translated = translated.replace(u"¥", u"ட")

    # ண Family
    translated = translated.replace(u"¯", u"ண்")
    translated = translated.replace(u"—«ã", u"ணௌ")
    translated = translated.replace(u"þ«‘", u"ணோ")
    translated = translated.replace(u"—«‘", u"ணொ")
    translated = translated.replace(u"€«", u"ணை")
    translated = translated.replace(u"þ«", u"ணே")
    translated = translated.replace(u"—«", u"ணெ")
    translated = translated.replace(u"®–", u"ணூ")
    translated = translated.replace(u"®", u"ணு")
    translated = translated.replace(u"−", u"ணீ")
    translated = translated.replace(u"¬", u"ணி")
    translated = translated.replace(u"«‘", u"ணா")
    translated = translated.replace(u"«", u"ண")

    # த Family
    translated = translated.replace(u"´", u"த்")
    translated = translated.replace(u"—°ã", u"தௌ")
    translated = translated.replace(u"þ°‘", u"தோ")
    translated = translated.replace(u"—°‘", u"தொ")
    translated = translated.replace(u"€°", u"தை")
    translated = translated.replace(u"þ°", u"தே")
    translated = translated.replace(u"—°", u"தெ")
    translated = translated.replace(u"³–", u"தூ")
    translated = translated.replace(u"³", u"து")
    translated = translated.replace(u"²", u"தீ")
    translated = translated.replace(u"±", u"தி")
    translated = translated.replace(u"°‘", u"தா")
    translated = translated.replace(u"°", u"த")

    # ந Family
    translated = translated.replace(u"¹", u"ந்")
    translated = translated.replace(u"—µã", u"நௌ")
    translated = translated.replace(u"þµ‘", u"நோ")
    translated = translated.replace(u"—µ‘", u"நொ")
    translated = translated.replace(u"€µ", u"நை")
    translated = translated.replace(u"þµ", u"நே")
    translated = translated.replace(u"—µ", u"நெ")
    translated = translated.replace(u"¸–", u"நூ")
    translated = translated.replace(u"¸", u"நு")
    translated = translated.replace(u"ÿ", u"நீ")
    translated = translated.replace(u"¶", u"நி")
    translated = translated.replace(u"µ‘", u"நா")
    translated = translated.replace(u"µ", u"ந")

    # ன Family
    translated = translated.replace(u"ò", u"ன்")
    translated = translated.replace(u"—îã", u"னௌ")
    translated = translated.replace(u"þî‘", u"னோ")
    translated = translated.replace(u"—î‘", u"னொ")
    translated = translated.replace(u"€î", u"னை")
    translated = translated.replace(u"þî", u"னே")
    translated = translated.replace(u"—î", u"னெ")
    translated = translated.replace(u"ñ–", u"னூ")
    translated = translated.replace(u"ñ", u"னு")
    translated = translated.replace(u"ð", u"னீ")
    translated = translated.replace(u"ï", u"னி")
    translated = translated.replace(u"î‘", u"னா")
    translated = translated.replace(u"î", u"ன")

    # ப Family
    translated = translated.replace(u"¿", u"ப்")
    translated = translated.replace(u"—ºã", u"பௌ")
    translated = translated.replace(u"þº‘", u"போ")
    translated = translated.replace(u"—º‘", u"பொ")
    translated = translated.replace(u"€º", u"பை")
    translated = translated.replace(u"þº", u"பே")
    translated = translated.replace(u"—º", u"பெ")
    translated = translated.replace(u"¾", u"பூ")
    translated = translated.replace(u"½", u"பு")
    translated = translated.replace(u"¼", u"பீ")
    translated = translated.replace(u"»", u"பி")
    translated = translated.replace(u"º‘", u"பா")
    translated = translated.replace(u"º", u"ப")

    # ம Family
    translated = translated.replace(u"Å", u"ம்")
    translated = translated.replace(u"—Àã", u"மௌ")
    translated = translated.replace(u"þÀ‘", u"மோ")
    translated = translated.replace(u"—À‘", u"மொ")
    translated = translated.replace(u"€À", u"மை")
    translated = translated.replace(u"þÀ", u"மே")
    translated = translated.replace(u"—À", u"மெ")
    translated = translated.replace(u"Ä", u"மூ")
    translated = translated.replace(u"Ã", u"மு")
    translated = translated.replace(u"Â", u"மீ")
    translated = translated.replace(u"Á", u"மி")
    translated = translated.replace(u"À‘", u"மா")
    translated = translated.replace(u"À", u"ம")

    # ய Family
    translated = translated.replace(u"Ë", u"ய்")
    translated = translated.replace(u"—Æã", u"யௌ")
    translated = translated.replace(u"þÆ‘", u"யோ")
    translated = translated.replace(u"—Æ‘", u"யொ")
    translated = translated.replace(u"€Æ", u"யை")
    translated = translated.replace(u"þÆ", u"யே")
    translated = translated.replace(u"—Æ", u"யெ")
    translated = translated.replace(u"Ê", u"யூ")
    translated = translated.replace(u"É", u"யு")
    translated = translated.replace(u"È", u"யீ")
    translated = translated.replace(u"Ç", u"யி")
    translated = translated.replace(u"Æ‘", u"யா")
    translated = translated.replace(u"Æ", u"ய")

    # ர Family
    translated = translated.replace(u"Ñ", u"ர்")
    translated = translated.replace(u"—Ìã", u"ரௌ")
    translated = translated.replace(u"þÌ‘", u"ரோ")
    translated = translated.replace(u"—Ì‘", u"ரொ")
    translated = translated.replace(u"€Ì", u"ரை")
    translated = translated.replace(u"þÌ", u"ரே")
    translated = translated.replace(u"—Ì", u"ரெ")
    translated = translated.replace(u"Ð", u"ரூ")
    translated = translated.replace(u"Ï", u"ரு")
    translated = translated.replace(u"Î", u"ரீ")
    translated = translated.replace(u"Í", u"ரி")
    translated = translated.replace(u"Ì‘", u"ரா")
    translated = translated.replace(u"Ì", u"ர")

    # ற Family
    translated = translated.replace(u"í", u"ற்")
    translated = translated.replace(u"—éé", u"றௌ")
    translated = translated.replace(u"þé‘", u"றோ")
    translated = translated.replace(u"—é‘", u"றொ")
    translated = translated.replace(u"€é", u"றை")
    translated = translated.replace(u"þé", u"றே")
    translated = translated.replace(u"—Ì", u"ரெ")
    translated = translated.replace(u"ì–", u"றூ")
    translated = translated.replace(u"ì", u"று")
    translated = translated.replace(u"ë", u"றீ")
    translated = translated.replace(u"ê", u"றி")
    translated = translated.replace(u"é‘", u"றா")
    translated = translated.replace(u"é", u"ற")

    # ல Family
    translated = translated.replace(u"Ö", u"ல்")
    translated = translated.replace(u"—Òã", u"லௌ")
    translated = translated.replace(u"þÒ‘", u"லோ")
    translated = translated.replace(u"—Ò‘", u"லொ")
    translated = translated.replace(u"€Ò", u"லை")
    translated = translated.replace(u"þÒ", u"லே")
    translated = translated.replace(u"—Ò", u"லெ")
    translated = translated.replace(u"Õ–", u"லூ")
    translated = translated.replace(u"Õ", u"லு")
    translated = translated.replace(u"Ô", u"லீ")
    translated = translated.replace(u"Ó", u"லி")
    translated = translated.replace(u"Ò‘", u"லா")
    translated = translated.replace(u"Ò", u"ல")

    # ள Family
    translated = translated.replace(u"è", u"ள்")
    translated = translated.replace(u"—ãã", u"ளௌ")
    translated = translated.replace(u"þã‘", u"ளோ")
    translated = translated.replace(u"€ã", u"ளை")
    translated = translated.replace(u"þã", u"ளே")
    translated = translated.replace(u"—ã", u"ளெ")
    translated = translated.replace(u"ç", u"ளூ")
    translated = translated.replace(u"æ", u"ளு")
    translated = translated.replace(u"å", u"ளீ")
    translated = translated.replace(u"ä", u"ளி")
    translated = translated.replace(u"ã‘", u"ளா")
    translated = translated.replace(u"ã", u"ள")

    # ழ Family
    translated = translated.replace(u"â", u"ழ்")
    translated = translated.replace(u"—ÝÝ", u"ழௌ")
    translated = translated.replace(u"þÝ‘", u"ழோ")
    translated = translated.replace(u"—Ý‘", u"ழொ")
    translated = translated.replace(u"€Ý", u"ழை")
    translated = translated.replace(u"þÝ", u"ழே")
    translated = translated.replace(u"—Ý", u"ழெ")
    translated = translated.replace(u"á", u"ழூ")
    translated = translated.replace(u"à", u"ழு")
    translated = translated.replace(u"ß", u"ழீ")
    translated = translated.replace(u"Þ", u"ழி")
    translated = translated.replace(u"Ý‘", u"ழா")
    translated = translated.replace(u"Ý", u"ழ")

    # வ Family
    translated = translated.replace(u"Ü", u"வ்")
    translated = translated.replace(u"—××", u"வௌ")
    translated = translated.replace(u"þ×‘", u"வோ")
    translated = translated.replace(u"—×‘", u"வொ")
    translated = translated.replace(u"€×", u"வை")
    translated = translated.replace(u"þ×", u"வே")
    translated = translated.replace(u"—×", u"வெ")
    translated = translated.replace(u"Û", u"வூ")
    translated = translated.replace(u"Ú", u"வு")
    translated = translated.replace(u"Ù", u"வீ")
    translated = translated.replace(u"Ø", u"வி")
    translated = translated.replace(u"×‘", u"வா")
    translated = translated.replace(u"×", u"வ")

    # ஷ Family
    translated = translated.replace(u"è", u"ஷ்")
    translated = translated.replace(u"öåå", u"ஷௌ")
    translated = translated.replace(u"÷åõ", u"ஷோ")
    translated = translated.replace(u"öåõ", u"ஷொ")
    translated = translated.replace(u"øå", u"ஷை")
    translated = translated.replace(u"÷å", u"ஷே")
    translated = translated.replace(u"öå", u"ஷெ")
    translated = translated.replace(u"ç", u"ஷீ")
    translated = translated.replace(u"æ", u"ஷி")
    translated = translated.replace(u"åõ", u"ஷா")
    translated = translated.replace(u"å", u"ஷ")

    # ஸ Family
    translated = translated.replace(u"ø", u"ஸ்")
    translated = translated.replace(u"—÷÷", u"ஸௌ")
    translated = translated.replace(u"þ÷‘", u"ஸோ")
    translated = translated.replace(u"—÷‘", u"ஸொ")
    translated = translated.replace(u"€÷", u"ஸை")
    translated = translated.replace(u"þ÷", u"ஸே")
    translated = translated.replace(u"—÷", u"ஸெ")
    translated = translated.replace(u"÷", u"ஸீ")
    translated = translated.replace(u"÷", u"ஸி")
    translated = translated.replace(u"÷‘", u"ஸா")
    translated = translated.replace(u"÷", u"ஸ")

    # ஹ Family
    translated = translated.replace(u"ú", u"ஹ்")
    translated = translated.replace(u"—ùù", u"ஹௌ")
    translated = translated.replace(u"þù‘", u"ஹோ")
    translated = translated.replace(u"—ù‘", u"ஹொ")
    translated = translated.replace(u"€ù", u"ஹை")
    translated = translated.replace(u"þù", u"ஹே")
    translated = translated.replace(u"—ù", u"ஹெ")
    translated = translated.replace(u"ù", u"ஹீ")
    translated = translated.replace(u"ù", u"ஹி")
    translated = translated.replace(u"ù‘", u"ஹா")
    translated = translated.replace(u"ù", u"ஹ")

    unconverted = [i for i in translated if i in source_text and not i in
                    punctuation+whitespace+digits]
    translated_trimed = ''.join([i for i in translated if not i in unconverted])

    if debug:
        return unconverted
    elif filtered:
        return translated_trimed
    else:
        return translated