# -*- coding: utf-8 -*-
from string import punctuation, whitespace, digits


def convertTounicode(source_text, filtered=False, debug=False):
    translated = source_text
    # Independent Vowels
    translated = translated.replace(u"m", u"அ")
    translated = translated.replace(u"M", u"ஆ")
    translated = translated.replace(u",", u"இ")
    translated = translated.replace(u"<", u"ஈ")
    translated = translated.replace(u"c", u"உ")
    translated = translated.replace(u"C", u"ஊ")
    translated = translated.replace(u"v", u"எ")
    translated = translated.replace(u"V", u"ஏ")
    translated = translated.replace(u"I", u"ஐ")
    translated = translated.replace(u"x", u"ஒ")
    translated = translated.replace(u"X", u"ஓ")
    translated = translated.replace(u"xs", u"ஔ")
    translated = translated.replace(u"\/", u"ஃ")

    #---
    translated = translated.replace(u"hP", u"ரீ")
    translated = translated.replace(u"hp", u"ரி")
    translated = translated.replace(u"H", u"ர்")
    translated = translated.replace(u"h;", u"ர்")
    translated = translated.replace(u"u;", u"ர்")

    # க Family
    translated = translated.replace(u"f;", u"க்")
    translated = translated.replace(u"nfs", u"கௌ")
    translated = translated.replace(u"Nfh", u"கோ")
    translated = translated.replace(u"nfh", u"கொ")
    translated = translated.replace(u"if", u"கை")
    translated = translated.replace(u"Nf", u"கே")
    translated = translated.replace(u"nf", u"கெ")
    translated = translated.replace(u"\$", u"கூ")
    translated = translated.replace(u"F", u"கு")
    translated = translated.replace(u"fP", u"கீ")
    translated = translated.replace(u"fp", u"கி")
    translated = translated.replace(u"fh", u"கா")
    translated = translated.replace(u"f", u"க")

    # ங Family
    translated = translated.replace(u"q;", u"ங்")
    translated = translated.replace(u"nqs", u"ஙௌ")
    translated = translated.replace(u"Nqh", u"ஙோ")
    translated = translated.replace(u"nqh", u"ஙொ")
    translated = translated.replace(u"iq", u"ஙை")
    translated = translated.replace(u"Nq", u"ஙே")
    translated = translated.replace(u"nq", u"ஙெ")
    translated = translated.replace(u"qP", u"ஙீ")
    translated = translated.replace(u"qp", u"ஙி")
    translated = translated.replace(u"qh", u"ஙா")
    translated = translated.replace(u"q", u"ங")

    # ச Family
    translated = translated.replace(u"r;", u"ச்")
    translated = translated.replace(u"nrs", u"சௌ")
    translated = translated.replace(u"Nrh", u"சோ")
    translated = translated.replace(u"nrh", u"சொ")
    translated = translated.replace(u"ir", u"சை")
    translated = translated.replace(u"Nr", u"சே")
    translated = translated.replace(u"nr", u"செ")
    translated = translated.replace(u"#", u"சூ")
    translated = translated.replace(u"R", u"சு")
    translated = translated.replace(u"rP", u"சீ")
    translated = translated.replace(u"rp", u"சி")
    translated = translated.replace(u"rh", u"சா")
    translated = translated.replace(u"r", u"ச")

    # ஜ Family
    translated = translated.replace(u"\[;", u"ஜ்")
    translated = translated.replace(u"n\[s", u"ஜௌ")
    translated = translated.replace(u"N\[h", u"ஜோ")
    translated = translated.replace(u"n\[h", u"ஜொ")
    translated = translated.replace(u"i\[", u"ஜை")
    translated = translated.replace(u"N\[", u"ஜே")
    translated = translated.replace(u"n\[", u"ஜெ")
    translated = translated.replace(u"\[_", u"ஜூ")
    translated = translated.replace(u"\[{", u"ஜு")
    translated = translated.replace(u"\[P", u"ஜீ")
    translated = translated.replace(u"\[p", u"ஜி")
    translated = translated.replace(u"\[h", u"ஜா")
    translated = translated.replace(u"\[", u"ஜ")

    # ஞ Family
    translated = translated.replace(u"Q;", u"ஞ்")
    translated = translated.replace(u"nQs", u"ஞௌ")
    translated = translated.replace(u"NQh", u"ஞோ")
    translated = translated.replace(u"nQh", u"ஞொ")
    translated = translated.replace(u"iQ", u"ஞை")
    translated = translated.replace(u"NQ", u"ஞே")
    translated = translated.replace(u"nQ", u"ஞெ")
    translated = translated.replace(u"QP", u"ஞீ")
    translated = translated.replace(u"Qp", u"ஞி")
    translated = translated.replace(u"Qh", u"ஞா")
    translated = translated.replace(u"Q", u"ஞ")

    # ட Family
    translated = translated.replace(u"l;", u"ட்")
    translated = translated.replace(u"nls", u"டௌ")
    translated = translated.replace(u"Nlh", u"டோ")
    translated = translated.replace(u"nlh", u"டொ")
    translated = translated.replace(u"il", u"டை")
    translated = translated.replace(u"Nl", u"டே")
    translated = translated.replace(u"nl", u"டெ")
    translated = translated.replace(u"\^", u"டூ")
    translated = translated.replace(u"L", u"டு")
    translated = translated.replace(u"lP", u"டீ")
    translated = translated.replace(u"lp", u"டி")
    translated = translated.replace(u"b", u"டி")
    translated = translated.replace(u"lh", u"டா")
    translated = translated.replace(u"l", u"ட")

    # ண Family
    translated = translated.replace(u"z;", u"ண்")
    translated = translated.replace(u"nzs", u"ணௌ")
    translated = translated.replace(u"Nzh", u"ணோ")
    translated = translated.replace(u"nzh", u"ணொ")
    translated = translated.replace(u"iz", u"ணை")
    translated = translated.replace(u"Nz", u"ணே")
    translated = translated.replace(u"nz", u"ணெ")
    translated = translated.replace(u"Zh", u"ணூ")
    translated = translated.replace(u"Z", u"ணு")
    translated = translated.replace(u"zP", u"ணீ")
    translated = translated.replace(u"zp", u"ணி")
    translated = translated.replace(u"zh", u"ணா")
    translated = translated.replace(u"z", u"ண")

    # த Family
    translated = translated.replace(u"j;", u"த்")
    translated = translated.replace(u"njs", u"தௌ")
    translated = translated.replace(u"Njh", u"தோ")
    translated = translated.replace(u"njh", u"தொ")
    translated = translated.replace(u"ij", u"தை")
    translated = translated.replace(u"Nj", u"தே")
    translated = translated.replace(u"nj", u"தெ")
    translated = translated.replace(u"Jh", u"தூ")
    translated = translated.replace(u"J}", u"தூ")
    translated = translated.replace(u"J", u"து")
    translated = translated.replace(u"jP", u"தீ")
    translated = translated.replace(u"jp", u"தி")
    translated = translated.replace(u"jh", u"தா")
    translated = translated.replace(u"j", u"த")

    # ந Family
    translated = translated.replace(u"e;", u"ந்")
    translated = translated.replace(u"nes", u"நௌ")
    translated = translated.replace(u"Neh", u"நோ")
    translated = translated.replace(u"neh", u"நொ")
    translated = translated.replace(u"ie", u"நை")
    translated = translated.replace(u"Ne", u"நே")
    translated = translated.replace(u"ne", u"நெ")
    translated = translated.replace(u"E}", u"நூ")
    translated = translated.replace(u"Eh", u"நூ")
    translated = translated.replace(u"E", u"நு")
    translated = translated.replace(u"eP", u"நீ")
    translated = translated.replace(u"ep", u"நி")
    translated = translated.replace(u"eh", u"நா")
    translated = translated.replace(u"e", u"ந")

    # ன Family
    translated = translated.replace(u"d;", u"ன்")
    translated = translated.replace(u"nds", u"னௌ")
    translated = translated.replace(u"Ndh", u"னோ")
    translated = translated.replace(u"ndh", u"னொ")
    translated = translated.replace(u"id", u"னை")
    translated = translated.replace(u"Nd", u"னே")
    translated = translated.replace(u"nd", u"னெ")
    translated = translated.replace(u"D}", u"னூ")
    translated = translated.replace(u"D", u"னு")
    translated = translated.replace(u"dP", u"னீ")
    translated = translated.replace(u"dp", u"னி")
    translated = translated.replace(u"dh", u"னா")
    translated = translated.replace(u"d", u"ன")

    # ப Family
    translated = translated.replace(u"g;", u"ப்")
    translated = translated.replace(u"ngs", u"பௌ")
    translated = translated.replace(u"Ngh", u"போ")
    translated = translated.replace(u"ngh", u"பொ")
    translated = translated.replace(u"ig", u"பை")
    translated = translated.replace(u"Ng", u"பே")
    translated = translated.replace(u"ng", u"பெ")
    translated = translated.replace(u"G\+", u"பூ")
    translated = translated.replace(u"G", u"பு")
    translated = translated.replace(u"gP", u"பீ")
    translated = translated.replace(u"gp", u"பி")
    translated = translated.replace(u"gh", u"பா")
    translated = translated.replace(u"g", u"ப")

    # ம Family
    translated = translated.replace(u"k;", u"ம்")
    translated = translated.replace(u"nks", u"மௌ")
    translated = translated.replace(u"Nkh", u"மோ")
    translated = translated.replace(u"nkh", u"மொ")
    translated = translated.replace(u"ik", u"மை")
    translated = translated.replace(u"Nk", u"மே")
    translated = translated.replace(u"nk", u"மெ")
    translated = translated.replace(u"%", u"மூ")
    translated = translated.replace(u"K", u"மு")
    translated = translated.replace(u"kP", u"மீ")
    translated = translated.replace(u"kp", u"மி")
    translated = translated.replace(u"kh", u"மா")
    translated = translated.replace(u"k", u"ம")

    # ய Family
    translated = translated.replace(u"a;", u"ய்")
    translated = translated.replace(u"nas", u"யௌ")
    translated = translated.replace(u"Nah", u"யோ")
    translated = translated.replace(u"nah", u"யொ")
    translated = translated.replace(u"ia", u"யை")
    translated = translated.replace(u"Na", u"யே")
    translated = translated.replace(u"na", u"யெ")
    translated = translated.replace(u"A+", u"யூ")
    translated = translated.replace(u"A", u"யு")
    translated = translated.replace(u"aP", u"யீ")
    translated = translated.replace(u"ap", u"யி")
    translated = translated.replace(u"ah", u"யா")
    translated = translated.replace(u"a", u"ய")

    # ர Family
    translated = translated.replace(u"nus", u"ரௌ")
    translated = translated.replace(u"Nuh", u"ரோ")
    translated = translated.replace(u"nuh", u"ரொ")
    translated = translated.replace(u"iu", u"ரை")
    translated = translated.replace(u"Nu", u"ரே")
    translated = translated.replace(u"nu", u"ரெ")
    translated = translated.replace(u"&", u"ரூ")
    translated = translated.replace(u"U", u"ரு")
    translated = translated.replace(u"uh", u"ரா")
    translated = translated.replace(u"u", u"ர")

    # ற Family
    translated = translated.replace(u"w;", u"ற்")
    translated = translated.replace(u"nws", u"றௌ")
    translated = translated.replace(u"Nwh", u"றோ")
    translated = translated.replace(u"nwh", u"றொ")
    translated = translated.replace(u"iw", u"றை")
    translated = translated.replace(u"Nw", u"றே")
    translated = translated.replace(u"nu", u"ரெ")
    translated = translated.replace(u"Wh", u"றூ")
    translated = translated.replace(u"W}", u"றூ")
    translated = translated.replace(u"W", u"று")
    translated = translated.replace(u"wP", u"றீ")
    translated = translated.replace(u"wp", u"றி")
    translated = translated.replace(u"wh", u"றா")
    translated = translated.replace(u"w", u"ற")

    # ல Family
    translated = translated.replace(u"y;", u"ல்")
    translated = translated.replace(u"nys", u"லௌ")
    translated = translated.replace(u"Nyh", u"லோ")
    translated = translated.replace(u"nyh", u"லொ")
    translated = translated.replace(u"iy", u"லை")
    translated = translated.replace(u"Ny", u"லே")
    translated = translated.replace(u"ny", u"லெ")
    translated = translated.replace(u"Yh", u"லூ")
    translated = translated.replace(u"Y}", u"லூ")
    translated = translated.replace(u"Y", u"லு")
    translated = translated.replace(u"yP", u"லீ")
    translated = translated.replace(u"yp", u"லி")
    translated = translated.replace(u"yh", u"லா")
    translated = translated.replace(u"y", u"ல")

    # ள Family
    translated = translated.replace(u"s;", u"ள்")
    translated = translated.replace(u"nss", u"ளௌ")
    translated = translated.replace(u"Nsh", u"ளோ")
    translated = translated.replace(u"is", u"ளை")
    translated = translated.replace(u"Ns", u"ளே")
    translated = translated.replace(u"ns", u"ளெ")
    translated = translated.replace(u"Sh", u"ளூ")
    translated = translated.replace(u"S", u"ளு")
    translated = translated.replace(u"sP", u"ளீ")
    translated = translated.replace(u"sp", u"ளி")
    translated = translated.replace(u"sh", u"ளா")
    translated = translated.replace(u"s", u"ள")

    # ழ Family
    translated = translated.replace(u"o;", u"ழ்")
    translated = translated.replace(u"noo", u"ழௌ")
    translated = translated.replace(u"Noh", u"ழோ")
    translated = translated.replace(u"noh", u"ழொ")
    translated = translated.replace(u"io", u"ழை")
    translated = translated.replace(u"No", u"ழே")
    translated = translated.replace(u"no", u"ழெ")
    translated = translated.replace(u"\*", u"ழூ")
    translated = translated.replace(u"O", u"ழு")
    translated = translated.replace(u"oP", u"ழீ")
    translated = translated.replace(u"op", u"ழி")
    translated = translated.replace(u"oh", u"ழா")
    translated = translated.replace(u"o", u"ழ")

    # வ Family
    translated = translated.replace(u"t;", u"வ்")
    translated = translated.replace(u"ntt", u"வௌ")
    translated = translated.replace(u"Nth", u"வோ")
    translated = translated.replace(u"nth", u"வொ")
    translated = translated.replace(u"it", u"வை")
    translated = translated.replace(u"Nt", u"வே")
    translated = translated.replace(u"nt", u"வெ")
    translated = translated.replace(u"வு10", u"வூ")
    translated = translated.replace(u"T", u"வு")
    translated = translated.replace(u"tP", u"வீ")
    translated = translated.replace(u"tp", u"வி")
    translated = translated.replace(u"th", u"வா")
    translated = translated.replace(u"t", u"வ")

    # ஷ Family
    translated = translated.replace(u"\\;", u"ஷ்")
    translated = translated.replace(u"n\\s", u"ஷௌ")
    translated = translated.replace(u"N\\h", u"ஷோ")
    translated = translated.replace(u"n\\h", u"ஷொ")
    translated = translated.replace(u"i\\", u"ஷை")
    translated = translated.replace(u"N\\", u"ஷே")
    translated = translated.replace(u"n\\", u"ஷெ")
    translated = translated.replace(u"\\P", u"ஷீ")
    translated = translated.replace(u"\\p", u"ஷி")
    translated = translated.replace(u"\\h", u"ஷா")
    translated = translated.replace(u"\\", u"ஷ")

    # ஸ Family
    translated = translated.replace(u"];", u"ஸ்")
    translated = translated.replace(u"n]s", u"ஸௌ")
    translated = translated.replace(u"N]h", u"ஸோ")
    translated = translated.replace(u"n]h", u"ஸொ")
    translated = translated.replace(u"i]", u"ஸை")
    translated = translated.replace(u"N]", u"ஸே")
    translated = translated.replace(u"n]", u"ஸெ")
    translated = translated.replace(u"]P", u"ஸீ")
    translated = translated.replace(u"]p", u"ஸி")
    translated = translated.replace(u"]h", u"ஸா")
    translated = translated.replace(u"]", u"ஸ")

    # ஹ Family
    translated = translated.replace(u"`;", u"ஹ்")
    translated = translated.replace(u"n``", u"ஹௌ")
    translated = translated.replace(u"N`h", u"ஹோ")
    translated = translated.replace(u"n`h", u"ஹொ")
    translated = translated.replace(u"i`", u"ஹை")
    translated = translated.replace(u"N`", u"ஹே")
    translated = translated.replace(u"n`", u"ஹெ")
    translated = translated.replace(u"`P", u"ஹீ")
    translated = translated.replace(u"`p", u"ஹி")
    translated = translated.replace(u"`h", u"ஹா")
    translated = translated.replace(u"`", u"ஹ")

    translated = translated.replace(u"=", u"ஸ்ரீ")

    unconverted = [i for i in translated if i in source_text and not i in
                    punctuation+whitespace+digits]
    translated_trimed = ''.join([i for i in translated if not i in unconverted])

    if debug:
        return unconverted
    elif filtered:
        return translated_trimed
    else:
        return translated