# -*- coding: utf-8 -*-
from string import punctuation, whitespace, digits


def convertTounicode(source_text, filtered=False, debug=False):
    translated = source_text
    # Independent Vowels
    translated = translated.replace(u"∂", u"அ")
    translated = translated.replace(u"g", u"ஆ")
    translated = translated.replace(u"÷", u"இ")
    translated = translated.replace(u"~", u"ஈ")
    translated = translated.replace(u"c", u"உ")
    translated = translated.replace(u"ª", u"ஊ")
    translated = translated.replace(u"®", u"எ")
    translated = translated.replace(u"∞", u"ஏ")
    translated = translated.replace(u"n", u"ஐ")
    translated = translated.replace(u"Œ", u"ஒ")
    translated = translated.replace(u"{", u"ஓ")
    translated = translated.replace(u"¡", u"ஔ")
    translated = translated.replace(u"‡", u"ஃ")
    translated = translated.replace(u"{D", u"ௐ")
    translated = translated.replace(u"p", u"ஸ்ரீ")

    # க Family
    translated = translated.replace(u"¬", u"க்")
    translated = translated.replace(u"ÿÔe", u"கௌ")
    translated = translated.replace(u"ºÔV", u"கோ")
    translated = translated.replace(u"ÿÔV", u"கொ")
    translated = translated.replace(u"ÁÔ", u"கை")
    translated = translated.replace(u"ºÔ", u"கே")
    translated = translated.replace(u"ÿÔ", u"கெ")
    translated = translated.replace(u"Ì", u"கூ")
    translated = translated.replace(u"z", u"கு")
    translated = translated.replace(u"ˇ", u"கீ")
    translated = translated.replace(u"˛", u"கி")
    translated = translated.replace(u"ÔV", u"கா")
    translated = translated.replace(u"Ô", u"க")

    # ங Family
    translated = translated.replace(u"∫", u"ங்")
    translated = translated.replace(u"ÿÙe", u"ஙௌ")
    translated = translated.replace(u"ºÙV", u"ஙோ")
    translated = translated.replace(u"ÿÙV", u"ஙொ")
    translated = translated.replace(u"ÁÙ", u"ஙை")
    translated = translated.replace(u"ºÙ", u"ஙே")
    translated = translated.replace(u"ÿÙ", u"ஙெ")
    #translated = translated.replace(u"", u"ஙூ")
    #translated = translated.replace(u"", u"ஙு")
    #translated = translated.replace(u"", u"ஙீ")
    #translated = translated.replace(u"", u"ஙி")
    translated = translated.replace(u"ÙV", u"ஙா")
    translated = translated.replace(u"Ù", u"ங")

    # ச Family
    translated = translated.replace(u"á", u"ச்")
    translated = translated.replace(u"ÿƒe", u"சௌ")
    translated = translated.replace(u"ºƒV", u"சோ")
    translated = translated.replace(u"ÿƒV", u"சொ")
    translated = translated.replace(u"Áƒ", u"சை")
    translated = translated.replace(u"ºƒ", u"சே")
    translated = translated.replace(u"ÿƒ", u"செ")
    translated = translated.replace(u"Û", u"சூ")
    translated = translated.replace(u"à", u"சு")
    translated = translated.replace(u"Ê", u"சீ")
    translated = translated.replace(u"E", u"சி")
    translated = translated.replace(u"ƒV", u"சா")
    translated = translated.replace(u"ƒ", u"ச")

    # ஜ Family
    translated = translated.replace(u"Î", u"ஜ்")
    translated = translated.replace(u"ÿÖe", u"ஜௌ")
    translated = translated.replace(u"ºÖV", u"ஜோ")
    translated = translated.replace(u"ÿÖV", u"ஜொ")
    translated = translated.replace(u"ÁÖ", u"ஜை")
    translated = translated.replace(u"ºÖ", u"ஜே")
    translated = translated.replace(u"ÿÖ", u"ஜெ")
    translated = translated.replace(u"…", u"ஜூ")
    translated = translated.replace(u"h", u"ஜு")
    translated = translated.replace(u"ä", u"ஜீ")
    translated = translated.replace(u"˜", u"ஜி")
    translated = translated.replace(u"ÖV", u"ஜா")
    translated = translated.replace(u"Ö", u"ஜ")

    # ஞ Family
    translated = translated.replace(u"â", u"ஞ்")
    translated = translated.replace(u"ÿQe", u"ஞௌ")
    translated = translated.replace(u"ºQV", u"ஞோ")
    translated = translated.replace(u"ÿQV", u"ஞொ")
    translated = translated.replace(u"ÁQ", u"ஞை")
    translated = translated.replace(u"ºQ", u"ஞே")
    translated = translated.replace(u"ÿQ", u"ஞெ")
    #translated = translated.replace(u"", u"ஞூ")
    #translated = translated.replace(u"", u"ஞு")
    #translated = translated.replace(u"", u"ஞீ")
    #translated = translated.replace(u"", u"ஞி")
    translated = translated.replace(u"QV", u"ஞா")
    translated = translated.replace(u"Q", u"ஞ")

    # ட Family
    translated = translated.replace(u"‚", u"ட்")
    translated = translated.replace(u"ÿ¶e", u"டௌ")
    translated = translated.replace(u"º¶V", u"டோ")
    translated = translated.replace(u"ÿ¶V", u"டொ")
    translated = translated.replace(u"Á¶", u"டை")
    translated = translated.replace(u"º¶", u"டே")
    translated = translated.replace(u"ÿ¶", u"டெ")
    translated = translated.replace(u"˘", u"டூ")
    translated = translated.replace(u"|", u"டு")
    translated = translated.replace(u"œ", u"டீ")
    translated = translated.replace(u"É", u"டி")
    translated = translated.replace(u"¶V", u"டா")
    translated = translated.replace(u"¶", u"ட")

    # ண Family
    translated = translated.replace(u"ı", u"ண்")
    translated = translated.replace(u"ÿÜe", u"ணௌ")
    translated = translated.replace(u"ºÜV", u"ணோ")
    translated = translated.replace(u"ÿÜV", u"ணொ")
    translated = translated.replace(u"ÁÜ", u"ணை")
    translated = translated.replace(u"ºÜ", u"ணே")
    translated = translated.replace(u"ÿÜ", u"ணெ")
    translated = translated.replace(u"I", u"ணூ")
    translated = translated.replace(u"Ó", u"ணு")
    translated = translated.replace(u"ß", u"ணீ")
    translated = translated.replace(u"Ë", u"ணி")
    translated = translated.replace(u"ÜV", u"ணா")
    translated = translated.replace(u"Ü", u"ண")

    # த Family
    translated = translated.replace(u"›", u"த்")
    translated = translated.replace(u"ÿ>e", u"தௌ")
    translated = translated.replace(u"º>V", u"தோ")
    translated = translated.replace(u"ÿ>V", u"தொ")
    translated = translated.replace(u"Á>", u"தை")
    translated = translated.replace(u"º>", u"தே")
    translated = translated.replace(u"ÿ>", u"தெ")
    translated = translated.replace(u"#", u"தூ")
    translated = translated.replace(u"m", u"து")
    translated = translated.replace(u"y", u"தீ")
    translated = translated.replace(u"]", u"தி")
    translated = translated.replace(u">V", u"தா")
    translated = translated.replace(u">", u"த")

    # ந Family
    translated = translated.replace(u"Õ", u"ந்")
    translated = translated.replace(u"ÿÂe", u"நௌ")
    translated = translated.replace(u"ºÂV", u"நோ")
    translated = translated.replace(u"ÿÂV", u"நொ")
    translated = translated.replace(u"ÁÂ", u"நை")
    translated = translated.replace(u"ºÂ", u"நே")
    translated = translated.replace(u"ÿÂ", u"நெ")
    translated = translated.replace(u"±", u"நூ")
    translated = translated.replace(u"O", u"நு")
    translated = translated.replace(u"¿", u"நீ")
    translated = translated.replace(u"W", u"நி")
    translated = translated.replace(u"ÂV", u"நா")
    translated = translated.replace(u"Â", u"ந")

    # ன Family
    translated = translated.replace(u"[", u"ன்")
    translated = translated.replace(u"ÿ™e", u"னௌ")
    translated = translated.replace(u"º™V", u"னோ")
    translated = translated.replace(u"ÿ™V", u"னொ")
    translated = translated.replace(u"Á™", u"னை")
    translated = translated.replace(u"º™", u"னே")
    translated = translated.replace(u"ÿ™", u"னெ")
    translated = translated.replace(u"˚", u"னூ")
    translated = translated.replace(u"–", u"னு")
    translated = translated.replace(u"Ã", u"னீ")
    translated = translated.replace(u"M", u"னி")
    translated = translated.replace(u"™V", u"னா")
    translated = translated.replace(u"™", u"ன")

    # ப Family
    translated = translated.replace(u"©", u"ப்")
    translated = translated.replace(u"ÿ√e", u"பௌ")
    translated = translated.replace(u"º√V", u"போ")
    translated = translated.replace(u"ÿ√V", u"பொ")
    translated = translated.replace(u"Á√", u"பை")
    translated = translated.replace(u"º√", u"பே")
    translated = translated.replace(u"ÿ√", u"பெ")
    translated = translated.replace(u"Ø", u"பூ")
    translated = translated.replace(u"A", u"பு")
    translated = translated.replace(u"¨", u"பீ")
    translated = translated.replace(u"∏", u"பி")
    translated = translated.replace(u"√V", u"பா")
    translated = translated.replace(u"√", u"ப")

    # ம Family
    translated = translated.replace(u"D", u"ம்")
    translated = translated.replace(u"ÿ\\e", u"மௌ")
    translated = translated.replace(u"º\\V", u"மோ")
    translated = translated.replace(u"ÿ\\V", u"மொ")
    translated = translated.replace(u"Á\\", u"மை")
    translated = translated.replace(u"º\\", u"மே")
    translated = translated.replace(u"ÿ\\", u"மெ")
    translated = translated.replace(u"J", u"மூ")
    translated = translated.replace(u"x", u"மு")
    translated = translated.replace(u"*", u"மீ")
    translated = translated.replace(u"t", u"மி")
    translated = translated.replace(u"\\V", u"மா")
    translated = translated.replace(u"\\", u"ம")

    # ய Family
    translated = translated.replace(u"F", u"ய்")
    translated = translated.replace(u"ÿBe", u"யௌ")
    translated = translated.replace(u"ºBV", u"யோ")
    translated = translated.replace(u"ÿBV", u"யொ")
    translated = translated.replace(u"ÁB", u"யை")
    translated = translated.replace(u"ºB", u"யே")
    translated = translated.replace(u"ÿB", u"யெ")
    translated = translated.replace(u"R", u"யூ")
    translated = translated.replace(u"•", u"யு")
    translated = translated.replace(u"X", u"யீ")
    translated = translated.replace(u"l", u"யி")
    translated = translated.replace(u"BV", u"யா")
    translated = translated.replace(u"B", u"ய")

    # ர Family
    translated = translated.replace(u"Ï", u"ர்")
    translated = translated.replace(u"ÿ´e", u"ரௌ")
    translated = translated.replace(u"º´V", u"ரோ")
    translated = translated.replace(u"ÿ´V", u"ரொ")
    translated = translated.replace(u"Á´", u"ரை")
    translated = translated.replace(u"º´", u"ரே")
    translated = translated.replace(u"ÿ´", u"ரெ")
    translated = translated.replace(u"‘", u"ரூ")
    translated = translated.replace(u"Ú", u"ரு")
    translated = translated.replace(u"Z", u"ரீ")
    translated = translated.replace(u"ˆ", u"ரி")
    translated = translated.replace(u"´V", u"ரா")
    translated = translated.replace(u"´", u"ர")

    # ற Family
    translated = translated.replace(u"u", u"ற்")
    translated = translated.replace(u"ÿ≈e", u"றௌ")
    translated = translated.replace(u"º≈V", u"றோ")
    translated = translated.replace(u"ÿ≈V", u"றொ")
    translated = translated.replace(u"Á≈", u"றை")
    translated = translated.replace(u"º≈", u"றே")
    translated = translated.replace(u"ÿ≈", u"ரெ")
    translated = translated.replace(u"G", u"றூ")
    translated = translated.replace(u"Æ", u"று")
    translated = translated.replace(u"S", u"றீ")
    translated = translated.replace(u"§", u"றி")
    translated = translated.replace(u"≈V", u"றா")
    translated = translated.replace(u"≈", u"ற")

    # ல Family
    translated = translated.replace(u"_", u"ல்")
    translated = translated.replace(u"ÿÈe", u"லௌ")
    translated = translated.replace(u"ºÈV", u"லோ")
    translated = translated.replace(u"ÿÈV", u"லொ")
    translated = translated.replace(u"ÁÈ", u"லை")
    translated = translated.replace(u"ºÈ", u"லே")
    translated = translated.replace(u"ÿÈ", u"லெ")
    translated = translated.replace(u"Ÿ", u"லூ")
    translated = translated.replace(u"K", u"லு")
    translated = translated.replace(u"‹", u"லீ")
    translated = translated.replace(u"o", u"லி")
    translated = translated.replace(u"ÈV", u"லா")
    translated = translated.replace(u"È", u"ல")

    # ள Family
    translated = translated.replace(u"^", u"ள்")
    translated = translated.replace(u"ÿee", u"ளௌ")
    translated = translated.replace(u"ºeV", u"ளோ")
    translated = translated.replace(u"ÿeV", u"ளொ")
    translated = translated.replace(u"Áe", u"ளை")
    translated = translated.replace(u"ºe", u"ளே")
    translated = translated.replace(u"ÿe", u"ளெ")
    translated = translated.replace(u"j", u"ளூ")
    translated = translated.replace(u"”", u"ளு")
    translated = translated.replace(u"C", u"ளீ")
    translated = translated.replace(u"Ñ", u"ளி")
    translated = translated.replace(u"eV", u"ளா")
    translated = translated.replace(u"e", u"ள")

    # ழ Family
    translated = translated.replace(u"µ", u"ழ்")
    translated = translated.replace(u"ÿwe", u"ழௌ")
    translated = translated.replace(u"ºwV", u"ழோ")
    translated = translated.replace(u"ÿwV", u"ழொ")
    translated = translated.replace(u"Áw", u"ழை")
    translated = translated.replace(u"ºw", u"ழே")
    translated = translated.replace(u"ÿw", u"ழெ")
    translated = translated.replace(u"Ò", u"ழூ")
    translated = translated.replace(u"ø", u"ழு")
    translated = translated.replace(u"—", u"ழீ")
    translated = translated.replace(u"a", u"ழி")
    translated = translated.replace(u"wV", u"ழா")
    translated = translated.replace(u"w", u"ழ")

    # வ Family
    translated = translated.replace(u"À", u"வ்")
    translated = translated.replace(u"ÿke", u"வௌ")
    translated = translated.replace(u"ºkV", u"வோ")
    translated = translated.replace(u"ÿkV", u"வொ")
    translated = translated.replace(u"Ák", u"வை")
    translated = translated.replace(u"ºk", u"வே")
    translated = translated.replace(u"ÿk", u"வெ")
    translated = translated.replace(u"∆", u"வூ")
    translated = translated.replace(u"°", u"வு")
    translated = translated.replace(u"T", u"வீ")
    translated = translated.replace(u"s", u"வி")
    translated = translated.replace(u"kV", u"வா")
    translated = translated.replace(u"k", u"வ")

    # ஷ Family
    translated = translated.replace(u"i", u"ஷ்")
    translated = translated.replace(u"ÿ≠e", u"ஷௌ")
    translated = translated.replace(u"º≠V", u"ஷோ")
    translated = translated.replace(u"ÿ≠V", u"ஷொ")
    translated = translated.replace(u"Á≠", u"ஷை")
    translated = translated.replace(u"º≠", u"ஷே")
    translated = translated.replace(u"ÿ≠", u"ஷெ")
    translated = translated.replace(u"£", u"ஷூ")
    translated = translated.replace(u"◊", u"ஷு")
    translated = translated.replace(u"U", u"ஷீ")
    translated = translated.replace(u"¥", u"ஷி")
    translated = translated.replace(u"≠V", u"ஷா")
    translated = translated.replace(u"≠", u"ஷ")

    # ஸ Family
    translated = translated.replace(u"¸", u"ஸ்")
    translated = translated.replace(u"ÿve", u"ஸௌ")
    translated = translated.replace(u"ºvV", u"ஸோ")
    translated = translated.replace(u"ÿvV", u"ஸொ")
    translated = translated.replace(u"Áv", u"ஸை")
    translated = translated.replace(u"ºv", u"ஸே")
    translated = translated.replace(u"ÿv", u"ஸெ")
    translated = translated.replace(u"`", u"ஸூ")
    translated = translated.replace(u"q", u"ஸு")
    translated = translated.replace(u"¢", u"ஸீ")
    translated = translated.replace(u"L", u"ஸி")
    translated = translated.replace(u"vV", u"ஸா")
    translated = translated.replace(u"v", u"ஸ")

    # ஹ Family
    translated = translated.replace(u"„", u"ஹ்")
    translated = translated.replace(u"ÿ«e", u"ஹௌ")
    translated = translated.replace(u"º«V", u"ஹோ")
    translated = translated.replace(u"ÿ«V", u"ஹொ")
    translated = translated.replace(u"Á«", u"ஹை")
    translated = translated.replace(u"º«", u"ஹே")
    translated = translated.replace(u"ÿ«", u"ஹெ")
    translated = translated.replace(u"Í", u"ஹீ")
    translated = translated.replace(u"N", u"ஹி")
    translated = translated.replace(u"«V", u"ஹா")
    translated = translated.replace(u"«", u"ஹ")

    # க்ஷ Family
    translated = translated.replace(u"’", u"க்ஷ்")
    translated = translated.replace(u"ÿ≥e", u"க்ஷௌ")
    translated = translated.replace(u"º≥V", u"க்ஷோ")
    translated = translated.replace(u"ÿ≥V", u"க்ஷொ")
    translated = translated.replace(u"Á≥", u"க்ஷை")
    translated = translated.replace(u"º≥", u"க்ஷே")
    translated = translated.replace(u"ÿ≥", u"க்ஷெ")
    translated = translated.replace(u"f", u"க்ஷூ")
    translated = translated.replace(u"Y", u"க்ஷு")
    translated = translated.replace(u"»", u"க்ஷீ")
    translated = translated.replace(u"H", u"க்ஷி")
    translated = translated.replace(u"≥V", u"க்ஷா")
    translated = translated.replace(u"≥", u"க்ஷ")


    unconverted = [i for i in translated if i in source_text and not i in
                    punctuation+whitespace+digits]
    translated_trimed = ''.join([i for i in translated if not i in unconverted])

    if debug:
        return unconverted
    elif filtered:
        return translated_trimed
    else:
        return translated

# print convertTounicode(u"7: ºƒ› ∞º™VÁƒ© ÿ√u≈∏[, ®ıIuº≈ø kÚ≠D clº´VÉÚÕm, z\V´Á´•D z\V´›]ÔÁe•D ÿ√u≈V[.")