# -*- coding: utf-8 -*-
from string import punctuation, whitespace, digits


def convertTounicode(source_text, filtered=False, debug=False):
    translated = source_text
    
    translated = translated.replace(u"í", u"அ")
    translated = translated.replace(u"Í", u"ஆ")
    translated = translated.replace(u"¬", u"இ")
    translated = translated.replace(u"¼", u"ஈ")
    translated = translated.replace(u"ã", u"உ")
    translated = translated.replace(u"Ã", u"ஊ")
    translated = translated.replace(u"ö", u"எ")
    translated = translated.replace(u"Ö", u"ஏ")
    translated = translated.replace(u"É", u"ஐ")
    translated = translated.replace(u"ø", u"ஒ")
    translated = translated.replace(u"Ø", u"ஓ")
    translated = translated.replace(u"øó", u"ஔ")
    translated = translated.replace(u"þ", u"ஃ")
    translated = translated.replace(u"ØÐ", u"ௐ")
    translated = translated.replace(u"¤", u"ஸ்ரீ")
    
    translated = translated.replace(u"æÐ", u"க்")
    translated = translated.replace(u"âæó", u"கௌ")
    translated = translated.replace(u"îæè", u"கோ")
    translated = translated.replace(u"âæè", u"கொ")
    translated = translated.replace(u"éæ", u"கை")
    translated = translated.replace(u"îæ", u"கே")
    translated = translated.replace(u"âæ", u"கெ")
    translated = translated.replace(u"Ô", u"கூ")
    translated = translated.replace(u"Æ", u"கு")
    translated = translated.replace(u"æ©", u"கீ")
    translated = translated.replace(u"æ¨", u"கி")
    translated = translated.replace(u"æè", u"கா")
    translated = translated.replace(u"æ", u"க")
    
    translated = translated.replace(u"§Ð", u"ங்")
    translated = translated.replace(u"â§ó", u"ஙௌ")
    translated = translated.replace(u"î§è", u"ஙோ")
    translated = translated.replace(u"â§è", u"ஙொ")
    translated = translated.replace(u"é§", u"ஙை")
    translated = translated.replace(u"î§", u"ஙே")
    translated = translated.replace(u"â§", u"ஙெ")
    translated = translated.replace(u"º", u"ஙூ")
    translated = translated.replace(u"³", u"ஙு")
    translated = translated.replace(u"§©", u"ஙீ")
    translated = translated.replace(u"§¨", u"ஙி")
    translated = translated.replace(u"§è", u"ஙா")
    translated = translated.replace(u"§", u"ங")
    
    translated = translated.replace(u"òÐ", u"ச்")
    translated = translated.replace(u"âòó", u"சௌ")
    translated = translated.replace(u"îòè", u"சோ")
    translated = translated.replace(u"âòè", u"சொ")
    translated = translated.replace(u"éò", u"சை")
    translated = translated.replace(u"îò", u"சே")
    translated = translated.replace(u"âò", u"செ")
    translated = translated.replace(u"Î", u"சூ")
    translated = translated.replace(u"à", u"சு")
    translated = translated.replace(u"ò©", u"சீ")
    translated = translated.replace(u"ò¨", u"சி")
    translated = translated.replace(u"òè", u"சா")
    translated = translated.replace(u"ò", u"ச")
    
    translated = translated.replace(u"£Ð", u"ஜ்")
    translated = translated.replace(u"â£ó", u"ஜௌ")
    translated = translated.replace(u"î£è", u"ஜோ")
    translated = translated.replace(u"â£è", u"ஜொ")
    translated = translated.replace(u"é£", u"ஜை")
    translated = translated.replace(u"î£", u"ஜே")
    translated = translated.replace(u"â£", u"ஜெ")
    translated = translated.replace(u"£ð", u"ஜூ")
    translated = translated.replace(u"£¦", u"ஜு")
    translated = translated.replace(u"£©", u"ஜீ")
    translated = translated.replace(u"£¨", u"ஜி")
    translated = translated.replace(u"£è", u"ஜா")
    translated = translated.replace(u"£", u"ஜ")
    
    translated = translated.replace(u"¢Ð", u"ஞ்")
    translated = translated.replace(u"â¢ó", u"ஞௌ")
    translated = translated.replace(u"î¢è", u"ஞோ")
    translated = translated.replace(u"â¢è", u"ஞொ")
    translated = translated.replace(u"é¢", u"ஞை")
    translated = translated.replace(u"î¢", u"ஞே")
    translated = translated.replace(u"â¢", u"ஞெ")
    translated = translated.replace(u"»", u"ஞூ")
    translated = translated.replace(u"ü", u"ஞு")
    translated = translated.replace(u"¢©", u"ஞீ")
    translated = translated.replace(u"¢¨", u"ஞி")
    translated = translated.replace(u"¢è", u"ஞா")
    translated = translated.replace(u"¢", u"ஞ")
    
    translated = translated.replace(u"ìÐ", u"ட்")
    translated = translated.replace(u"âìó", u"டௌ")
    translated = translated.replace(u"îìè", u"டோ")
    translated = translated.replace(u"âìè", u"டொ")
    translated = translated.replace(u"éì", u"டை")
    translated = translated.replace(u"îì", u"டே")
    translated = translated.replace(u"âì", u"டெ")
    translated = translated.replace(u"Þ", u"டூ")
    translated = translated.replace(u"Ì", u"டு")
    translated = translated.replace(u"Ï", u"டீ")
    translated = translated.replace(u"ï", u"டி")
    translated = translated.replace(u"ìè", u"டா")
    translated = translated.replace(u"ì", u"ட")
    
    translated = translated.replace(u"úª", u"ண்")
    translated = translated.replace(u"âúó", u"ணௌ")
    translated = translated.replace(u"îúè", u"ணோ")
    translated = translated.replace(u"âúè", u"ணொ")
    translated = translated.replace(u"éú", u"ணை")
    translated = translated.replace(u"îú", u"ணே")
    translated = translated.replace(u"âú", u"ணெ")
    translated = translated.replace(u"½", u"ணூ")
    translated = translated.replace(u"Ñ", u"ணு")
    translated = translated.replace(u"ú©", u"ணீ")
    translated = translated.replace(u"ú¨", u"ணி")
    translated = translated.replace(u"úè", u"ணா")
    translated = translated.replace(u"ú", u"ண")
    
    translated = translated.replace(u"êÐ", u"த்")
    translated = translated.replace(u"âêó", u"தௌ")
    translated = translated.replace(u"îêè", u"தோ")
    translated = translated.replace(u"âêè", u"தொ")
    translated = translated.replace(u"éê", u"தை")
    translated = translated.replace(u"îê", u"தே")
    translated = translated.replace(u"âê", u"தெ")
    translated = translated.replace(u"œ", u"தூ")
    translated = translated.replace(u"Ê", u"து")
    translated = translated.replace(u"ê©", u"தீ")
    translated = translated.replace(u"ê¨", u"தி")
    translated = translated.replace(u"êè", u"தா")
    translated = translated.replace(u"ê", u"த")
    
    translated = translated.replace(u"åÐ", u"ந்")
    translated = translated.replace(u"âåó", u"நௌ")
    translated = translated.replace(u"îåè", u"நோ")
    translated = translated.replace(u"âåè", u"நொ")
    translated = translated.replace(u"éå", u"நை")
    translated = translated.replace(u"îå", u"நே")
    translated = translated.replace(u"âå", u"நெ")
    translated = translated.replace(u"¿", u"நூ")
    translated = translated.replace(u"Å", u"நு")
    translated = translated.replace(u"å©", u"நீ")
    translated = translated.replace(u"å¨", u"நி")
    translated = translated.replace(u"åè", u"நா")
    translated = translated.replace(u"å", u"ந")
    
    translated = translated.replace(u"äª", u"ன்")
    translated = translated.replace(u"âäó", u"னௌ")
    translated = translated.replace(u"îäè", u"னோ")
    translated = translated.replace(u"âäè", u"னொ")
    translated = translated.replace(u"éä", u"னை")
    translated = translated.replace(u"îä", u"னே")
    translated = translated.replace(u"âä", u"னெ")
    translated = translated.replace(u"Û", u"னூ")
    translated = translated.replace(u"Ä", u"னு")
    translated = translated.replace(u"ä©", u"னீ")
    translated = translated.replace(u"ä¨", u"னி")
    translated = translated.replace(u"äè", u"னா")
    translated = translated.replace(u"ä", u"ன")
    
    translated = translated.replace(u"çÐ", u"ப்")
    translated = translated.replace(u"âçó", u"பௌ")
    translated = translated.replace(u"îçè", u"போ")
    translated = translated.replace(u"âçè", u"பொ")
    translated = translated.replace(u"éç", u"பை")
    translated = translated.replace(u"îç", u"பே")
    translated = translated.replace(u"âç", u"பெ")
    translated = translated.replace(u"—", u"பூ")
    translated = translated.replace(u"µ", u"பு")
    translated = translated.replace(u"ç©", u"பீ")
    translated = translated.replace(u"ç¨", u"பி")
    translated = translated.replace(u"çè", u"பா")
    translated = translated.replace(u"ç", u"ப")
    
    translated = translated.replace(u"ëÐ", u"ம்")
    translated = translated.replace(u"âëó", u"மௌ")
    translated = translated.replace(u"îëè", u"மோ")
    translated = translated.replace(u"âëè", u"மொ")
    translated = translated.replace(u"éë", u"மை")
    translated = translated.replace(u"îë", u"மே")
    translated = translated.replace(u"âë", u"மெ")
    translated = translated.replace(u"ß", u"மூ")
    translated = translated.replace(u"Ë", u"மு")
    translated = translated.replace(u"ë©", u"மீ")
    translated = translated.replace(u"ë¨", u"மி")
    translated = translated.replace(u"ëè", u"மா")
    translated = translated.replace(u"ë", u"ம")
    
    translated = translated.replace(u"áÐ", u"ய்")
    translated = translated.replace(u"âáó", u"யௌ")
    translated = translated.replace(u"îáè", u"யோ")
    translated = translated.replace(u"âáè", u"யொ")
    translated = translated.replace(u"éá", u"யை")
    translated = translated.replace(u"îá", u"யே")
    translated = translated.replace(u"âá", u"யெ")
    translated = translated.replace(u"¹", u"யூ")
    translated = translated.replace(u"±", u"யு")
    translated = translated.replace(u"á©", u"யீ")
    translated = translated.replace(u"á¨", u"யி")
    translated = translated.replace(u"áè", u"யா")
    translated = translated.replace(u"á", u"ய")
    
    translated = translated.replace(u"õÐ", u"ர்")
    translated = translated.replace(u"èÐ", u"ர்")  # Added
    translated = translated.replace(u"âõó", u"ரௌ")
    translated = translated.replace(u"îõè", u"ரோ")
    translated = translated.replace(u"âõè", u"ரொ")
    translated = translated.replace(u"éõ", u"ரை")
    translated = translated.replace(u"îõ", u"ரே")
    translated = translated.replace(u"âõ", u"ரெ")
    translated = translated.replace(u"¥", u"ரூ")
    translated = translated.replace(u"Õ", u"ரு")
    translated = translated.replace(u"õ©", u"ரீ")
    translated = translated.replace(u"è©", u"ரீ")  # Added
    translated = translated.replace(u"õ¨", u"ரி")
    translated = translated.replace(u"è¨", u"ரி")  # Added
    translated = translated.replace(u"õè", u"ரா")
    translated = translated.replace(u"õ", u"ர")
    
    translated = translated.replace(u"÷Ð", u"ற்")
    translated = translated.replace(u"â÷ó", u"றௌ")
    translated = translated.replace(u"î÷è", u"றோ")
    translated = translated.replace(u"â÷è", u"றொ")
    translated = translated.replace(u"é÷", u"றை")
    translated = translated.replace(u"î÷", u"றே")
    translated = translated.replace(u"âõ", u"ரெ")
    translated = translated.replace(u"®", u"றூ")
    translated = translated.replace(u"×", u"று")
    translated = translated.replace(u"÷©", u"றீ")
    translated = translated.replace(u"÷¨", u"றி")
    translated = translated.replace(u"÷è", u"றா")
    translated = translated.replace(u"÷", u"ற")
    
    translated = translated.replace(u"ùÐ", u"ல்")
    translated = translated.replace(u"âùó", u"லௌ")
    translated = translated.replace(u"îùè", u"லோ")
    translated = translated.replace(u"âùè", u"லொ")
    translated = translated.replace(u"éù", u"லை")
    translated = translated.replace(u"îù", u"லே")
    translated = translated.replace(u"âù", u"லெ")
    translated = translated.replace(u"û", u"லூ")
    translated = translated.replace(u"Ù", u"லு")
    translated = translated.replace(u"ù©", u"லீ")
    translated = translated.replace(u"ù¨", u"லி")
    translated = translated.replace(u"ùè", u"லா")
    translated = translated.replace(u"ù", u"ல")
    
    translated = translated.replace(u"óª", u"ள்")
    translated = translated.replace(u"âóó", u"ளௌ")
    translated = translated.replace(u"îóè", u"ளோ")
    translated = translated.replace(u"âóè", u"ளொ")
    translated = translated.replace(u"éó", u"ளை")
    translated = translated.replace(u"îó", u"ளே")
    translated = translated.replace(u"âó", u"ளெ")
    translated = translated.replace(u"ñ", u"ளூ")
    translated = translated.replace(u"Ó", u"ளு")
    translated = translated.replace(u"ó©", u"ளீ")
    translated = translated.replace(u"ó¨", u"ளி")
    translated = translated.replace(u"óè", u"ளா")
    translated = translated.replace(u"ó", u"ள")
    
    translated = translated.replace(u"ÈÐ", u"ழ்")
    translated = translated.replace(u"âÈó", u"ழௌ")
    translated = translated.replace(u"îÈè", u"ழோ")
    translated = translated.replace(u"âÈè", u"ழொ")
    translated = translated.replace(u"éÈ", u"ழை")
    translated = translated.replace(u"îÈ", u"ழே")
    translated = translated.replace(u"âÈ", u"ழெ")
    translated = translated.replace(u"¾", u"ழூ")
    translated = translated.replace(u"Ç", u"ழு")
    translated = translated.replace(u"È©", u"ழீ")
    translated = translated.replace(u"È¨", u"ழி")
    translated = translated.replace(u"Èè", u"ழா")
    translated = translated.replace(u"È", u"ழ")
    
    translated = translated.replace(u"ôÐ", u"வ்")
    translated = translated.replace(u"âôó", u"வௌ")
    translated = translated.replace(u"îôè", u"வோ")
    translated = translated.replace(u"âôè", u"வொ")
    translated = translated.replace(u"éô", u"வை")
    translated = translated.replace(u"îô", u"வே")
    translated = translated.replace(u"âô", u"வெ")
    translated = translated.replace(u"´", u"வூ")
    translated = translated.replace(u"²", u"வு")
    translated = translated.replace(u"ô©", u"வீ")
    translated = translated.replace(u"ô¨", u"வி")
    translated = translated.replace(u"ôè", u"வா")
    translated = translated.replace(u"ô", u"வ")
    
    translated = translated.replace(u"ÜÐ", u"ஷ்")
    translated = translated.replace(u"âÜó", u"ஷௌ")
    translated = translated.replace(u"îÜè", u"ஷோ")
    translated = translated.replace(u"âÜè", u"ஷொ")
    translated = translated.replace(u"éÜ", u"ஷை")
    translated = translated.replace(u"îÜ", u"ஷே")
    translated = translated.replace(u"âÜ", u"ஷெ")
    translated = translated.replace(u"Üð", u"ஷூ")
    translated = translated.replace(u"Ü¦", u"ஷு")
    translated = translated.replace(u"Ü©", u"ஷீ")
    translated = translated.replace(u"Ü¨", u"ஷி")
    translated = translated.replace(u"Üè", u"ஷா")
    translated = translated.replace(u"Ü", u"ஷ")
    
    translated = translated.replace(u"ÁÐ", u"ஹ்")
    translated = translated.replace(u"âÁó", u"ஹௌ")
    translated = translated.replace(u"îÁè", u"ஹோ")
    translated = translated.replace(u"âÁè", u"ஹொ")
    translated = translated.replace(u"éÁ", u"ஹை")
    translated = translated.replace(u"îÁ", u"ஹே")
    translated = translated.replace(u"âÁ", u"ஹெ")
    translated = translated.replace(u"Á©", u"ஹீ")
    translated = translated.replace(u"Á¨", u"ஹி")
    translated = translated.replace(u"Áè", u"ஹா")
    translated = translated.replace(u"Á", u"ஹ")
    
    unconverted = [i for i in translated if i in source_text and not i in
                    punctuation+whitespace+digits]
    translated_trimed = ''.join([i for i in translated if not i in unconverted])

    if debug:
        return ''.join(unconverted)
    elif filtered:
        return translated_trimed
    else:
        return translated