# -*- coding: utf-8 -*-
from string import punctuation, whitespace, digits


def convertTounicode(source_text, filtered=False, debug=False):
    translated = source_text
    # Independent Vowels
    translated = translated.replace(u"m", u"அ")
    translated = translated.replace(u"M", u"ஆ")
    translated = translated.replace(u"Ï", u"இ")
    translated = translated.replace(u"<", u"ஈ")
    translated = translated.replace(u"c", u"உ")
    translated = translated.replace(u"C", u"ஊ")
    translated = translated.replace(u"v", u"எ")
    translated = translated.replace(u"V", u"ஏ")
    translated = translated.replace(u"I", u"ஐ")
    translated = translated.replace(u"x", u"ஒ")
    translated = translated.replace(u"X", u"ஓ")
    translated = translated.replace(u"xs", u"ஔ")
    translated = translated.replace(u"~", u"ஃ")

    # க Family
    translated = translated.replace(u"¡", u"க்")
    translated = translated.replace(u"bfs", u"கௌ")
    translated = translated.replace(u"nfh", u"கோ")
    translated = translated.replace(u"bfh", u"கொ")
    translated = translated.replace(u"if", u"கை")
    translated = translated.replace(u"nf", u"கே")
    translated = translated.replace(u"bf", u"கெ")
    translated = translated.replace(u"T", u"கூ")
    translated = translated.replace(u"F", u"கு")
    translated = translated.replace(u"Ñ", u"கீ")
    translated = translated.replace(u"»", u"கி")
    translated = translated.replace(u"fh", u"கா")
    translated = translated.replace(u"f", u"க")

    # ங Family
    translated = translated.replace(u"§", u"ங்")
    translated = translated.replace(u"b‡s", u"ஙௌ")
    translated = translated.replace(u"n‡h", u"ஙோ")
    translated = translated.replace(u"b‡h", u"ஙொ")
    translated = translated.replace(u"i‡", u"ஙை")
    translated = translated.replace(u"n‡", u"ஙே")
    translated = translated.replace(u"b‡", u"ஙெ")
    translated = translated.replace(u"½", u"ஙூ")
    translated = translated.replace(u"¼", u"ஙு")
    translated = translated.replace(u"†", u"ஙீ")
    translated = translated.replace(u"à", u"ஙி")
    translated = translated.replace(u"‡h", u"ஙா")
    translated = translated.replace(u"‡", u"ங")

    # ச Family
    translated = translated.replace(u"¢", u"ச்")
    translated = translated.replace(u"brs", u"சௌ")
    translated = translated.replace(u"nrh", u"சோ")
    translated = translated.replace(u"brh", u"சொ")
    translated = translated.replace(u"ir", u"சை")
    translated = translated.replace(u"nr", u"சே")
    translated = translated.replace(u"br", u"செ")
    translated = translated.replace(u"N", u"சூ")
    translated = translated.replace(u"R", u"சு")
    translated = translated.replace(u"Ó", u"சீ")
    translated = translated.replace(u"Á", u"சி")
    translated = translated.replace(u"rh", u"சா")
    translated = translated.replace(u"r", u"ச")

    # ஜ Family
    translated = translated.replace(u"{", u"ஜ்")
    translated = translated.replace(u"b#s", u"ஜௌ")
    translated = translated.replace(u"n#h", u"ஜோ")
    translated = translated.replace(u"b#h", u"ஜொ")
    translated = translated.replace(u"i#", u"ஜை")
    translated = translated.replace(u"n#", u"ஜே")
    translated = translated.replace(u"b#", u"ஜெ")
    translated = translated.replace(u"#]", u"ஜூ")
    translated = translated.replace(u"#&", u"ஜு")
    translated = translated.replace(u"É", u"ஜீ")
    translated = translated.replace(u"í", u"ஜி")
    translated = translated.replace(u"#h", u"ஜா")
    translated = translated.replace(u"#", u"ஜ")

    # ஞ Family
    translated = translated.replace(u"Š", u"ஞ்")
    translated = translated.replace(u"bPs", u"ஞௌ")
    translated = translated.replace(u"nPh", u"ஞோ")
    translated = translated.replace(u"bPh", u"ஞொ")
    translated = translated.replace(u"iP", u"ஞை")
    translated = translated.replace(u"nP", u"ஞே")
    translated = translated.replace(u"bP", u"ஞெ")
    translated = translated.replace(u"ú", u"ஞூ")
    translated = translated.replace(u"\|", u"ஞு")
    translated = translated.replace(u"Ø", u"ஞீ")
    translated = translated.replace(u"á", u"ஞி")
    translated = translated.replace(u"Ph", u"ஞா")
    translated = translated.replace(u"P", u"ஞ")

    # ட Family
    translated = translated.replace(u"£", u"ட்")
    translated = translated.replace(u"bls", u"டௌ")
    translated = translated.replace(u"nlh", u"டோ")
    translated = translated.replace(u"blh", u"டொ")
    translated = translated.replace(u"il", u"டை")
    translated = translated.replace(u"nl", u"டே")
    translated = translated.replace(u"bl", u"டெ")
    translated = translated.replace(u"\^", u"டூ")
    translated = translated.replace(u"L", u"டு")
    translated = translated.replace(u"O", u"டீ")
    translated = translated.replace(u"o", u"டி")
    translated = translated.replace(u"lh", u"டா")
    translated = translated.replace(u"l", u"ட")

    # ண Family
    translated = translated.replace(u"©", u"ண்")
    translated = translated.replace(u"bzs", u"ணௌ")
    translated = translated.replace(u"nzh", u"ணோ")
    translated = translated.replace(u"bzh", u"ணொ")
    translated = translated.replace(u"iz", u"ணை")
    translated = translated.replace(u"nz", u"ணே")
    translated = translated.replace(u"bz", u"ணெ")
    translated = translated.replace(u"û", u"ணூ")
    translated = translated.replace(u"Q", u"ணு")
    translated = translated.replace(u"Ù", u"ணீ")
    translated = translated.replace(u"â", u"ணி")
    translated = translated.replace(u"zh", u"ணா")
    translated = translated.replace(u"z", u"ண")

    # த Family
    translated = translated.replace(u"¤", u"த்")
    translated = translated.replace(u"bjs", u"தௌ")
    translated = translated.replace(u"njh", u"தோ")
    translated = translated.replace(u"bjh", u"தொ")
    translated = translated.replace(u"ij", u"தை")
    translated = translated.replace(u"nj", u"தே")
    translated = translated.replace(u"bj", u"தெ")
    translated = translated.replace(u"ö", u"தூ")
    translated = translated.replace(u"J", u"து")
    translated = translated.replace(u"Ô", u"தீ")
    translated = translated.replace(u"Â", u"தி")
    translated = translated.replace(u"jh", u"தா")
    translated = translated.replace(u"j", u"த")

    # ந Family
    translated = translated.replace(u"ª", u"ந்")
    translated = translated.replace(u"bes", u"நௌ")
    translated = translated.replace(u"neh", u"நோ")
    translated = translated.replace(u"beh", u"நொ")
    translated = translated.replace(u"ie", u"நை")
    translated = translated.replace(u"ne", u"நே")
    translated = translated.replace(u"be", u"நெ")
    translated = translated.replace(u"ü", u"நூ")
    translated = translated.replace(u"E", u"நு")
    translated = translated.replace(u"Ú", u"நீ")
    translated = translated.replace(u"ã", u"நி")
    translated = translated.replace(u"eh", u"நா")
    translated = translated.replace(u"e", u"ந")

    # ன Family
    translated = translated.replace(u"‹", u"ன்")
    translated = translated.replace(u"bds", u"னௌ")
    translated = translated.replace(u"ndh", u"னோ")
    translated = translated.replace(u"bdh", u"னொ")
    translated = translated.replace(u"id", u"னை")
    translated = translated.replace(u"nd", u"னே")
    translated = translated.replace(u"bd", u"னெ")
    translated = translated.replace(u"}", u"னூ")
    translated = translated.replace(u"D", u"னு")
    translated = translated.replace(u"Ü", u"னீ")
    translated = translated.replace(u"å", u"னி")
    translated = translated.replace(u"dh", u"னா")
    translated = translated.replace(u"d", u"ன")

    # ப Family
    translated = translated.replace(u"¥", u"ப்")
    translated = translated.replace(u"bgs", u"பௌ")
    translated = translated.replace(u"ngh", u"போ")
    translated = translated.replace(u"bgh", u"பொ")
    translated = translated.replace(u"ig", u"பை")
    translated = translated.replace(u"ng", u"பே")
    translated = translated.replace(u"bg", u"பெ")
    translated = translated.replace(u"ó", u"பூ")
    translated = translated.replace(u"ò", u"பு")
    translated = translated.replace(u"Õ", u"பீ")
    translated = translated.replace(u"Ã", u"பி")
    translated = translated.replace(u"gh", u"பா")
    translated = translated.replace(u"g", u"ப")

    # ம Family
    translated = translated.replace(u"«", u"ம்")
    translated = translated.replace(u"bks", u"மௌ")
    translated = translated.replace(u"nkh", u"மோ")
    translated = translated.replace(u"bkh", u"மொ")
    translated = translated.replace(u"ik", u"மை")
    translated = translated.replace(u"nk", u"மே")
    translated = translated.replace(u"bk", u"மெ")
    translated = translated.replace(u"_", u"மூ")
    translated = translated.replace(u"K", u"மு")
    translated = translated.replace(u"Û", u"மீ")
    translated = translated.replace(u"ä", u"மி")
    translated = translated.replace(u"kh", u"மா")
    translated = translated.replace(u"k", u"ம")

    # ய Family
    translated = translated.replace(u"Œ", u"ய்")
    translated = translated.replace(u"bas", u"யௌ")
    translated = translated.replace(u"nah", u"யோ")
    translated = translated.replace(u"bah", u"யொ")
    translated = translated.replace(u"ia", u"யை")
    translated = translated.replace(u"na", u"யே")
    translated = translated.replace(u"ba", u"யெ")
    translated = translated.replace(u"ô", u"யூ")
    translated = translated.replace(u"Í", u"யு")
    translated = translated.replace(u"p", u"யீ")
    translated = translated.replace(u"æ", u"யி")
    translated = translated.replace(u"ah", u"யா")
    translated = translated.replace(u"a", u"ய")

    # ர Family
    translated = translated.replace(u"®", u"ர்")
    translated = translated.replace(u"bus", u"ரௌ")
    translated = translated.replace(u"nuh", u"ரோ")
    translated = translated.replace(u"buh", u"ரொ")
    translated = translated.replace(u"iu", u"ரை")
    translated = translated.replace(u"nu", u"ரே")
    translated = translated.replace(u"bu", u"ரெ")
    translated = translated.replace(u"%", u"ரூ")
    translated = translated.replace(u"U", u"ரு")
    translated = translated.replace(u"ß", u"ரீ")
    translated = translated.replace(u"ç", u"ரி")
    translated = translated.replace(u"uh", u"ரா")
    translated = translated.replace(u"u", u"ர")

    # ற Family
    translated = translated.replace(u"‰", u"ற்")
    translated = translated.replace(u"bws", u"றௌ")
    translated = translated.replace(u"nwh", u"றோ")
    translated = translated.replace(u"bwh", u"றொ")
    translated = translated.replace(u"iw", u"றை")
    translated = translated.replace(u"nw", u"றே")
    translated = translated.replace(u"bu", u"ரெ")
    translated = translated.replace(u"ù", u"றூ")
    translated = translated.replace(u"W", u"று")
    translated = translated.replace(u"Ö", u"றீ")
    translated = translated.replace(u"¿", u"றி")
    translated = translated.replace(u"wh", u"றா")
    translated = translated.replace(u"w", u"ற")

    # ல Family
    translated = translated.replace(u"š", u"ல்")
    translated = translated.replace(u"bys", u"லௌ")
    translated = translated.replace(u"nyh", u"லோ")
    translated = translated.replace(u"byh", u"லொ")
    translated = translated.replace(u"iy", u"லை")
    translated = translated.replace(u"ny", u"லே")
    translated = translated.replace(u"by", u"லெ")
    translated = translated.replace(u"ÿ", u"லூ")
    translated = translated.replace(u"Y", u"லு")
    translated = translated.replace(u"Ä", u"லீ")
    translated = translated.replace(u"è", u"லி")
    translated = translated.replace(u"yh", u"லா")
    translated = translated.replace(u"y", u"ல")

    # ள Family
    translated = translated.replace(u"Ÿ", u"ள்")
    translated = translated.replace(u"bss", u"ளௌ")
    translated = translated.replace(u"nsh", u"ளோ")
    translated = translated.replace(u"is", u"ளை")
    translated = translated.replace(u"ns", u"ளே")
    translated = translated.replace(u"bs", u"ளெ")
    translated = translated.replace(u"q", u"ளூ")
    translated = translated.replace(u"S", u"ளு")
    translated = translated.replace(u"Ç", u"ளீ")
    translated = translated.replace(u"ë", u"ளி")
    translated = translated.replace(u"sh", u"ளா")
    translated = translated.replace(u"s", u"ள")

    # ழ Family
    translated = translated.replace(u"œ", u"ழ்")
    translated = translated.replace(u"bHs", u"ழௌ")
    translated = translated.replace(u"nHh", u"ழோ")
    translated = translated.replace(u"bHh", u"ழொ")
    translated = translated.replace(u"iH", u"ழை")
    translated = translated.replace(u"nH", u"ழே")
    translated = translated.replace(u"bH", u"ழெ")
    translated = translated.replace(u">", u"ழூ")
    translated = translated.replace(u"G", u"ழு")
    translated = translated.replace(u"Æ", u"ழீ")
    translated = translated.replace(u"ê", u"ழி")
    translated = translated.replace(u"Hh", u"ழா")
    translated = translated.replace(u"H", u"ழ")

    # வ Family
    translated = translated.replace(u"›", u"வ்")
    translated = translated.replace(u"bts", u"வௌ")
    translated = translated.replace(u"nth", u"வோ")
    translated = translated.replace(u"bth", u"வொ")
    translated = translated.replace(u"it", u"வை")
    translated = translated.replace(u"nt", u"வே")
    translated = translated.replace(u"bt", u"வெ")
    translated = translated.replace(u"ñ", u"வூ")
    translated = translated.replace(u"Î", u"வு")
    translated = translated.replace(u"Å", u"வீ")
    translated = translated.replace(u"é", u"வி")
    translated = translated.replace(u"th", u"வா")
    translated = translated.replace(u"t", u"வ")

    # ஷ Family
    translated = translated.replace(u"Z", u"ஷ்")
    translated = translated.replace(u"bõs", u"ஷௌ")
    translated = translated.replace(u"nõh", u"ஷோ")
    translated = translated.replace(u"bõh", u"ஷொ")
    translated = translated.replace(u"iõ", u"ஷை")
    translated = translated.replace(u"nõ", u"ஷே")
    translated = translated.replace(u"bõ", u"ஷெ")
    translated = translated.replace(u"Ê", u"ஷீ")
    translated = translated.replace(u"î", u"ஷி")
    translated = translated.replace(u"õh", u"ஷா")
    translated = translated.replace(u"õ", u"ஷ")

    # ஸ Family
    translated = translated.replace(u"°", u"ஸ்")
    translated = translated.replace(u"b\[s", u"ஸௌ")
    translated = translated.replace(u"n\[h", u"ஸோ")
    translated = translated.replace(u"b\[h", u"ஸொ")
    translated = translated.replace(u"i\[", u"ஸை")
    translated = translated.replace(u"n\[", u"ஸே")
    translated = translated.replace(u"b\[", u"ஸெ")
    translated = translated.replace(u"È", u"ஸீ")
    translated = translated.replace(u"ì", u"ஸி")
    translated = translated.replace(u"\[h", u"ஸா")
    translated = translated.replace(u"\[", u"ஸ")

    # ஹ Family
    translated = translated.replace(u"À", u"ஹ்")
    translated = translated.replace(u"bAs", u"ஹௌ")
    translated = translated.replace(u"nAh", u"ஹோ")
    translated = translated.replace(u"bAh", u"ஹொ")
    translated = translated.replace(u"iA", u"ஹை")
    translated = translated.replace(u"nA", u"ஹே")
    translated = translated.replace(u"bA", u"ஹெ")
    translated = translated.replace(u"Ë", u"ஹீ")
    translated = translated.replace(u"ï", u"ஹி")
    translated = translated.replace(u"Ah", u"ஹா")
    translated = translated.replace(u"A", u"ஹ")

    unconverted = [i for i in translated if i in source_text and not i in
                    punctuation+whitespace+digits]
    translated_trimed = ''.join([i for i in translated if not i in unconverted])

    if debug:
        return unconverted
    elif filtered:
        return translated_trimed
    else:
        return translated