# -*- coding: utf-8 -*-
from string import punctuation, whitespace, digits


def convertTounicode(source_text, filtered=False, debug=False):
    translated = source_text
    # ச Family
    translated = translated.replace(u"chau", u"சௌ")
    translated = translated.replace(u"choo", u"சோ")
    translated = translated.replace(u"cho", u"சொ")
    translated = translated.replace(u"chai", u"சை")
    translated = translated.replace(u"chee", u"சே")
    translated = translated.replace(u"che", u"செ")
    translated = translated.replace(u"chuu", u"சூ")
    translated = translated.replace(u"chu", u"சு")
    translated = translated.replace(u"chii", u"சீ")
    translated = translated.replace(u"chi", u"சி")
    translated = translated.replace(u"chaa", u"சா")
    translated = translated.replace(u"cha", u"ச")
    translated = translated.replace(u"ch", u"ச்")

    # க Family
    translated = translated.replace(u"kau", u"கௌ")
    translated = translated.replace(u"koo", u"கோ")
    translated = translated.replace(u"ko", u"கொ")
    translated = translated.replace(u"kai", u"கை")
    translated = translated.replace(u"kee", u"கே")
    translated = translated.replace(u"ke", u"கெ")
    translated = translated.replace(u"kuu", u"கூ")
    translated = translated.replace(u"ku", u"கு")
    translated = translated.replace(u"kii", u"கீ")
    translated = translated.replace(u"ki", u"கி")
    translated = translated.replace(u"kaa", u"கா")
    translated = translated.replace(u"ka", u"க")
    translated = translated.replace(u"k", u"க்")

    # க Family
    translated = translated.replace(u"khau", u"கௌ")
    translated = translated.replace(u"khoo", u"கோ")
    translated = translated.replace(u"kho", u"கொ")
    translated = translated.replace(u"khai", u"கை")
    translated = translated.replace(u"khee", u"கே")
    translated = translated.replace(u"khe", u"கெ")
    translated = translated.replace(u"khuu", u"கூ")
    translated = translated.replace(u"khu", u"கு")
    translated = translated.replace(u"khii", u"கீ")
    translated = translated.replace(u"khi", u"கி")
    translated = translated.replace(u"khaa", u"கா")
    translated = translated.replace(u"kha", u"க")
    translated = translated.replace(u"kh", u"க்")

    # க Family
    translated = translated.replace(u"gau", u"கௌ")
    translated = translated.replace(u"goo", u"கோ")
    translated = translated.replace(u"go", u"கொ")
    translated = translated.replace(u"gai", u"கை")
    translated = translated.replace(u"gee", u"கே")
    translated = translated.replace(u"ge", u"கெ")
    translated = translated.replace(u"guu", u"கூ")
    translated = translated.replace(u"gu", u"கு")
    translated = translated.replace(u"gii", u"கீ")
    translated = translated.replace(u"gi", u"கி")
    translated = translated.replace(u"gaa", u"கா")
    translated = translated.replace(u"ga", u"க")
    translated = translated.replace(u"g", u"க்")

    # க Family
    translated = translated.replace(u"cau", u"கௌ")
    translated = translated.replace(u"coo", u"கோ")
    translated = translated.replace(u"co", u"கொ")
    translated = translated.replace(u"cai", u"கை")
    translated = translated.replace(u"cee", u"கே")
    translated = translated.replace(u"ce", u"கெ")
    translated = translated.replace(u"cuu", u"கூ")
    translated = translated.replace(u"cu", u"கு")
    translated = translated.replace(u"cii", u"கீ")
    translated = translated.replace(u"ci", u"கி")
    translated = translated.replace(u"caa", u"கா")
    translated = translated.replace(u"ca", u"க")
    translated = translated.replace(u"c", u"க்")

    # ங Family
    translated = translated.replace(u"ngau", u"ஙௌ")
    translated = translated.replace(u"ngoo", u"ஙோ")
    translated = translated.replace(u"ngo", u"ஙொ")
    translated = translated.replace(u"ngai", u"ஙை")
    translated = translated.replace(u"ngee", u"ஙே")
    translated = translated.replace(u"nge", u"ஙெ")
    translated = translated.replace(u"nguu", u"ஙூ")
    translated = translated.replace(u"ngu", u"ஙு")
    translated = translated.replace(u"ngii", u"ஙீ")
    translated = translated.replace(u"ngi", u"ஙி")
    translated = translated.replace(u"ngaa", u"ஙா")
    translated = translated.replace(u"nga", u"ங")
    translated = translated.replace(u"ng", u"ங்")

    # ங Family
    translated = translated.replace(u"nGau", u"ஙௌ")
    translated = translated.replace(u"nGoo", u"ஙோ")
    translated = translated.replace(u"nGo", u"ஙொ")
    translated = translated.replace(u"nGai", u"ஙை")
    translated = translated.replace(u"nGee", u"ஙே")
    translated = translated.replace(u"nGe", u"ஙெ")
    translated = translated.replace(u"nGuu", u"ஙூ")
    translated = translated.replace(u"nGu", u"ஙு")
    translated = translated.replace(u"nGii", u"ஙீ")
    translated = translated.replace(u"nGi", u"ஙி")
    translated = translated.replace(u"nGaa", u"ஙா")
    translated = translated.replace(u"nGa", u"ங")
    translated = translated.replace(u"nG", u"ங்")

    # ஜ Family
    translated = translated.replace(u"jau", u"ஜௌ")
    translated = translated.replace(u"joo", u"ஜோ")
    translated = translated.replace(u"jo", u"ஜொ")
    translated = translated.replace(u"jai", u"ஜை")
    translated = translated.replace(u"jee", u"ஜே")
    translated = translated.replace(u"je", u"ஜெ")
    translated = translated.replace(u"juu", u"ஜூ")
    translated = translated.replace(u"ju", u"ஜு")
    translated = translated.replace(u"jii", u"ஜீ")
    translated = translated.replace(u"ji", u"ஜி")
    translated = translated.replace(u"jaa", u"ஜா")
    translated = translated.replace(u"ja", u"ஜ")
    translated = translated.replace(u"j", u"ஜ்")

    # ஞ Family
    translated = translated.replace(u"njau", u"ஞௌ")
    translated = translated.replace(u"njoo", u"ஞோ")
    translated = translated.replace(u"njo", u"ஞொ")
    translated = translated.replace(u"njai", u"ஞை")
    translated = translated.replace(u"njee", u"ஞே")
    translated = translated.replace(u"nje", u"ஞெ")
    translated = translated.replace(u"njuu", u"ஞூ")
    translated = translated.replace(u"nju", u"ஞு")
    translated = translated.replace(u"njii", u"ஞீ")
    translated = translated.replace(u"nji", u"ஞி")
    translated = translated.replace(u"njaa", u"ஞா")
    translated = translated.replace(u"nja", u"ஞ")
    translated = translated.replace(u"nj", u"ஞ்")

    # ஞ Family
    translated = translated.replace(u"nYau", u"ஞௌ")
    translated = translated.replace(u"nYoo", u"ஞோ")
    translated = translated.replace(u"nYo", u"ஞொ")
    translated = translated.replace(u"nYai", u"ஞை")
    translated = translated.replace(u"nYee", u"ஞே")
    translated = translated.replace(u"nYe", u"ஞெ")
    translated = translated.replace(u"nYuu", u"ஞூ")
    translated = translated.replace(u"nYu", u"ஞு")
    translated = translated.replace(u"nYii", u"ஞீ")
    translated = translated.replace(u"nYi", u"ஞி")
    translated = translated.replace(u"nYaa", u"ஞா")
    translated = translated.replace(u"nYa", u"ஞ")
    translated = translated.replace(u"nY", u"ஞ்")

    # த Family
    translated = translated.replace(u"dhau", u"தௌ")
    translated = translated.replace(u"dhoo", u"தோ")
    translated = translated.replace(u"dho", u"தொ")
    translated = translated.replace(u"dhai", u"தை")
    translated = translated.replace(u"dhee", u"தே")
    translated = translated.replace(u"dhe", u"தெ")
    translated = translated.replace(u"dhuu", u"தூ")
    translated = translated.replace(u"dhu", u"து")
    translated = translated.replace(u"dhii", u"தீ")
    translated = translated.replace(u"dhi", u"தி")
    translated = translated.replace(u"dhaa", u"தா")
    translated = translated.replace(u"dha", u"த")
    translated = translated.replace(u"dh", u"த்")

    # த Family
    translated = translated.replace(u"thau", u"தௌ")
    translated = translated.replace(u"thoo", u"தோ")
    translated = translated.replace(u"tho", u"தொ")
    translated = translated.replace(u"thai", u"தை")
    translated = translated.replace(u"thee", u"தே")
    translated = translated.replace(u"the", u"தெ")
    translated = translated.replace(u"thuu", u"தூ")
    translated = translated.replace(u"thu", u"து")
    translated = translated.replace(u"thii", u"தீ")
    translated = translated.replace(u"thi", u"தி")
    translated = translated.replace(u"thaa", u"தா")
    translated = translated.replace(u"tha", u"த")
    translated = translated.replace(u"th", u"த்")

    # க Family
    # translated = translated.replace(u"hau", u"கௌ")
    # translated = translated.replace(u"hoo", u"கோ")
    # translated = translated.replace(u"ho", u"கொ")
    # translated = translated.replace(u"hai", u"கை")
    # translated = translated.replace(u"hee", u"கே")
    # translated = translated.replace(u"he", u"கெ")
    # translated = translated.replace(u"huu", u"கூ")
    # translated = translated.replace(u"hu", u"கு")
    # translated = translated.replace(u"hii", u"கீ")
    # translated = translated.replace(u"hi", u"கி")
    # translated = translated.replace(u"haa", u"கா")
    # translated = translated.replace(u"ha", u"க")
    # translated = translated.replace(u"h", u"க்")

    # ட Family
    translated = translated.replace(u"tau", u"டௌ")
    translated = translated.replace(u"too", u"டோ")
    translated = translated.replace(u"to", u"டொ")
    translated = translated.replace(u"tai", u"டை")
    translated = translated.replace(u"tee", u"டே")
    translated = translated.replace(u"te", u"டெ")
    translated = translated.replace(u"tuu", u"டூ")
    translated = translated.replace(u"tu", u"டு")
    translated = translated.replace(u"tii", u"டீ")
    translated = translated.replace(u"ti", u"டி")
    translated = translated.replace(u"taa", u"டா")
    translated = translated.replace(u"ta", u"ட")
    translated = translated.replace(u"t", u"ட்")

    # ட Family
    translated = translated.replace(u"dau", u"டௌ")
    translated = translated.replace(u"doo", u"டோ")
    translated = translated.replace(u"do", u"டொ")
    translated = translated.replace(u"dai", u"டை")
    translated = translated.replace(u"dee", u"டே")
    translated = translated.replace(u"de", u"டெ")
    translated = translated.replace(u"duu", u"டூ")
    translated = translated.replace(u"du", u"டு")
    translated = translated.replace(u"dii", u"டீ")
    translated = translated.replace(u"di", u"டி")
    translated = translated.replace(u"daa", u"டா")
    translated = translated.replace(u"da", u"ட")
    translated = translated.replace(u"d", u"ட்")

    # ண Family
    # translated = translated.replace(u"Nau", u"ணௌ")
    # translated = translated.replace(u"Noo", u"ணோ")
    # translated = translated.replace(u"No", u"ணொ")
    # translated = translated.replace(u"Nai", u"ணை")
    # translated = translated.replace(u"Nee", u"ணே")
    # translated = translated.replace(u"Ne", u"ணெ")
    # translated = translated.replace(u"Nuu", u"ணூ")
    # translated = translated.replace(u"Nu", u"ணு")
    # translated = translated.replace(u"Nii", u"ணீ")
    # translated = translated.replace(u"Ni", u"ணி")
    # translated = translated.replace(u"Naa", u"ணா")
    # translated = translated.replace(u"Na", u"ண")
    # translated = translated.replace(u"N", u"ண்")

    # ண Family
    translated = translated.replace(u"nNau", u"ணௌ")
    translated = translated.replace(u"nNoo", u"ணோ")
    translated = translated.replace(u"nNo", u"ணொ")
    translated = translated.replace(u"nNai", u"ணை")
    translated = translated.replace(u"nNee", u"ணே")
    translated = translated.replace(u"nNe", u"ணெ")
    translated = translated.replace(u"nNuu", u"ணூ")
    translated = translated.replace(u"nNu", u"ணு")
    translated = translated.replace(u"nNii", u"ணீ")
    translated = translated.replace(u"nNi", u"ணி")
    translated = translated.replace(u"nNaa", u"ணா")
    translated = translated.replace(u"nNa", u"ண")
    translated = translated.replace(u"nN", u"ண்")

    # ந Family
    translated = translated.replace(u"Nau", u"நௌ")
    translated = translated.replace(u"Noo", u"நோ")
    translated = translated.replace(u"No", u"நொ")
    translated = translated.replace(u"Nai", u"நை")
    translated = translated.replace(u"Nee", u"நே")
    translated = translated.replace(u"Ne", u"நெ")
    translated = translated.replace(u"Nuu", u"நூ")
    translated = translated.replace(u"Nu", u"நு")
    translated = translated.replace(u"Nii", u"நீ")
    translated = translated.replace(u"Ni", u"நி")
    translated = translated.replace(u"Naa", u"நா")
    translated = translated.replace(u"Na", u"ந")
    translated = translated.replace(u"N", u"ந்")

    # ன Family
    translated = translated.replace(u"nau", u"னௌ")
    translated = translated.replace(u"noo", u"னோ")
    translated = translated.replace(u"no", u"னொ")
    translated = translated.replace(u"nai", u"னை")
    translated = translated.replace(u"nee", u"னே")
    translated = translated.replace(u"ne", u"னெ")
    translated = translated.replace(u"nuu", u"னூ")
    translated = translated.replace(u"nu", u"னு")
    translated = translated.replace(u"nii", u"னீ")
    translated = translated.replace(u"ni", u"னி")
    translated = translated.replace(u"naa", u"னா")
    translated = translated.replace(u"na", u"ன")
    translated = translated.replace(u"n", u"ன்")

    # ப Family
    translated = translated.replace(u"pau", u"பௌ")
    translated = translated.replace(u"poo", u"போ")
    translated = translated.replace(u"po", u"பொ")
    translated = translated.replace(u"pai", u"பை")
    translated = translated.replace(u"pee", u"பே")
    translated = translated.replace(u"pe", u"பெ")
    translated = translated.replace(u"puu", u"பூ")
    translated = translated.replace(u"pu", u"பு")
    translated = translated.replace(u"pii", u"பீ")
    translated = translated.replace(u"pi", u"பி")
    translated = translated.replace(u"paa", u"பா")
    translated = translated.replace(u"pa", u"ப")
    translated = translated.replace(u"p", u"ப்")

    # ப Family
    translated = translated.replace(u"bhau", u"பௌ")
    translated = translated.replace(u"bhoo", u"போ")
    translated = translated.replace(u"bho", u"பொ")
    translated = translated.replace(u"bhai", u"பை")
    translated = translated.replace(u"bhee", u"பே")
    translated = translated.replace(u"bhe", u"பெ")
    translated = translated.replace(u"bhuu", u"பூ")
    translated = translated.replace(u"bhu", u"பு")
    translated = translated.replace(u"bhii", u"பீ")
    translated = translated.replace(u"bhi", u"பி")
    translated = translated.replace(u"bhaa", u"பா")
    translated = translated.replace(u"bha", u"ப")
    translated = translated.replace(u"bh", u"ப்")

    # ப Family
    translated = translated.replace(u"bau", u"பௌ")
    translated = translated.replace(u"boo", u"போ")
    translated = translated.replace(u"bo", u"பொ")
    translated = translated.replace(u"bai", u"பை")
    translated = translated.replace(u"bee", u"பே")
    translated = translated.replace(u"be", u"பெ")
    translated = translated.replace(u"buu", u"பூ")
    translated = translated.replace(u"bu", u"பு")
    translated = translated.replace(u"bii", u"பீ")
    translated = translated.replace(u"bi", u"பி")
    translated = translated.replace(u"baa", u"பா")
    translated = translated.replace(u"ba", u"ப")
    translated = translated.replace(u"b", u"ப்")

    # ம Family
    translated = translated.replace(u"mau", u"மௌ")
    translated = translated.replace(u"moo", u"மோ")
    translated = translated.replace(u"mo", u"மொ")
    translated = translated.replace(u"mai", u"மை")
    translated = translated.replace(u"mee", u"மே")
    translated = translated.replace(u"me", u"மெ")
    translated = translated.replace(u"muu", u"மூ")
    translated = translated.replace(u"mu", u"மு")
    translated = translated.replace(u"mii", u"மீ")
    translated = translated.replace(u"mi", u"மி")
    translated = translated.replace(u"maa", u"மா")
    translated = translated.replace(u"ma", u"ம")
    translated = translated.replace(u"m", u"ம்")

    # ய Family
    translated = translated.replace(u"yau", u"யௌ")
    translated = translated.replace(u"yoo", u"யோ")
    translated = translated.replace(u"yo", u"யொ")
    translated = translated.replace(u"yai", u"யை")
    translated = translated.replace(u"yee", u"யே")
    translated = translated.replace(u"ye", u"யெ")
    translated = translated.replace(u"yuu", u"யூ")
    translated = translated.replace(u"yu", u"யு")
    translated = translated.replace(u"yii", u"யீ")
    translated = translated.replace(u"yi", u"யி")
    translated = translated.replace(u"yaa", u"யா")
    translated = translated.replace(u"ya", u"ய")
    translated = translated.replace(u"y", u"ய்")

    # ர Family
    translated = translated.replace(u"rau", u"ரௌ")
    translated = translated.replace(u"roo", u"ரோ")
    translated = translated.replace(u"ro", u"ரொ")
    translated = translated.replace(u"rai", u"ரை")
    translated = translated.replace(u"ree", u"ரே")
    translated = translated.replace(u"re", u"ரெ")
    translated = translated.replace(u"ruu", u"ரூ")
    translated = translated.replace(u"ru", u"ரு")
    translated = translated.replace(u"rii", u"ரீ")
    translated = translated.replace(u"ri", u"ரி")
    translated = translated.replace(u"raa", u"ரா")
    translated = translated.replace(u"ra", u"ர")
    translated = translated.replace(u"r", u"ர்")

    # ற Family
    translated = translated.replace(u"Rau", u"றௌ")
    translated = translated.replace(u"Roo", u"றோ")
    translated = translated.replace(u"Ro", u"றொ")
    translated = translated.replace(u"Rai", u"றை")
    translated = translated.replace(u"Ree", u"றே")
    translated = translated.replace(u"re", u"ரெ")
    translated = translated.replace(u"Ruu", u"றூ")
    translated = translated.replace(u"Ru", u"று")
    translated = translated.replace(u"Rii", u"றீ")
    translated = translated.replace(u"Ri", u"றி")
    translated = translated.replace(u"Raa", u"றா")
    translated = translated.replace(u"Ra", u"ற")
    translated = translated.replace(u"R", u"ற்")

    # ல Family
    translated = translated.replace(u"lau", u"லௌ")
    translated = translated.replace(u"loo", u"லோ")
    translated = translated.replace(u"lo", u"லொ")
    translated = translated.replace(u"lai", u"லை")
    translated = translated.replace(u"lee", u"லே")
    translated = translated.replace(u"le", u"லெ")
    translated = translated.replace(u"luu", u"லூ")
    translated = translated.replace(u"lu", u"லு")
    translated = translated.replace(u"lii", u"லீ")
    translated = translated.replace(u"li", u"லி")
    translated = translated.replace(u"laa", u"லா")
    translated = translated.replace(u"la", u"ல")
    translated = translated.replace(u"l", u"ல்")

    # ள Family
    translated = translated.replace(u"Lau", u"ளௌ")
    translated = translated.replace(u"Loo", u"ளோ")
    translated = translated.replace(u"Lo", u"ளொ")
    translated = translated.replace(u"Lai", u"ளை")
    translated = translated.replace(u"Lee", u"ளே")
    translated = translated.replace(u"Le", u"ளெ")
    translated = translated.replace(u"Luu", u"ளூ")
    translated = translated.replace(u"Lu", u"ளு")
    translated = translated.replace(u"Lii", u"ளீ")
    translated = translated.replace(u"Li", u"ளி")
    translated = translated.replace(u"Laa", u"ளா")
    translated = translated.replace(u"La", u"ள")
    translated = translated.replace(u"L", u"ள்")

    # ழ Family
    translated = translated.replace(u"zau", u"ழௌ")
    translated = translated.replace(u"zoo", u"ழோ")
    translated = translated.replace(u"zo", u"ழொ")
    translated = translated.replace(u"zai", u"ழை")
    translated = translated.replace(u"zee", u"ழே")
    translated = translated.replace(u"ze", u"ழெ")
    translated = translated.replace(u"zuu", u"ழூ")
    translated = translated.replace(u"zu", u"ழு")
    translated = translated.replace(u"zii", u"ழீ")
    translated = translated.replace(u"zi", u"ழி")
    translated = translated.replace(u"zaa", u"ழா")
    translated = translated.replace(u"za", u"ழ")
    translated = translated.replace(u"z", u"ழ்")

    # ழ Family
    translated = translated.replace(u"zhau", u"ழௌ")
    translated = translated.replace(u"zhoo", u"ழோ")
    translated = translated.replace(u"zho", u"ழொ")
    translated = translated.replace(u"zhai", u"ழை")
    translated = translated.replace(u"zhee", u"ழே")
    translated = translated.replace(u"zhe", u"ழெ")
    translated = translated.replace(u"zhuu", u"ழூ")
    translated = translated.replace(u"zhu", u"ழு")
    translated = translated.replace(u"zhii", u"ழீ")
    translated = translated.replace(u"zhi", u"ழி")
    translated = translated.replace(u"zhaa", u"ழா")
    translated = translated.replace(u"zha", u"ழ")
    translated = translated.replace(u"zh", u"ழ்")

    # வ Family
    translated = translated.replace(u"vau", u"வௌ")
    translated = translated.replace(u"voo", u"வோ")
    translated = translated.replace(u"vo", u"வொ")
    translated = translated.replace(u"vai", u"வை")
    translated = translated.replace(u"vee", u"வே")
    translated = translated.replace(u"ve", u"வெ")
    translated = translated.replace(u"vuu", u"வூ")
    translated = translated.replace(u"vu", u"வு")
    translated = translated.replace(u"vii", u"வீ")
    translated = translated.replace(u"vi", u"வி")
    translated = translated.replace(u"vaa", u"வா")
    translated = translated.replace(u"va", u"வ")
    translated = translated.replace(u"v", u"வ்")

    # வ Family
    translated = translated.replace(u"wau", u"வௌ")
    translated = translated.replace(u"woo", u"வோ")
    translated = translated.replace(u"wo", u"வொ")
    translated = translated.replace(u"wai", u"வை")
    translated = translated.replace(u"wee", u"வே")
    translated = translated.replace(u"we", u"வெ")
    translated = translated.replace(u"wuu", u"வூ")
    translated = translated.replace(u"wu", u"வு")
    translated = translated.replace(u"wii", u"வீ")
    translated = translated.replace(u"wi", u"வி")
    translated = translated.replace(u"waa", u"வா")
    translated = translated.replace(u"wa", u"வ")
    translated = translated.replace(u"w", u"வ்")

    # ஷ Family
    translated = translated.replace(u"shau", u"ஷௌ")
    translated = translated.replace(u"shoo", u"ஷோ")
    translated = translated.replace(u"sho", u"ஷொ")
    translated = translated.replace(u"shai", u"ஷை")
    translated = translated.replace(u"shee", u"ஷே")
    translated = translated.replace(u"she", u"ஷெ")
    translated = translated.replace(u"shuu", u"ஷூ")
    translated = translated.replace(u"shu", u"ஷு")
    translated = translated.replace(u"shii", u"ஷீ")
    translated = translated.replace(u"shi", u"ஷி")
    translated = translated.replace(u"shaa", u"ஷா")
    translated = translated.replace(u"sha", u"ஷ")
    translated = translated.replace(u"sh", u"ஷ்")

    # ஸ Family
    translated = translated.replace(u"sau", u"ஸௌ")
    translated = translated.replace(u"soo", u"ஸோ")
    translated = translated.replace(u"so", u"ஸொ")
    translated = translated.replace(u"sai", u"ஸை")
    translated = translated.replace(u"see", u"ஸே")
    translated = translated.replace(u"se", u"ஸெ")
    translated = translated.replace(u"suu", u"ஸூ")
    translated = translated.replace(u"su", u"ஸு")
    translated = translated.replace(u"sii", u"ஸீ")
    translated = translated.replace(u"si", u"ஸி")
    translated = translated.replace(u"saa", u"ஸா")
    translated = translated.replace(u"sa", u"ஸ")
    translated = translated.replace(u"s", u"ஸ்")

    # ஹ Family
    translated = translated.replace(u"hau", u"ஹௌ")
    translated = translated.replace(u"hoo", u"ஹோ")
    translated = translated.replace(u"ho", u"ஹொ")
    translated = translated.replace(u"hai", u"ஹை")
    translated = translated.replace(u"hee", u"ஹே")
    translated = translated.replace(u"he", u"ஹெ")
    translated = translated.replace(u"hii", u"ஹீ")
    translated = translated.replace(u"hi", u"ஹி")
    translated = translated.replace(u"haa", u"ஹா")
    translated = translated.replace(u"ha", u"ஹ")
    translated = translated.replace(u"h", u"ஹ்")

    # Independent Vowels
    translated = translated.replace(u"oa", u"ஓ")
    translated = translated.replace(u"aa", u"ஆ")
    translated = translated.replace(u"au", u"ஔ")
    translated = translated.replace(u"ai", u"ஐ")
    translated = translated.replace(u"ae", u"ஏ")
    translated = translated.replace(u"a", u"அ")
    translated = translated.replace(u"ee", u"ஈ")
    translated = translated.replace(u"I", u"ஈ")
    translated = translated.replace(u"ii", u"ஈ")
    translated = translated.replace(u"i", u"இ")
    translated = translated.replace(u"U", u"ஊ")
    translated = translated.replace(u"oo", u"ஊ")
    translated = translated.replace(u"uu", u"ஊ")
    translated = translated.replace(u"u", u"உ")
    # translated = translated.replace(u"ee", u"ஏ")
    translated = translated.replace(u"e", u"எ")
    translated = translated.replace(u"E", u"ஏ")
    # translated = translated.replace(u"oo", u"ஓ")
    translated = translated.replace(u"O", u"ஓ")
    translated = translated.replace(u"o", u"ஒ")
    translated = translated.replace(u"q", u"ஃ")
    translated = translated.replace(u"H", u"ஃ")
    translated = translated.replace(u"Ahh", u"ஃ")

    unconverted = [i for i in translated if i in source_text and not i in
                    punctuation+whitespace+digits]
    translated_trimed = ''.join([i for i in translated if not i in unconverted])

    if debug:
        return unconverted
    elif filtered:
        return translated_trimed
    else:
        return translated