# -*- coding: utf-8 -*-
from string import punctuation, whitespace, digits


def convertTobamini(source_text, filtered=False, debug=False):
    translated = source_text
    # Independent Vowels
    translated = translated.replace(u"அ", u"m")
    translated = translated.replace(u"ஆ", u"M")
    translated = translated.replace(u"இ", u",")
    translated = translated.replace(u"ஈ", u"<")
    translated = translated.replace(u"உ", u"c")
    translated = translated.replace(u"ஊ", u"C")
    translated = translated.replace(u"எ", u"v")
    translated = translated.replace(u"ஏ", u"V")
    translated = translated.replace(u"ஐ", u"I")
    translated = translated.replace(u"ஒ", u"x")
    translated = translated.replace(u"ஓ", u"X")
    translated = translated.replace(u"ஔ", u"xs")
    translated = translated.replace(u"ஃ", u"\/")

    #---
    translated = translated.replace(u"ரீ", u"hP")
    translated = translated.replace(u"ரி", u"hp")
    translated = translated.replace(u"ர்", u"H")
    translated = translated.replace(u"ர்", u"h;")
    translated = translated.replace(u"ர்", u"u;")

    # க Family
    translated = translated.replace(u"க்", u"f;")
    translated = translated.replace(u"கௌ", u"nfs")
    translated = translated.replace(u"கோ", u"Nfh")
    translated = translated.replace(u"கொ", u"nfh")
    translated = translated.replace(u"கை", u"if")
    translated = translated.replace(u"கே", u"Nf")
    translated = translated.replace(u"கெ", u"nf")
    translated = translated.replace(u"கூ", u"\$")
    translated = translated.replace(u"கு", u"F")
    translated = translated.replace(u"கீ", u"fP")
    translated = translated.replace(u"கி", u"fp")
    translated = translated.replace(u"கா", u"fh")
    translated = translated.replace(u"க", u"f")

    # ங Family
    translated = translated.replace(u"ங்", u"q;")
    translated = translated.replace(u"ஙௌ", u"nqs")
    translated = translated.replace(u"ஙோ", u"Nqh")
    translated = translated.replace(u"ஙொ", u"nqh")
    translated = translated.replace(u"ஙை", u"iq")
    translated = translated.replace(u"ஙே", u"Nq")
    translated = translated.replace(u"ஙெ", u"nq")
    translated = translated.replace(u"ஙீ", u"qP")
    translated = translated.replace(u"ஙி", u"qp")
    translated = translated.replace(u"ஙா", u"qh")
    translated = translated.replace(u"ங", u"q")

    # ச Family
    translated = translated.replace(u"ச்", u"r;")
    translated = translated.replace(u"சௌ", u"nrs")
    translated = translated.replace(u"சோ", u"Nrh")
    translated = translated.replace(u"சொ", u"nrh")
    translated = translated.replace(u"சை", u"ir")
    translated = translated.replace(u"சே", u"Nr")
    translated = translated.replace(u"செ", u"nr")
    translated = translated.replace(u"சூ", u"#")
    translated = translated.replace(u"சு", u"R")
    translated = translated.replace(u"சீ", u"rP")
    translated = translated.replace(u"சி", u"rp")
    translated = translated.replace(u"சா", u"rh")
    translated = translated.replace(u"ச", u"r")

    # ஜ Family
    translated = translated.replace(u"ஜ்", u"\[;")
    translated = translated.replace(u"ஜௌ", u"n\[s")
    translated = translated.replace(u"ஜோ", u"N\[h")
    translated = translated.replace(u"ஜொ", u"n\[h")
    translated = translated.replace(u"ஜை", u"i\[")
    translated = translated.replace(u"ஜே", u"N\[")
    translated = translated.replace(u"ஜெ", u"n\[")
    translated = translated.replace(u"ஜூ", u"\[_")
    translated = translated.replace(u"ஜு", u"\[{")
    translated = translated.replace(u"ஜீ", u"\[P")
    translated = translated.replace(u"ஜி", u"\[p")
    translated = translated.replace(u"ஜா", u"\[h")
    translated = translated.replace(u"ஜ", u"\[")

    # ஞ Family
    translated = translated.replace(u"ஞ்", u"Q;")
    translated = translated.replace(u"ஞௌ", u"nQs")
    translated = translated.replace(u"ஞோ", u"NQh")
    translated = translated.replace(u"ஞொ", u"nQh")
    translated = translated.replace(u"ஞை", u"iQ")
    translated = translated.replace(u"ஞே", u"NQ")
    translated = translated.replace(u"ஞெ", u"nQ")
    translated = translated.replace(u"ஞீ", u"QP")
    translated = translated.replace(u"ஞி", u"Qp")
    translated = translated.replace(u"ஞா", u"Qh")
    translated = translated.replace(u"ஞ", u"Q")

    # ட Family
    translated = translated.replace(u"ட்", u"l;")
    translated = translated.replace(u"டௌ", u"nls")
    translated = translated.replace(u"டோ", u"Nlh")
    translated = translated.replace(u"டொ", u"nlh")
    translated = translated.replace(u"டை", u"il")
    translated = translated.replace(u"டே", u"Nl")
    translated = translated.replace(u"டெ", u"nl")
    translated = translated.replace(u"டூ", u"\^")
    translated = translated.replace(u"டு", u"L")
    translated = translated.replace(u"டீ", u"lP")
    translated = translated.replace(u"டி", u"lp")
    translated = translated.replace(u"டி", u"b")
    translated = translated.replace(u"டா", u"lh")
    translated = translated.replace(u"ட", u"l")

    # ண Family
    translated = translated.replace(u"ண்", u"z;")
    translated = translated.replace(u"ணௌ", u"nzs")
    translated = translated.replace(u"ணோ", u"Nzh")
    translated = translated.replace(u"ணொ", u"nzh")
    translated = translated.replace(u"ணை", u"iz")
    translated = translated.replace(u"ணே", u"Nz")
    translated = translated.replace(u"ணெ", u"nz")
    translated = translated.replace(u"ணூ", u"Zh")
    translated = translated.replace(u"ணு", u"Z")
    translated = translated.replace(u"ணீ", u"zP")
    translated = translated.replace(u"ணி", u"zp")
    translated = translated.replace(u"ணா", u"zh")
    translated = translated.replace(u"ண", u"z")

    # த Family
    translated = translated.replace(u"த்", u"j;")
    translated = translated.replace(u"தௌ", u"njs")
    translated = translated.replace(u"தோ", u"Njh")
    translated = translated.replace(u"தொ", u"njh")
    translated = translated.replace(u"தை", u"ij")
    translated = translated.replace(u"தே", u"Nj")
    translated = translated.replace(u"தெ", u"nj")
    translated = translated.replace(u"தூ", u"Jh")
    translated = translated.replace(u"து", u"J")
    translated = translated.replace(u"தீ", u"jP")
    translated = translated.replace(u"தி", u"jp")
    translated = translated.replace(u"தா", u"jh")
    translated = translated.replace(u"த", u"j")

    # ந Family
    translated = translated.replace(u"ந்", u"e;")
    translated = translated.replace(u"நௌ", u"nes")
    translated = translated.replace(u"நோ", u"Neh")
    translated = translated.replace(u"நொ", u"neh")
    translated = translated.replace(u"நை", u"ie")
    translated = translated.replace(u"நே", u"Ne")
    translated = translated.replace(u"நெ", u"ne")
    translated = translated.replace(u"நூ", u"E}")
    translated = translated.replace(u"நூ", u"Eh")
    translated = translated.replace(u"நு", u"E")
    translated = translated.replace(u"நீ", u"eP")
    translated = translated.replace(u"நி", u"ep")
    translated = translated.replace(u"நா", u"eh")
    translated = translated.replace(u"ந", u"e")

    # ன Family
    translated = translated.replace(u"ன்", u"d;")
    translated = translated.replace(u"னௌ", u"nds")
    translated = translated.replace(u"னோ", u"Ndh")
    translated = translated.replace(u"னொ", u"ndh")
    translated = translated.replace(u"னை", u"id")
    translated = translated.replace(u"னே", u"Nd")
    translated = translated.replace(u"னெ", u"nd")
    translated = translated.replace(u"னூ", u"D}")
    translated = translated.replace(u"னு", u"D")
    translated = translated.replace(u"னீ", u"dP")
    translated = translated.replace(u"னி", u"dp")
    translated = translated.replace(u"னா", u"dh")
    translated = translated.replace(u"ன", u"d")

    # ப Family
    translated = translated.replace(u"ப்", u"g;")
    translated = translated.replace(u"பௌ", u"ngs")
    translated = translated.replace(u"போ", u"Ngh")
    translated = translated.replace(u"பொ", u"ngh")
    translated = translated.replace(u"பை", u"ig")
    translated = translated.replace(u"பே", u"Ng")
    translated = translated.replace(u"பெ", u"ng")
    translated = translated.replace(u"பூ", u"G\+")
    translated = translated.replace(u"பு", u"G")
    translated = translated.replace(u"பீ", u"gP")
    translated = translated.replace(u"பி", u"gp")
    translated = translated.replace(u"பா", u"gh")
    translated = translated.replace(u"ப", u"g")

    # ம Family
    translated = translated.replace(u"ம்", u"k;")
    translated = translated.replace(u"மௌ", u"nks")
    translated = translated.replace(u"மோ", u"Nkh")
    translated = translated.replace(u"மொ", u"nkh")
    translated = translated.replace(u"மை", u"ik")
    translated = translated.replace(u"மே", u"Nk")
    translated = translated.replace(u"மெ", u"nk")
    translated = translated.replace(u"மூ", u"%")
    translated = translated.replace(u"மு", u"K")
    translated = translated.replace(u"மீ", u"kP")
    translated = translated.replace(u"மி", u"kp")
    translated = translated.replace(u"மா", u"kh")
    translated = translated.replace(u"ம", u"k")

    # ய Family
    translated = translated.replace(u"ய்", u"a;")
    translated = translated.replace(u"யௌ", u"nas")
    translated = translated.replace(u"யோ", u"Nah")
    translated = translated.replace(u"யொ", u"nah")
    translated = translated.replace(u"யை", u"ia")
    translated = translated.replace(u"யே", u"Na")
    translated = translated.replace(u"யெ", u"na")
    translated = translated.replace(u"யூ", u"A+")
    translated = translated.replace(u"யு", u"A")
    translated = translated.replace(u"யீ", u"aP")
    translated = translated.replace(u"யி", u"ap")
    translated = translated.replace(u"யா", u"ah")
    translated = translated.replace(u"ய", u"a")

    # ர Family
    translated = translated.replace(u"ரௌ", u"nus")
    translated = translated.replace(u"ரோ", u"Nuh")
    translated = translated.replace(u"ரொ", u"nuh")
    translated = translated.replace(u"ரை", u"iu")
    translated = translated.replace(u"ரே", u"Nu")
    translated = translated.replace(u"ரெ", u"nu")
    translated = translated.replace(u"ரூ", u"&")
    translated = translated.replace(u"ரு", u"U")
    translated = translated.replace(u"ரா", u"uh")
    translated = translated.replace(u"ர", u"u")

    # ற Family
    translated = translated.replace(u"ற்", u"w;")
    translated = translated.replace(u"றௌ", u"nws")
    translated = translated.replace(u"றோ", u"Nwh")
    translated = translated.replace(u"றொ", u"nwh")
    translated = translated.replace(u"றை", u"iw")
    translated = translated.replace(u"றே", u"Nw")
    translated = translated.replace(u"ரெ", u"nu")
    translated = translated.replace(u"றூ", u"Wh")
    translated = translated.replace(u"றூ", u"W}")
    translated = translated.replace(u"று", u"W")
    translated = translated.replace(u"றீ", u"wP")
    translated = translated.replace(u"றி", u"wp")
    translated = translated.replace(u"றா", u"wh")
    translated = translated.replace(u"ற", u"w")

    # ல Family
    translated = translated.replace(u"ல்", u"y;")
    translated = translated.replace(u"லௌ", u"nys")
    translated = translated.replace(u"லோ", u"Nyh")
    translated = translated.replace(u"லொ", u"nyh")
    translated = translated.replace(u"லை", u"iy")
    translated = translated.replace(u"லே", u"Ny")
    translated = translated.replace(u"லெ", u"ny")
    translated = translated.replace(u"லூ", u"Yh")
    translated = translated.replace(u"லூ", u"Y}")
    translated = translated.replace(u"லு", u"Y")
    translated = translated.replace(u"லீ", u"yP")
    translated = translated.replace(u"லி", u"yp")
    translated = translated.replace(u"லா", u"yh")
    translated = translated.replace(u"ல", u"y")

    # ள Family
    translated = translated.replace(u"ள்", u"s;")
    translated = translated.replace(u"ளௌ", u"nss")
    translated = translated.replace(u"ளோ", u"Nsh")
    translated = translated.replace(u"ளை", u"is")
    translated = translated.replace(u"ளே", u"Ns")
    translated = translated.replace(u"ளெ", u"ns")
    translated = translated.replace(u"ளூ", u"Sh")
    translated = translated.replace(u"ளு", u"S")
    translated = translated.replace(u"ளீ", u"sP")
    translated = translated.replace(u"ளி", u"sp")
    translated = translated.replace(u"ளா", u"sh")
    translated = translated.replace(u"ள", u"s")

    # ழ Family
    translated = translated.replace(u"ழ்", u"o;")
    translated = translated.replace(u"ழௌ", u"noo")
    translated = translated.replace(u"ழோ", u"Noh")
    translated = translated.replace(u"ழொ", u"noh")
    translated = translated.replace(u"ழை", u"io")
    translated = translated.replace(u"ழே", u"No")
    translated = translated.replace(u"ழெ", u"no")
    translated = translated.replace(u"ழூ", u"\*")
    translated = translated.replace(u"ழு", u"O")
    translated = translated.replace(u"ழீ", u"oP")
    translated = translated.replace(u"ழி", u"op")
    translated = translated.replace(u"ழா", u"oh")
    translated = translated.replace(u"ழ", u"o")

    # வ Family
    translated = translated.replace(u"வ்", u"t;")
    translated = translated.replace(u"வௌ", u"ntt")
    translated = translated.replace(u"வோ", u"Nth")
    translated = translated.replace(u"வொ", u"nth")
    translated = translated.replace(u"வை", u"it")
    translated = translated.replace(u"வே", u"Nt")
    translated = translated.replace(u"வெ", u"nt")
    translated = translated.replace(u"வூ", u"வு10")
    translated = translated.replace(u"வு", u"T")
    translated = translated.replace(u"வீ", u"tP")
    translated = translated.replace(u"வி", u"tp")
    translated = translated.replace(u"வா", u"th")
    translated = translated.replace(u"வ", u"t")

    # ஷ Family
    translated = translated.replace(u"ஷ்", u"\\;")
    translated = translated.replace(u"ஷௌ", u"n\\s")
    translated = translated.replace(u"ஷோ", u"N\\h")
    translated = translated.replace(u"ஷொ", u"n\\h")
    translated = translated.replace(u"ஷை", u"i\\")
    translated = translated.replace(u"ஷே", u"N\\")
    translated = translated.replace(u"ஷெ", u"n\\")
    translated = translated.replace(u"ஷீ", u"\\P")
    translated = translated.replace(u"ஷி", u"\\p")
    translated = translated.replace(u"ஷா", u"\\h")
    translated = translated.replace(u"ஷ", u"\\")

    # ஸ Family
    translated = translated.replace(u"ஸ்", u"];")
    translated = translated.replace(u"ஸௌ", u"n]s")
    translated = translated.replace(u"ஸோ", u"N]h")
    translated = translated.replace(u"ஸொ", u"n]h")
    translated = translated.replace(u"ஸை", u"i]")
    translated = translated.replace(u"ஸே", u"N]")
    translated = translated.replace(u"ஸெ", u"n]")
    translated = translated.replace(u"ஸீ", u"]P")
    translated = translated.replace(u"ஸி", u"]p")
    translated = translated.replace(u"ஸா", u"]h")
    translated = translated.replace(u"ஸ", u"]")

    # ஹ Family
    translated = translated.replace(u"ஹ்", u"`;")
    translated = translated.replace(u"ஹௌ", u"n``")
    translated = translated.replace(u"ஹோ", u"N`h")
    translated = translated.replace(u"ஹொ", u"n`h")
    translated = translated.replace(u"ஹை", u"i`")
    translated = translated.replace(u"ஹே", u"N`")
    translated = translated.replace(u"ஹெ", u"n`")
    translated = translated.replace(u"ஹீ", u"`P")
    translated = translated.replace(u"ஹி", u"`p")
    translated = translated.replace(u"ஹா", u"`h")
    translated = translated.replace(u"ஹ", u"`")

    translated = translated.replace(u"ஸ்ரீ", u"=")

    unconverted = [i for i in translated if i in source_text and not i in
                    punctuation+whitespace+digits]
    translated_trimed = ''.join([i for i in translated if not i in unconverted])

    if debug:
        return unconverted
    elif filtered:
        return translated_trimed
    else:
        return translated