# -*- coding: utf-8 -*-
from string import punctuation, whitespace, digits


def convertToshreelipi(source_text, filtered=False, debug=False):
    translated = source_text
    
    translated = translated.replace(u"அ", u"A")
    translated = translated.replace(u"ஆ", u"B")
    translated = translated.replace(u"இ", u"C")
    translated = translated.replace(u"ஈ", u"D")
    translated = translated.replace(u"உ", u"E")
    translated = translated.replace(u"ஊ", u"F")
    translated = translated.replace(u"எ", u"G")
    translated = translated.replace(u"ஏ", u"H")
    translated = translated.replace(u"ஐ", u"I")
    translated = translated.replace(u"ஒ", u"J")
    translated = translated.replace(u"ஓ", u"K")
    translated = translated.replace(u"ஔ", u"JÍ")
    translated = translated.replace(u"ஃ", u"ஃ")
    translated = translated.replace(u"ௐ", u"K®")
    translated = translated.replace(u"ஸ்ரீ", u"ÿ")
    
    translated = translated.replace(u"க்", u"U")
    translated = translated.replace(u"கௌ", u"öPÍ")
    translated = translated.replace(u"கோ", u"@Põ")
    translated = translated.replace(u"கொ", u"öPõ")
    translated = translated.replace(u"கை", u"øP")
    translated = translated.replace(u"கே", u"@P")
    translated = translated.replace(u"கெ", u"öP")
    translated = translated.replace(u"கூ", u"T")
    translated = translated.replace(u"கு", u"S")
    translated = translated.replace(u"கீ", u"R")
    translated = translated.replace(u"கி", u"Q")
    translated = translated.replace(u"கா", u"Põ")
    translated = translated.replace(u"க", u"P")
    
    translated = translated.replace(u"ங்", u"[")
    translated = translated.replace(u"ஙௌ", u"öVÍ")
    translated = translated.replace(u"ஙோ", u"@Võ")
    translated = translated.replace(u"ஙொ", u"öVõ")
    translated = translated.replace(u"ஙை", u"øV")
    translated = translated.replace(u"ஙே", u"@V")
    translated = translated.replace(u"ஙெ", u"öV")
    translated = translated.replace(u"ஙூ", u"Z")
    translated = translated.replace(u"ஙு", u"Y")
    translated = translated.replace(u"ஙீ", u"X")
    translated = translated.replace(u"ஙி", u"W")
    translated = translated.replace(u"ஙா", u"Võ")
    translated = translated.replace(u"ங", u"V")
    
    translated = translated.replace(u"ச்", u"a")
    translated = translated.replace(u"சௌ", u"öŒÍ")
    translated = translated.replace(u"சோ", u"@Œõ")
    translated = translated.replace(u"சொ", u"öŒõ")
    translated = translated.replace(u"சை", u"øŒ")
    translated = translated.replace(u"சே", u"@Œ")
    translated = translated.replace(u"செ", u"öŒ")
    translated = translated.replace(u"சூ", u"‹")
    translated = translated.replace(u"சு", u"”")
    translated = translated.replace(u"சீ", u"^")
    translated = translated.replace(u"சி", u"]")
    translated = translated.replace(u"சா", u"Œõ")
    translated = translated.replace(u"ச", u"Œ")
    
    translated = translated.replace(u"ஜ்", u"ä")
    translated = translated.replace(u"ஜௌ", u"öáÍ")
    translated = translated.replace(u"ஜோ", u"@áõ")
    translated = translated.replace(u"ஜொ", u"öáõ")
    translated = translated.replace(u"ஜை", u"øá")
    translated = translated.replace(u"ஜே", u"@á")
    translated = translated.replace(u"ஜெ", u"öá")
    translated = translated.replace(u"ஜூ", u"á„")
    translated = translated.replace(u"ஜு", u"áú")
    translated = translated.replace(u"ஜீ", u"ã")
    translated = translated.replace(u"ஜி", u"â")
    translated = translated.replace(u"ஜா", u"áõ")
    translated = translated.replace(u"ஜ", u"á")
    
    translated = translated.replace(u"ஞ்", u"g")
    translated = translated.replace(u"ஞௌ", u"öbÍ")
    translated = translated.replace(u"ஞோ", u"@bõ")
    translated = translated.replace(u"ஞொ", u"öbõ")
    translated = translated.replace(u"ஞை", u"øb")
    translated = translated.replace(u"ஞே", u"@b")
    translated = translated.replace(u"ஞெ", u"öb")
    translated = translated.replace(u"ஞூ", u"f")
    translated = translated.replace(u"ஞு", u"e")
    translated = translated.replace(u"ஞீ", u"d")
    translated = translated.replace(u"ஞி", u"c")
    translated = translated.replace(u"ஞா", u"bõ")
    translated = translated.replace(u"ஞ", u"b")
    
    translated = translated.replace(u"ட்", u"m")
    translated = translated.replace(u"டௌ", u"öhÍ")
    translated = translated.replace(u"டோ", u"@hõ")
    translated = translated.replace(u"டொ", u"öhõ")
    translated = translated.replace(u"டை", u"øh")
    translated = translated.replace(u"டே", u"@h")
    translated = translated.replace(u"டெ", u"öh")
    translated = translated.replace(u"டூ", u"l")
    translated = translated.replace(u"டு", u"k")
    translated = translated.replace(u"டீ", u"j")
    translated = translated.replace(u"டி", u"i")
    translated = translated.replace(u"டா", u"hõ")
    translated = translated.replace(u"ட", u"h")
    
    translated = translated.replace(u"ண்", u"s")
    translated = translated.replace(u"ணௌ", u"önÍ")
    translated = translated.replace(u"ணோ", u"@nõ")
    translated = translated.replace(u"ணொ", u"önõ")
    translated = translated.replace(u"ணை", u"øn")
    translated = translated.replace(u"ணே", u"@n")
    translated = translated.replace(u"ணெ", u"ön")
    translated = translated.replace(u"ணூ", u"r")
    translated = translated.replace(u"ணு", u"q")
    translated = translated.replace(u"ணீ", u"p")
    translated = translated.replace(u"ணி", u"o")
    translated = translated.replace(u"ணா", u"nõ")
    translated = translated.replace(u"ண", u"n")
    
    translated = translated.replace(u"த்", u"z")
    translated = translated.replace(u"தௌ", u"öuÍ")
    translated = translated.replace(u"தோ", u"@uõ")
    translated = translated.replace(u"தொ", u"öuõ")
    translated = translated.replace(u"தை", u"øu")
    translated = translated.replace(u"தே", u"@u")
    translated = translated.replace(u"தெ", u"öu")
    translated = translated.replace(u"தூ", u"y")
    translated = translated.replace(u"து", u"x")
    translated = translated.replace(u"தீ", u"w")
    translated = translated.replace(u"தி", u"v")
    translated = translated.replace(u"தா", u"uõ")
    translated = translated.replace(u"த", u"u")
    
    translated = translated.replace(u"ந்", u"¢")
    translated = translated.replace(u"நௌ", u"ö|Í")
    translated = translated.replace(u"நோ", u"@|õ")
    translated = translated.replace(u"நொ", u"ö|õ")
    translated = translated.replace(u"நை", u"ø|")
    translated = translated.replace(u"நே", u"@|")
    translated = translated.replace(u"நெ", u"ö|")
    translated = translated.replace(u"நூ", u"¡")
    translated = translated.replace(u"நு", u"~")
    translated = translated.replace(u"நீ", u"}")
    translated = translated.replace(u"நி", u"{")
    translated = translated.replace(u"நா", u"|õ")
    translated = translated.replace(u"ந", u"|")
    
    translated = translated.replace(u"ன்", u"ß")
    translated = translated.replace(u"னௌ", u"öÚÍ")
    translated = translated.replace(u"னோ", u"@Úõ")
    translated = translated.replace(u"னொ", u"öÚõ")
    translated = translated.replace(u"னை", u"øÚ")
    translated = translated.replace(u"னே", u"@Ú")
    translated = translated.replace(u"னெ", u"öÚ")
    translated = translated.replace(u"னூ", u"Ù")
    translated = translated.replace(u"னு", u"ˆ")
    translated = translated.replace(u"னீ", u"Ü")
    translated = translated.replace(u"னி", u"Û")
    translated = translated.replace(u"னா", u"Úõ")
    translated = translated.replace(u"ன", u"Ú")
    
    translated = translated.replace(u"ப்", u"¨")
    translated = translated.replace(u"பௌ", u"ö£Í")
    translated = translated.replace(u"போ", u"@£õ")
    translated = translated.replace(u"பொ", u"ö£õ")
    translated = translated.replace(u"பை", u"ø£")
    translated = translated.replace(u"பே", u"@£")
    translated = translated.replace(u"பெ", u"ö£")
    translated = translated.replace(u"பூ", u"§")
    translated = translated.replace(u"பு", u">")
    translated = translated.replace(u"பீ", u"¥")
    translated = translated.replace(u"பி", u"$")
    translated = translated.replace(u"பா", u"£õ")
    translated = translated.replace(u"ப", u"£")
    
    translated = translated.replace(u"ம்", u"®")
    translated = translated.replace(u"மௌ", u"ö©Í")
    translated = translated.replace(u"மோ", u"@©õ")
    translated = translated.replace(u"மொ", u"ö©õ")
    translated = translated.replace(u"மை", u"ø©")
    translated = translated.replace(u"மே", u"@©")
    translated = translated.replace(u"மெ", u"ö©")
    translated = translated.replace(u"மூ", u"‰")
    translated = translated.replace(u"மு", u"•")
    translated = translated.replace(u"மீ", u"«")
    translated = translated.replace(u"மி", u"ª")
    translated = translated.replace(u"மா", u"©õ")
    translated = translated.replace(u"ம", u"©")
    
    translated = translated.replace(u"ய்", u"#")
    translated = translated.replace(u"யௌ", u"ö¯Í")
    translated = translated.replace(u"யோ", u"@¯õ")
    translated = translated.replace(u"யொ", u"ö¯õ")
    translated = translated.replace(u"யை", u"ø¯")
    translated = translated.replace(u"யே", u"@¯")
    translated = translated.replace(u"யெ", u"ö¯")
    translated = translated.replace(u"யூ", u"N")
    translated = translated.replace(u"யு", u"M")
    translated = translated.replace(u"யீ", u"±")
    translated = translated.replace(u"யி", u"°")
    translated = translated.replace(u"யா", u"¯õ")
    translated = translated.replace(u"ய", u"¯")
    
    translated = translated.replace(u"ர்", u"º")
    translated = translated.replace(u"ரௌ", u"öµÍ")
    translated = translated.replace(u"ரோ", u"@µõ")
    translated = translated.replace(u"ரொ", u"öµõ")
    translated = translated.replace(u"ரை", u"øµ")
    translated = translated.replace(u"ரே", u"@µ")
    translated = translated.replace(u"ரெ", u"öµ")
    translated = translated.replace(u"ரூ", u"O")
    translated = translated.replace(u"ரு", u"¸")
    translated = translated.replace(u"ரீ", u"Ÿ")
    translated = translated.replace(u"ரி", u"›")
    translated = translated.replace(u"ரா", u"µõ")
    translated = translated.replace(u"ர", u"µ")
    
    translated = translated.replace(u"ற்", u"Ø")
    translated = translated.replace(u"றௌ", u"öÓõ")
    translated = translated.replace(u"றோ", u"@Óõ")
    translated = translated.replace(u"றொ", u"öÓõ")
    translated = translated.replace(u"றை", u"øÓ")
    translated = translated.replace(u"றே", u"@Ó")
    translated = translated.replace(u"ரெ", u"öµ")
    translated = translated.replace(u"றூ", u"–")
    translated = translated.replace(u"று", u"Ö")
    translated = translated.replace(u"றீ", u"Õ")
    translated = translated.replace(u"றி", u"Ô")
    translated = translated.replace(u"றா", u"Óõ")
    translated = translated.replace(u"ற", u"Ó")
    
    translated = translated.replace(u"ல்", u"À")
    translated = translated.replace(u"லௌ", u"ö»Í")
    translated = translated.replace(u"லோ", u"@»õ")
    translated = translated.replace(u"லொ", u"ö»õ")
    translated = translated.replace(u"லை", u"ø»")
    translated = translated.replace(u"லே", u"@»")
    translated = translated.replace(u"லெ", u"ö»")
    translated = translated.replace(u"லூ", u"¿")
    translated = translated.replace(u"லு", u"˜")
    translated = translated.replace(u"லீ", u"—")
    translated = translated.replace(u"லி", u"t")
    translated = translated.replace(u"லா", u"»õ")
    translated = translated.replace(u"ல", u"»")
    
    translated = translated.replace(u"ள்", u"Ò")
    translated = translated.replace(u"ளௌ", u"öÍÍ")
    translated = translated.replace(u"ளோ", u"@Íõ")
    translated = translated.replace(u"ளொ", u"öÍõ")
    translated = translated.replace(u"ளை", u"øÍ")
    translated = translated.replace(u"ளே", u"@Í")
    translated = translated.replace(u"ளெ", u"öÍ")
    translated = translated.replace(u"ளூ", u"Ñ")
    translated = translated.replace(u"ளு", u"™")
    translated = translated.replace(u"ளீ", u"Ï")
    translated = translated.replace(u"ளி", u"Î")
    translated = translated.replace(u"ளா", u"Íõ")
    translated = translated.replace(u"ள", u"Í")
    
    translated = translated.replace(u"ழ்", u"Ì")
    translated = translated.replace(u"ழௌ", u"öÇÍ")
    translated = translated.replace(u"ழோ", u"@Çõ")
    translated = translated.replace(u"ழொ", u"öÇõ")
    translated = translated.replace(u"ழை", u"øÇ")
    translated = translated.replace(u"ழே", u"@Ç")
    translated = translated.replace(u"ழெ", u"öÇ")
    translated = translated.replace(u"ழூ", u"Ë")
    translated = translated.replace(u"ழு", u"Ê")
    translated = translated.replace(u"ழீ", u"É")
    translated = translated.replace(u"ழி", u"È")
    translated = translated.replace(u"ழா", u"Çõ")
    translated = translated.replace(u"ழ", u"Ç")
    
    translated = translated.replace(u"வ்", u"Æ")
    translated = translated.replace(u"வௌ", u"öÁÍ")
    translated = translated.replace(u"வோ", u"@Áõ")
    translated = translated.replace(u"வொ", u"öÁõ")
    translated = translated.replace(u"வை", u"øÁ")
    translated = translated.replace(u"வே", u"@Á")
    translated = translated.replace(u"வெ", u"öÁ")
    translated = translated.replace(u"வூ", u"Å")
    translated = translated.replace(u"வு", u"Ä")
    translated = translated.replace(u"வீ", u"Ã")
    translated = translated.replace(u"வி", u"Â")
    translated = translated.replace(u"வா", u"Áõ")
    translated = translated.replace(u"வ", u"Á")
    
    translated = translated.replace(u"ஷ்", u"è")
    translated = translated.replace(u"ஷௌ", u"öåÍ")
    translated = translated.replace(u"ஷோ", u"@åõ")
    translated = translated.replace(u"ஷொ", u"öåõ")
    translated = translated.replace(u"ஷை", u"øå")
    translated = translated.replace(u"ஷே", u"@å")
    translated = translated.replace(u"ஷெ", u"öå")
    translated = translated.replace(u"ஷூ", u"å„")
    translated = translated.replace(u"ஷு", u"åû")
    translated = translated.replace(u"ஷீ", u"ç")
    translated = translated.replace(u"ஷி", u"æ")
    translated = translated.replace(u"ஷா", u"åõ")
    translated = translated.replace(u"ஷ", u"å")
    
    translated = translated.replace(u"ஸ்", u"ì")
    translated = translated.replace(u"ஸௌ", u"öéÍ")
    translated = translated.replace(u"ஸோ", u"@éõ")
    translated = translated.replace(u"ஸொ", u"öéõ")
    translated = translated.replace(u"ஸை", u"øé")
    translated = translated.replace(u"ஸே", u"@é")
    translated = translated.replace(u"ஸெ", u"öé")
    translated = translated.replace(u"ஸூ", u"é„")
    translated = translated.replace(u"ஸு", u"éú")
    translated = translated.replace(u"ஸீ", u"ë")
    translated = translated.replace(u"ஸி", u"ê")
    translated = translated.replace(u"ஸா", u"éõ")
    translated = translated.replace(u"ஸ", u"é")
    
    translated = translated.replace(u"ஹ்", u"à")
    translated = translated.replace(u"ஹௌ", u"öíÍ")
    translated = translated.replace(u"ஹோ", u"@íõ")
    translated = translated.replace(u"ஹொ", u"öíõ")
    translated = translated.replace(u"ஹை", u"øí")
    translated = translated.replace(u"ஹே", u"@í")
    translated = translated.replace(u"ஹெ", u"öí")
    translated = translated.replace(u"ஹீ", u"ï")
    translated = translated.replace(u"ஹி", u"î")
    translated = translated.replace(u"ஹா", u"ஹா")
    translated = translated.replace(u"ஹ", u"ஹ")

    translated = translated.replace(u"க்ஷ்", u"க்ஷ்")
    translated = translated.replace(u"க்ஷௌ", u"க்ஷௌ")
    translated = translated.replace(u"க்ஷோ", u"க்ஷோ")
    translated = translated.replace(u"க்ஷொ", u"க்ஷொ")
    translated = translated.replace(u"க்ஷை", u"க்ஷை")
    translated = translated.replace(u"க்ஷே", u"க்ஷே")
    translated = translated.replace(u"க்ஷெ", u"க்ஷெ")
    translated = translated.replace(u"க்ஷூ", u"க்ஷூ")
    translated = translated.replace(u"க்ஷு", u"க்ஷு")
    translated = translated.replace(u"க்ஷீ", u"க்ஷீ")
    translated = translated.replace(u"க்ஷி", u"க்ஷி")
    translated = translated.replace(u"க்ஷா", u"க்ஷா")
    translated = translated.replace(u"க்ஷ", u"க்ஷ")
    
    unconverted = [i for i in translated if i in source_text and not i in
                    punctuation+whitespace+digits]
    translated_trimed = ''.join([i for i in translated if not i in unconverted])

    if debug:
        return ''.join(unconverted)
    elif filtered:
        return translated_trimed
    else:
        return translated