# -*- coding: utf-8 -*-
from string import punctuation, whitespace, digits


def convertToindica(source_text, filtered=False, debug=False):
    translated = source_text
    # Independent Vowels
    translated = translated.replace(u"அ", u"∂")
    translated = translated.replace(u"ஆ", u"g")
    translated = translated.replace(u"இ", u"÷")
    translated = translated.replace(u"ஈ", u"~")
    translated = translated.replace(u"உ", u"c")
    translated = translated.replace(u"ஊ", u"ª")
    translated = translated.replace(u"எ", u"®")
    translated = translated.replace(u"ஏ", u"∞")
    translated = translated.replace(u"ஐ", u"n")
    translated = translated.replace(u"ஒ", u"Œ")
    translated = translated.replace(u"ஓ", u"{")
    translated = translated.replace(u"ஔ", u"¡")
    translated = translated.replace(u"ஃ", u"‡")
    translated = translated.replace(u"ௐ", u"{D")
    translated = translated.replace(u"ஸ்ரீ", u"p")

    # க Family
    translated = translated.replace(u"க்", u"¬")
    translated = translated.replace(u"கௌ", u"ÿÔe")
    translated = translated.replace(u"கோ", u"ºÔV")
    translated = translated.replace(u"கொ", u"ÿÔV")
    translated = translated.replace(u"கை", u"ÁÔ")
    translated = translated.replace(u"கே", u"ºÔ")
    translated = translated.replace(u"கெ", u"ÿÔ")
    translated = translated.replace(u"கூ", u"Ì")
    translated = translated.replace(u"கு", u"z")
    translated = translated.replace(u"கீ", u"ˇ")
    translated = translated.replace(u"கி", u"˛")
    translated = translated.replace(u"கா", u"ÔV")
    translated = translated.replace(u"க", u"Ô")

    # ங Family
    translated = translated.replace(u"ங்", u"∫")
    translated = translated.replace(u"ஙௌ", u"ÿÙe")
    translated = translated.replace(u"ஙோ", u"ºÙV")
    translated = translated.replace(u"ஙொ", u"ÿÙV")
    translated = translated.replace(u"ஙை", u"ÁÙ")
    translated = translated.replace(u"ஙே", u"ºÙ")
    translated = translated.replace(u"ஙெ", u"ÿÙ")
    #translated = translated.replace(u"ஙூ", u"")
    #translated = translated.replace(u"ஙு", u"")
    #translated = translated.replace(u"ஙீ", u"")
    #translated = translated.replace(u"ஙி", u"")
    translated = translated.replace(u"ஙா", u"ÙV")
    translated = translated.replace(u"ங", u"Ù")

    # ச Family
    translated = translated.replace(u"ச்", u"á")
    translated = translated.replace(u"சௌ", u"ÿƒe")
    translated = translated.replace(u"சோ", u"ºƒV")
    translated = translated.replace(u"சொ", u"ÿƒV")
    translated = translated.replace(u"சை", u"Áƒ")
    translated = translated.replace(u"சே", u"ºƒ")
    translated = translated.replace(u"செ", u"ÿƒ")
    translated = translated.replace(u"சூ", u"Û")
    translated = translated.replace(u"சு", u"à")
    translated = translated.replace(u"சீ", u"Ê")
    translated = translated.replace(u"சி", u"E")
    translated = translated.replace(u"சா", u"ƒV")
    translated = translated.replace(u"ச", u"ƒ")

    # ஜ Family
    translated = translated.replace(u"ஜ்", u"Î")
    translated = translated.replace(u"ஜௌ", u"ÿÖe")
    translated = translated.replace(u"ஜோ", u"ºÖV")
    translated = translated.replace(u"ஜொ", u"ÿÖV")
    translated = translated.replace(u"ஜை", u"ÁÖ")
    translated = translated.replace(u"ஜே", u"ºÖ")
    translated = translated.replace(u"ஜெ", u"ÿÖ")
    translated = translated.replace(u"ஜூ", u"…")
    translated = translated.replace(u"ஜு", u"h")
    translated = translated.replace(u"ஜீ", u"ä")
    translated = translated.replace(u"ஜி", u"˜")
    translated = translated.replace(u"ஜா", u"ÖV")
    translated = translated.replace(u"ஜ", u"Ö")

    # ஞ Family
    translated = translated.replace(u"ஞ்", u"â")
    translated = translated.replace(u"ஞௌ", u"ÿQe")
    translated = translated.replace(u"ஞோ", u"ºQV")
    translated = translated.replace(u"ஞொ", u"ÿQV")
    translated = translated.replace(u"ஞை", u"ÁQ")
    translated = translated.replace(u"ஞே", u"ºQ")
    translated = translated.replace(u"ஞெ", u"ÿQ")
    #translated = translated.replace(u"ஞூ", u"")
    #translated = translated.replace(u"ஞு", u"")
    #translated = translated.replace(u"ஞீ", u"")
    #translated = translated.replace(u"ஞி", u"")
    translated = translated.replace(u"ஞா", u"QV")
    translated = translated.replace(u"ஞ", u"Q")

    # ட Family
    translated = translated.replace(u"ட்", u"‚")
    translated = translated.replace(u"டௌ", u"ÿ¶e")
    translated = translated.replace(u"டோ", u"º¶V")
    translated = translated.replace(u"டொ", u"ÿ¶V")
    translated = translated.replace(u"டை", u"Á¶")
    translated = translated.replace(u"டே", u"º¶")
    translated = translated.replace(u"டெ", u"ÿ¶")
    translated = translated.replace(u"டூ", u"˘")
    translated = translated.replace(u"டு", u"|")
    translated = translated.replace(u"டீ", u"œ")
    translated = translated.replace(u"டி", u"É")
    translated = translated.replace(u"டா", u"¶V")
    translated = translated.replace(u"ட", u"¶")

    # ண Family
    translated = translated.replace(u"ண்", u"ı")
    translated = translated.replace(u"ணௌ", u"ÿÜe")
    translated = translated.replace(u"ணோ", u"ºÜV")
    translated = translated.replace(u"ணொ", u"ÿÜV")
    translated = translated.replace(u"ணை", u"ÁÜ")
    translated = translated.replace(u"ணே", u"ºÜ")
    translated = translated.replace(u"ணெ", u"ÿÜ")
    translated = translated.replace(u"ணூ", u"I")
    translated = translated.replace(u"ணு", u"Ó")
    translated = translated.replace(u"ணீ", u"ß")
    translated = translated.replace(u"ணி", u"Ë")
    translated = translated.replace(u"ணா", u"ÜV")
    translated = translated.replace(u"ண", u"Ü")

    # த Family
    translated = translated.replace(u"த்", u"›")
    translated = translated.replace(u"தௌ", u"ÿ>e")
    translated = translated.replace(u"தோ", u"º>V")
    translated = translated.replace(u"தொ", u"ÿ>V")
    translated = translated.replace(u"தை", u"Á>")
    translated = translated.replace(u"தே", u"º>")
    translated = translated.replace(u"தெ", u"ÿ>")
    translated = translated.replace(u"தூ", u"#")
    translated = translated.replace(u"து", u"m")
    translated = translated.replace(u"தீ", u"y")
    translated = translated.replace(u"தி", u"]")
    translated = translated.replace(u"தா", u">V")
    translated = translated.replace(u"த", u">")

    # ந Family
    translated = translated.replace(u"ந்", u"Õ")
    translated = translated.replace(u"நௌ", u"ÿÂe")
    translated = translated.replace(u"நோ", u"ºÂV")
    translated = translated.replace(u"நொ", u"ÿÂV")
    translated = translated.replace(u"நை", u"ÁÂ")
    translated = translated.replace(u"நே", u"ºÂ")
    translated = translated.replace(u"நெ", u"ÿÂ")
    translated = translated.replace(u"நூ", u"±")
    translated = translated.replace(u"நு", u"O")
    translated = translated.replace(u"நீ", u"¿")
    translated = translated.replace(u"நி", u"W")
    translated = translated.replace(u"நா", u"ÂV")
    translated = translated.replace(u"ந", u"Â")

    # ன Family
    translated = translated.replace(u"ன்", u"[")
    translated = translated.replace(u"னௌ", u"ÿ™e")
    translated = translated.replace(u"னோ", u"º™V")
    translated = translated.replace(u"னொ", u"ÿ™V")
    translated = translated.replace(u"னை", u"Á™")
    translated = translated.replace(u"னே", u"º™")
    translated = translated.replace(u"னெ", u"ÿ™")
    translated = translated.replace(u"னூ", u"˚")
    translated = translated.replace(u"னு", u"–")
    translated = translated.replace(u"னீ", u"Ã")
    translated = translated.replace(u"னி", u"M")
    translated = translated.replace(u"னா", u"™V")
    translated = translated.replace(u"ன", u"™")

    # ப Family
    translated = translated.replace(u"ப்", u"©")
    translated = translated.replace(u"பௌ", u"ÿ√e")
    translated = translated.replace(u"போ", u"º√V")
    translated = translated.replace(u"பொ", u"ÿ√V")
    translated = translated.replace(u"பை", u"Á√")
    translated = translated.replace(u"பே", u"º√")
    translated = translated.replace(u"பெ", u"ÿ√")
    translated = translated.replace(u"பூ", u"Ø")
    translated = translated.replace(u"பு", u"A")
    translated = translated.replace(u"பீ", u"¨")
    translated = translated.replace(u"பி", u"∏")
    translated = translated.replace(u"பா", u"√V")
    translated = translated.replace(u"ப", u"√")

    # ம Family
    translated = translated.replace(u"ம்", u"D")
    translated = translated.replace(u"மௌ", u"ÿ\\e")
    translated = translated.replace(u"மோ", u"º\\V")
    translated = translated.replace(u"மொ", u"ÿ\\V")
    translated = translated.replace(u"மை", u"Á\\")
    translated = translated.replace(u"மே", u"º\\")
    translated = translated.replace(u"மெ", u"ÿ\\")
    translated = translated.replace(u"மூ", u"J")
    translated = translated.replace(u"மு", u"x")
    translated = translated.replace(u"மீ", u"*")
    translated = translated.replace(u"மி", u"t")
    translated = translated.replace(u"மா", u"\\V")
    translated = translated.replace(u"ம", u"\\")

    # ய Family
    translated = translated.replace(u"ய்", u"F")
    translated = translated.replace(u"யௌ", u"ÿBe")
    translated = translated.replace(u"யோ", u"ºBV")
    translated = translated.replace(u"யொ", u"ÿBV")
    translated = translated.replace(u"யை", u"ÁB")
    translated = translated.replace(u"யே", u"ºB")
    translated = translated.replace(u"யெ", u"ÿB")
    translated = translated.replace(u"யூ", u"R")
    translated = translated.replace(u"யு", u"•")
    translated = translated.replace(u"யீ", u"X")
    translated = translated.replace(u"யி", u"l")
    translated = translated.replace(u"யா", u"BV")
    translated = translated.replace(u"ய", u"B")

    # ர Family
    translated = translated.replace(u"ர்", u"Ï")
    translated = translated.replace(u"ரௌ", u"ÿ´e")
    translated = translated.replace(u"ரோ", u"º´V")
    translated = translated.replace(u"ரொ", u"ÿ´V")
    translated = translated.replace(u"ரை", u"Á´")
    translated = translated.replace(u"ரே", u"º´")
    translated = translated.replace(u"ரெ", u"ÿ´")
    translated = translated.replace(u"ரூ", u"‘")
    translated = translated.replace(u"ரு", u"Ú")
    translated = translated.replace(u"ரீ", u"Z")
    translated = translated.replace(u"ரி", u"ˆ")
    translated = translated.replace(u"ரா", u"´V")
    translated = translated.replace(u"ர", u"´")

    # ற Family
    translated = translated.replace(u"ற்", u"u")
    translated = translated.replace(u"றௌ", u"ÿ≈e")
    translated = translated.replace(u"றோ", u"º≈V")
    translated = translated.replace(u"றொ", u"ÿ≈V")
    translated = translated.replace(u"றை", u"Á≈")
    translated = translated.replace(u"றே", u"º≈")
    translated = translated.replace(u"ரெ", u"ÿ≈")
    translated = translated.replace(u"றூ", u"G")
    translated = translated.replace(u"று", u"Æ")
    translated = translated.replace(u"றீ", u"S")
    translated = translated.replace(u"றி", u"§")
    translated = translated.replace(u"றா", u"≈V")
    translated = translated.replace(u"ற", u"≈")

    # ல Family
    translated = translated.replace(u"ல்", u"_")
    translated = translated.replace(u"லௌ", u"ÿÈe")
    translated = translated.replace(u"லோ", u"ºÈV")
    translated = translated.replace(u"லொ", u"ÿÈV")
    translated = translated.replace(u"லை", u"ÁÈ")
    translated = translated.replace(u"லே", u"ºÈ")
    translated = translated.replace(u"லெ", u"ÿÈ")
    translated = translated.replace(u"லூ", u"Ÿ")
    translated = translated.replace(u"லு", u"K")
    translated = translated.replace(u"லீ", u"‹")
    translated = translated.replace(u"லி", u"o")
    translated = translated.replace(u"லா", u"ÈV")
    translated = translated.replace(u"ல", u"È")

    # ள Family
    translated = translated.replace(u"ள்", u"^")
    translated = translated.replace(u"ளௌ", u"ÿee")
    translated = translated.replace(u"ளோ", u"ºeV")
    translated = translated.replace(u"ளொ", u"ÿeV")
    translated = translated.replace(u"ளை", u"Áe")
    translated = translated.replace(u"ளே", u"ºe")
    translated = translated.replace(u"ளெ", u"ÿe")
    translated = translated.replace(u"ளூ", u"j")
    translated = translated.replace(u"ளு", u"”")
    translated = translated.replace(u"ளீ", u"C")
    translated = translated.replace(u"ளி", u"Ñ")
    translated = translated.replace(u"ளா", u"eV")
    translated = translated.replace(u"ள", u"e")

    # ழ Family
    translated = translated.replace(u"ழ்", u"µ")
    translated = translated.replace(u"ழௌ", u"ÿwe")
    translated = translated.replace(u"ழோ", u"ºwV")
    translated = translated.replace(u"ழொ", u"ÿwV")
    translated = translated.replace(u"ழை", u"Áw")
    translated = translated.replace(u"ழே", u"ºw")
    translated = translated.replace(u"ழெ", u"ÿw")
    translated = translated.replace(u"ழூ", u"Ò")
    translated = translated.replace(u"ழு", u"ø")
    translated = translated.replace(u"ழீ", u"—")
    translated = translated.replace(u"ழி", u"a")
    translated = translated.replace(u"ழா", u"wV")
    translated = translated.replace(u"ழ", u"w")

    # வ Family
    translated = translated.replace(u"வ்", u"À")
    translated = translated.replace(u"வௌ", u"ÿke")
    translated = translated.replace(u"வோ", u"ºkV")
    translated = translated.replace(u"வொ", u"ÿkV")
    translated = translated.replace(u"வை", u"Ák")
    translated = translated.replace(u"வே", u"ºk")
    translated = translated.replace(u"வெ", u"ÿk")
    translated = translated.replace(u"வூ", u"∆")
    translated = translated.replace(u"வு", u"°")
    translated = translated.replace(u"வீ", u"T")
    translated = translated.replace(u"வி", u"s")
    translated = translated.replace(u"வா", u"kV")
    translated = translated.replace(u"வ", u"k")

    # ஷ Family
    translated = translated.replace(u"ஷ்", u"i")
    translated = translated.replace(u"ஷௌ", u"ÿ≠e")
    translated = translated.replace(u"ஷோ", u"º≠V")
    translated = translated.replace(u"ஷொ", u"ÿ≠V")
    translated = translated.replace(u"ஷை", u"Á≠")
    translated = translated.replace(u"ஷே", u"º≠")
    translated = translated.replace(u"ஷெ", u"ÿ≠")
    translated = translated.replace(u"ஷூ", u"£")
    translated = translated.replace(u"ஷு", u"◊")
    translated = translated.replace(u"ஷீ", u"U")
    translated = translated.replace(u"ஷி", u"¥")
    translated = translated.replace(u"ஷா", u"≠V")
    translated = translated.replace(u"ஷ", u"≠")

    # ஸ Family
    translated = translated.replace(u"ஸ்", u"¸")
    translated = translated.replace(u"ஸௌ", u"ÿve")
    translated = translated.replace(u"ஸோ", u"ºvV")
    translated = translated.replace(u"ஸொ", u"ÿvV")
    translated = translated.replace(u"ஸை", u"Áv")
    translated = translated.replace(u"ஸே", u"ºv")
    translated = translated.replace(u"ஸெ", u"ÿv")
    translated = translated.replace(u"ஸூ", u"`")
    translated = translated.replace(u"ஸு", u"q")
    translated = translated.replace(u"ஸீ", u"¢")
    translated = translated.replace(u"ஸி", u"L")
    translated = translated.replace(u"ஸா", u"vV")
    translated = translated.replace(u"ஸ", u"v")

    # ஹ Family
    translated = translated.replace(u"ஹ்", u"„")
    translated = translated.replace(u"ஹௌ", u"ÿ«e")
    translated = translated.replace(u"ஹோ", u"º«V")
    translated = translated.replace(u"ஹொ", u"ÿ«V")
    translated = translated.replace(u"ஹை", u"Á«")
    translated = translated.replace(u"ஹே", u"º«")
    translated = translated.replace(u"ஹெ", u"ÿ«")
    translated = translated.replace(u"ஹீ", u"Í")
    translated = translated.replace(u"ஹி", u"N")
    translated = translated.replace(u"ஹா", u"«V")
    translated = translated.replace(u"ஹ", u"«")

    # க்ஷ Family
    translated = translated.replace(u"க்ஷ்", u"’")
    translated = translated.replace(u"க்ஷௌ", u"ÿ≥e")
    translated = translated.replace(u"க்ஷோ", u"º≥V")
    translated = translated.replace(u"க்ஷொ", u"ÿ≥V")
    translated = translated.replace(u"க்ஷை", u"Á≥")
    translated = translated.replace(u"க்ஷே", u"º≥")
    translated = translated.replace(u"க்ஷெ", u"ÿ≥")
    translated = translated.replace(u"க்ஷூ", u"f")
    translated = translated.replace(u"க்ஷு", u"Y")
    translated = translated.replace(u"க்ஷீ", u"»")
    translated = translated.replace(u"க்ஷி", u"H")
    translated = translated.replace(u"க்ஷா", u"≥V")
    translated = translated.replace(u"க்ஷ", u"≥")

    unconverted = [i for i in translated if i in source_text and not i in
                    punctuation+whitespace+digits]
    translated_trimed = ''.join([i for i in translated if not i in unconverted])

    if debug:
        return unconverted
    elif filtered:
        return translated_trimed
    else:
        return translated

