# -*- coding: utf-8 -*-
from string import punctuation, whitespace, digits


def convertTotscii(source_text, filtered=False, debug=False):
    translated = source_text
    # Independent Vowels
    translated = translated.replace(u"அ", u"«")
    translated = translated.replace(u"ஆ", u"¬")
    translated = translated.replace(u"இ", u"­")
    translated = translated.replace(u"ஈ", u"®")
    translated = translated.replace(u"உ", u"¯")
    translated = translated.replace(u"ஊ", u"°")
    translated = translated.replace(u"எ", u"±")
    translated = translated.replace(u"ஏ", u"²")
    translated = translated.replace(u"ஐ", u"³")
    translated = translated.replace(u"ஒ", u"´")
    translated = translated.replace(u"ஓ", u"µ")
    translated = translated.replace(u"ஔ", u"¶")
    translated = translated.replace(u"ஃ", u"∙")

    # க Family
    translated = translated.replace(u"க்", u"ì")
    translated = translated.replace(u"கௌ", u"¦¸ª")
    translated = translated.replace(u"கோ", u"§¸¡")
    translated = translated.replace(u"கொ", u"¦¸¡")
    translated = translated.replace(u"கை", u"¨¸")
    translated = translated.replace(u"கே", u"§¸")
    translated = translated.replace(u"கெ", u"¦¸")
    translated = translated.replace(u"கூ", u"Ü")
    translated = translated.replace(u"கு", u"Ì")
    translated = translated.replace(u"கீ", u"¸£")
    translated = translated.replace(u"கி", u"¸¢")
    translated = translated.replace(u"கா", u"¸¡")
    translated = translated.replace(u"க", u"¸")

    # ங Family
    translated = translated.replace(u"ங்", u"í")
    translated = translated.replace(u"ஙௌ", u"¦¹ª")
    translated = translated.replace(u"ஙோ", u"§¹¡")
    translated = translated.replace(u"ஙொ", u"¦¹¡")
    translated = translated.replace(u"ஙை", u"¨¹")
    translated = translated.replace(u"ஙே", u"§¹")
    translated = translated.replace(u"ஙெ", u"¦¹")
    translated = translated.replace(u"ஙூ", u"›")
    translated = translated.replace(u"ஙு", u"™")
    translated = translated.replace(u"ஙீ", u"¹£")
    translated = translated.replace(u"ஙி", u"¹¢")
    translated = translated.replace(u"ஙா", u"¹¡")
    translated = translated.replace(u"ங", u"¹")

    # ச Family
    translated = translated.replace(u"ச்", u"î")
    translated = translated.replace(u"சௌ", u"¦ºª")
    translated = translated.replace(u"சோ", u"§º¡")
    translated = translated.replace(u"சொ", u"¦º¡")
    translated = translated.replace(u"சை", u"¨º")
    translated = translated.replace(u"சே", u"§º")
    translated = translated.replace(u"செ", u"¦º")
    translated = translated.replace(u"சூ", u"Ý")
    translated = translated.replace(u"சு", u"Í")
    translated = translated.replace(u"சீ", u"º£")
    translated = translated.replace(u"சி", u"º¢")
    translated = translated.replace(u"சா", u"º¡")
    translated = translated.replace(u"ச", u"º")

    # ஜ Family
    translated = translated.replace(u"ஜ்", u"ˆ")
    translated = translated.replace(u"ஜௌ", u"¦ƒª")
    translated = translated.replace(u"ஜோ", u"§ƒ¡")
    translated = translated.replace(u"ஜொ", u"¦ƒ¡")
    translated = translated.replace(u"ஜை", u"¨ƒ")
    translated = translated.replace(u"ஜே", u"§ƒ")
    translated = translated.replace(u"ஜெ", u"¦ƒ")
    translated = translated.replace(u"ஜூ", u"ƒ¥")
    translated = translated.replace(u"ஜு", u"ƒ¤")
    translated = translated.replace(u"ஜீ", u"ƒ£")
    translated = translated.replace(u"ஜி", u"ƒ¢")
    translated = translated.replace(u"ஜா", u"ƒ¡")
    translated = translated.replace(u"ஜ", u"ƒ")

    # ஞ Family
    translated = translated.replace(u"ஞ்", u"ï")
    translated = translated.replace(u"ஞௌ", u"¦»ª")
    translated = translated.replace(u"ஞோ", u"§»¡")
    translated = translated.replace(u"ஞொ", u"¦»¡")
    translated = translated.replace(u"ஞை", u"¨»")
    translated = translated.replace(u"ஞே", u"§»")
    translated = translated.replace(u"ஞெ", u"¦»")
    translated = translated.replace(u"ஞூ", u"œ")
    translated = translated.replace(u"ஞு", u"")
    translated = translated.replace(u"ஞீ", u"»£")
    translated = translated.replace(u"ஞி", u"»¢")
    translated = translated.replace(u"ஞா", u"»¡")
    translated = translated.replace(u"ஞ", u"»")

    # ட Family
    translated = translated.replace(u"ட்", u"ð")
    translated = translated.replace(u"டௌ", u"¦¼ª")
    translated = translated.replace(u"டோ", u"§¼¡")
    translated = translated.replace(u"டொ", u"¦¼¡")
    translated = translated.replace(u"டை", u"¨¼")
    translated = translated.replace(u"டே", u"§¼")
    translated = translated.replace(u"டெ", u"¦¼")
    translated = translated.replace(u"டூ", u"Þ")
    translated = translated.replace(u"டு", u"Î")
    translated = translated.replace(u"டீ", u"Ë")
    translated = translated.replace(u"டி", u"Ê")
    translated = translated.replace(u"டா", u"¼¡")
    translated = translated.replace(u"ட", u"¼")

    # ண Family
    translated = translated.replace(u"ண்", u"ñ")
    translated = translated.replace(u"ணௌ", u"¦½ª")
    translated = translated.replace(u"ணோ", u"§½¡")
    translated = translated.replace(u"ணொ", u"¦½¡")
    translated = translated.replace(u"ணை", u"¨½")
    translated = translated.replace(u"ணே", u"§½")
    translated = translated.replace(u"ணெ", u"¦½")
    translated = translated.replace(u"ணூ", u"ß")
    translated = translated.replace(u"ணு", u"Ï")
    translated = translated.replace(u"ணீ", u"½£")
    translated = translated.replace(u"ணி", u"½¢")
    translated = translated.replace(u"ணா", u"½¡")
    translated = translated.replace(u"ண", u"½")

    # த Family
    translated = translated.replace(u"த்", u"ò")
    translated = translated.replace(u"தௌ", u"¦¾ª")
    translated = translated.replace(u"தோ", u"§¾¡")
    translated = translated.replace(u"தொ", u"¦¾¡")
    translated = translated.replace(u"தை", u"¨¾")
    translated = translated.replace(u"தே", u"§¾")
    translated = translated.replace(u"தெ", u"¦¾")
    translated = translated.replace(u"தூ", u"à")
    translated = translated.replace(u"து", u"Ð")
    translated = translated.replace(u"தீ", u"¾£")
    translated = translated.replace(u"தி", u"¾¢")
    translated = translated.replace(u"தா", u"¾¡")
    translated = translated.replace(u"த", u"¾")

    # ந Family
    translated = translated.replace(u"ந்", u"ó")
    translated = translated.replace(u"நௌ", u"¦¿ª")
    translated = translated.replace(u"நோ", u"§¿¡")
    translated = translated.replace(u"நொ", u"¦¿¡")
    translated = translated.replace(u"நை", u"¨¿")
    translated = translated.replace(u"நே", u"§¿")
    translated = translated.replace(u"நெ", u"¦¿")
    translated = translated.replace(u"நூ", u"á")
    translated = translated.replace(u"நு", u"Ñ")
    translated = translated.replace(u"நீ", u"¿£")
    translated = translated.replace(u"நி", u"¿¢")
    translated = translated.replace(u"நா", u"¿¡")
    translated = translated.replace(u"ந", u"¿")

    # ன Family
    translated = translated.replace(u"ன்", u"ý")
    translated = translated.replace(u"னௌ", u"¦Éª")
    translated = translated.replace(u"னோ", u"§É¡")
    translated = translated.replace(u"னொ", u"¦É¡")
    translated = translated.replace(u"னை", u"¨É")
    translated = translated.replace(u"னே", u"§É")
    translated = translated.replace(u"னெ", u"¦É")
    translated = translated.replace(u"னூ", u"ë")
    translated = translated.replace(u"னு", u"Û")
    translated = translated.replace(u"னீ", u"É£")
    translated = translated.replace(u"னி", u"É¢")
    translated = translated.replace(u"னா", u"É¡")
    translated = translated.replace(u"ன", u"É")

    # ப Family
    translated = translated.replace(u"ப்", u"ô")
    translated = translated.replace(u"பௌ", u"¦Àª")
    translated = translated.replace(u"போ", u"§À¡")
    translated = translated.replace(u"பொ", u"¦À¡")
    translated = translated.replace(u"பை", u"¨À")
    translated = translated.replace(u"பே", u"§À")
    translated = translated.replace(u"பெ", u"¦À")
    translated = translated.replace(u"பூ", u"â")
    translated = translated.replace(u"பு", u"Ò")
    translated = translated.replace(u"பீ", u"À£")
    translated = translated.replace(u"பி", u"À¢")
    translated = translated.replace(u"பா", u"À¡")
    translated = translated.replace(u"ப", u"À")

    # ம Family
    translated = translated.replace(u"ம்", u"õ")
    translated = translated.replace(u"மௌ", u"¦Áª")
    translated = translated.replace(u"மோ", u"§Á¡")
    translated = translated.replace(u"மொ", u"¦Á¡")
    translated = translated.replace(u"மை", u"¨Á")
    translated = translated.replace(u"மே", u"§Á")
    translated = translated.replace(u"மெ", u"¦Á")
    translated = translated.replace(u"மூ", u"ã")
    translated = translated.replace(u"மு", u"Ó")
    translated = translated.replace(u"மீ", u"Á£")
    translated = translated.replace(u"மி", u"Á¢")
    translated = translated.replace(u"மா", u"Á¡")
    translated = translated.replace(u"ம", u"Á")

    # ய Family
    translated = translated.replace(u"ய்", u"ö")
    translated = translated.replace(u"யௌ", u"¦Âª")
    translated = translated.replace(u"யோ", u"§Â¡")
    translated = translated.replace(u"யொ", u"¦Â¡")
    translated = translated.replace(u"யை", u"¨Â")
    translated = translated.replace(u"யே", u"§Â")
    translated = translated.replace(u"யெ", u"¦Â")
    translated = translated.replace(u"யூ", u"ä")
    translated = translated.replace(u"யு", u"Ô")
    translated = translated.replace(u"யீ", u"Â£")
    translated = translated.replace(u"யி", u"Â¢")
    translated = translated.replace(u"யா", u"Â¡")
    translated = translated.replace(u"ய", u"Â")

    # ர Family
    translated = translated.replace(u"ர்", u"÷")
    translated = translated.replace(u"ரௌ", u"¦Ãª")
    translated = translated.replace(u"ரோ", u"§Ã¡")
    translated = translated.replace(u"ரொ", u"¦Ã¡")
    translated = translated.replace(u"ரை", u"¨Ã")
    translated = translated.replace(u"ரே", u"§Ã")
    translated = translated.replace(u"ரெ", u"¦Ã")
    translated = translated.replace(u"ரூ", u"å")
    translated = translated.replace(u"ரு", u"Õ")
    translated = translated.replace(u"ரீ", u"Ã£")
    translated = translated.replace(u"ரி", u"Ã¢")
    translated = translated.replace(u"ரா", u"Ã¡")
    translated = translated.replace(u"ர", u"Ã")

    # ற Family
    translated = translated.replace(u"ற்", u"ü")
    translated = translated.replace(u"றௌ", u"¦Èª")
    translated = translated.replace(u"றோ", u"§È¡")
    translated = translated.replace(u"றொ", u"¦È¡")
    translated = translated.replace(u"றை", u"¨È")
    translated = translated.replace(u"றே", u"§È")
    translated = translated.replace(u"ரெ", u"¦Ã")
    translated = translated.replace(u"றூ", u"ê")
    translated = translated.replace(u"று", u"Ú")
    translated = translated.replace(u"றீ", u"È£")
    translated = translated.replace(u"றி", u"È¢")
    translated = translated.replace(u"றா", u"È¡")
    translated = translated.replace(u"ற", u"È")

    # ல Family
    translated = translated.replace(u"ல்", u"ø")
    translated = translated.replace(u"லௌ", u"¦Äª")
    translated = translated.replace(u"லோ", u"§Ä¡")
    translated = translated.replace(u"லொ", u"¦Ä¡")
    translated = translated.replace(u"லை", u"¨Ä")
    translated = translated.replace(u"லே", u"§Ä")
    translated = translated.replace(u"லெ", u"¦Ä")
    translated = translated.replace(u"லூ", u"æ")
    translated = translated.replace(u"லு", u"Ö")
    translated = translated.replace(u"லீ", u"Ä£")
    translated = translated.replace(u"லி", u"Ä¢")
    translated = translated.replace(u"லா", u"Ä¡")
    translated = translated.replace(u"ல", u"Ä")

    # ள Family
    translated = translated.replace(u"ள்", u"û")
    translated = translated.replace(u"ளௌ", u"¦Çª")
    translated = translated.replace(u"ளோ", u"§Ç¡")
    translated = translated.replace(u"ளொ", u"¦Ç¡")
    translated = translated.replace(u"ளை", u"¨Ç")
    translated = translated.replace(u"ளே", u"§Ç")
    translated = translated.replace(u"ளெ", u"¦Ç")
    translated = translated.replace(u"ளூ", u"é")
    translated = translated.replace(u"ளு", u"Ù")
    translated = translated.replace(u"ளீ", u"Ç£")
    translated = translated.replace(u"ளி", u"Ç¢")
    translated = translated.replace(u"ளா", u"Ç¡")
    translated = translated.replace(u"ள", u"Ç")

    # ழ Family
    translated = translated.replace(u"ழ்", u"ú")
    translated = translated.replace(u"ழௌ", u"¦Æª")
    translated = translated.replace(u"ழோ", u"§Æ¡")
    translated = translated.replace(u"ழொ", u"¦Æ¡")
    translated = translated.replace(u"ழை", u"¨Æ")
    translated = translated.replace(u"ழே", u"§Æ")
    translated = translated.replace(u"ழெ", u"¦Æ")
    translated = translated.replace(u"ழூ", u"è")
    translated = translated.replace(u"ழு", u"Ø")
    translated = translated.replace(u"ழீ", u"Æ£")
    translated = translated.replace(u"ழி", u"Æ¢")
    translated = translated.replace(u"ழா", u"Æ¡")
    translated = translated.replace(u"ழ", u"Æ")

    # வ Family
    translated = translated.replace(u"வ்", u"ù")
    translated = translated.replace(u"வௌ", u"¦Åª")
    translated = translated.replace(u"வோ", u"§Å¡")
    translated = translated.replace(u"வொ", u"¦Å¡")
    translated = translated.replace(u"வை", u"¨Å")
    translated = translated.replace(u"வே", u"§Å")
    translated = translated.replace(u"வெ", u"¦Å")
    translated = translated.replace(u"வூ", u"ç")
    translated = translated.replace(u"வு", u"×")
    translated = translated.replace(u"வீ", u"Å£")
    translated = translated.replace(u"வி", u"Å¢")
    translated = translated.replace(u"வா", u"Å¡")
    translated = translated.replace(u"வ", u"Å")

    # ஷ Family
    translated = translated.replace(u"ஷ்", u"‰")
    translated = translated.replace(u"ஷௌ", u"¦„ª")
    translated = translated.replace(u"ஷோ", u"§„¡")
    translated = translated.replace(u"ஷொ", u"¦„¡")
    translated = translated.replace(u"ஷை", u"¨„")
    translated = translated.replace(u"ஷே", u"§„")
    translated = translated.replace(u"ஷெ", u"¦„")
    translated = translated.replace(u"ஷீ", u"„£")
    translated = translated.replace(u"ஷி", u"„¢")
    translated = translated.replace(u"ஷா", u"„¡")
    translated = translated.replace(u"ஷ", u"„")

    # ஸ Family
    translated = translated.replace(u"ஸ்", u"Š")
    translated = translated.replace(u"ஸௌ", u"¦…ª")
    translated = translated.replace(u"ஸோ", u"§…¡")
    translated = translated.replace(u"ஸொ", u"¦…¡")
    translated = translated.replace(u"ஸை", u"¨…")
    translated = translated.replace(u"ஸே", u"§…")
    translated = translated.replace(u"ஸெ", u"¦…")
    translated = translated.replace(u"ஸீ", u"…£")
    translated = translated.replace(u"ஸி", u"…¢")
    translated = translated.replace(u"ஸா", u"…¡")
    translated = translated.replace(u"ஸ", u"…")

    # ஹ Family
    translated = translated.replace(u"ஹ்", u"‹")
    translated = translated.replace(u"ஹௌ", u"¦†ª")
    translated = translated.replace(u"ஹோ", u"§†¡")
    translated = translated.replace(u"ஹொ", u"¦†¡")
    translated = translated.replace(u"ஹை", u"¨†")
    translated = translated.replace(u"ஹே", u"§†")
    translated = translated.replace(u"ஹெ", u"¦†")
    translated = translated.replace(u"ஹீ", u"†£")
    translated = translated.replace(u"ஹி", u"†¢")
    translated = translated.replace(u"ஹா", u"†¡")
    translated = translated.replace(u"ஹ", u"†")

    unconverted = [i for i in translated if i in source_text and not i in
                    punctuation+whitespace+digits]
    translated_trimed = ''.join([i for i in translated if not i in unconverted])

    if debug:
        return unconverted
    elif filtered:
        return translated_trimed
    else:
        return translated