# -*- coding: utf-8 -*-
from string import punctuation, whitespace, digits


def convertTomurasoli(source_text, filtered=False, debug=False):
    translated = source_text
    # Independent Vowels
    translated = translated.replace(u"அ", u"m")
    translated = translated.replace(u"ஆ", u"M")
    translated = translated.replace(u"இ", u"Ï")
    translated = translated.replace(u"ஈ", u"<")
    translated = translated.replace(u"உ", u"c")
    translated = translated.replace(u"ஊ", u"C")
    translated = translated.replace(u"எ", u"v")
    translated = translated.replace(u"ஏ", u"V")
    translated = translated.replace(u"ஐ", u"I")
    translated = translated.replace(u"ஒ", u"x")
    translated = translated.replace(u"ஓ", u"X")
    translated = translated.replace(u"ஔ", u"xs")
    translated = translated.replace(u"ஃ", u"~")

    # க Family
    translated = translated.replace(u"க்", u"¡")
    translated = translated.replace(u"கௌ", u"bfs")
    translated = translated.replace(u"கோ", u"nfh")
    translated = translated.replace(u"கொ", u"bfh")
    translated = translated.replace(u"கை", u"if")
    translated = translated.replace(u"கே", u"nf")
    translated = translated.replace(u"கெ", u"bf")
    translated = translated.replace(u"கூ", u"T")
    translated = translated.replace(u"கு", u"F")
    translated = translated.replace(u"கீ", u"Ñ")
    translated = translated.replace(u"கி", u"»")
    translated = translated.replace(u"கா", u"fh")
    translated = translated.replace(u"க", u"f")

    # ங Family
    translated = translated.replace(u"ங்", u"§")
    translated = translated.replace(u"ஙௌ", u"b‡s")
    translated = translated.replace(u"ஙோ", u"n‡h")
    translated = translated.replace(u"ஙொ", u"b‡h")
    translated = translated.replace(u"ஙை", u"i‡")
    translated = translated.replace(u"ஙே", u"n‡")
    translated = translated.replace(u"ஙெ", u"b‡")
    translated = translated.replace(u"ஙூ", u"½")
    translated = translated.replace(u"ஙு", u"¼")
    translated = translated.replace(u"ஙீ", u"†")
    translated = translated.replace(u"ஙி", u"à")
    translated = translated.replace(u"ஙா", u"‡h")
    translated = translated.replace(u"ங", u"‡")

    # ச Family
    translated = translated.replace(u"ச்", u"¢")
    translated = translated.replace(u"சௌ", u"brs")
    translated = translated.replace(u"சோ", u"nrh")
    translated = translated.replace(u"சொ", u"brh")
    translated = translated.replace(u"சை", u"ir")
    translated = translated.replace(u"சே", u"nr")
    translated = translated.replace(u"செ", u"br")
    translated = translated.replace(u"சூ", u"N")
    translated = translated.replace(u"சு", u"R")
    translated = translated.replace(u"சீ", u"Ó")
    translated = translated.replace(u"சி", u"Á")
    translated = translated.replace(u"சா", u"rh")
    translated = translated.replace(u"ச", u"r")

    # ஜ Family
    translated = translated.replace(u"ஜ்", u"{")
    translated = translated.replace(u"ஜௌ", u"b#s")
    translated = translated.replace(u"ஜோ", u"n#h")
    translated = translated.replace(u"ஜொ", u"b#h")
    translated = translated.replace(u"ஜை", u"i#")
    translated = translated.replace(u"ஜே", u"n#")
    translated = translated.replace(u"ஜெ", u"b#")
    translated = translated.replace(u"ஜூ", u"#]")
    translated = translated.replace(u"ஜு", u"#&")
    translated = translated.replace(u"ஜீ", u"É")
    translated = translated.replace(u"ஜி", u"í")
    translated = translated.replace(u"ஜா", u"#h")
    translated = translated.replace(u"ஜ", u"#")

    # ஞ Family
    translated = translated.replace(u"ஞ்", u"Š")
    translated = translated.replace(u"ஞௌ", u"bPs")
    translated = translated.replace(u"ஞோ", u"nPh")
    translated = translated.replace(u"ஞொ", u"bPh")
    translated = translated.replace(u"ஞை", u"iP")
    translated = translated.replace(u"ஞே", u"nP")
    translated = translated.replace(u"ஞெ", u"bP")
    translated = translated.replace(u"ஞூ", u"ú")
    translated = translated.replace(u"ஞு", u"\|")
    translated = translated.replace(u"ஞீ", u"Ø")
    translated = translated.replace(u"ஞி", u"á")
    translated = translated.replace(u"ஞா", u"Ph")
    translated = translated.replace(u"ஞ", u"P")

    # ட Family
    translated = translated.replace(u"ட்", u"£")
    translated = translated.replace(u"டௌ", u"bls")
    translated = translated.replace(u"டோ", u"nlh")
    translated = translated.replace(u"டொ", u"blh")
    translated = translated.replace(u"டை", u"il")
    translated = translated.replace(u"டே", u"nl")
    translated = translated.replace(u"டெ", u"bl")
    translated = translated.replace(u"டூ", u"\^")
    translated = translated.replace(u"டு", u"L")
    translated = translated.replace(u"டீ", u"O")
    translated = translated.replace(u"டி", u"o")
    translated = translated.replace(u"டா", u"lh")
    translated = translated.replace(u"ட", u"l")

    # ண Family
    translated = translated.replace(u"ண்", u"©")
    translated = translated.replace(u"ணௌ", u"bzs")
    translated = translated.replace(u"ணோ", u"nzh")
    translated = translated.replace(u"ணொ", u"bzh")
    translated = translated.replace(u"ணை", u"iz")
    translated = translated.replace(u"ணே", u"nz")
    translated = translated.replace(u"ணெ", u"bz")
    translated = translated.replace(u"ணூ", u"û")
    translated = translated.replace(u"ணு", u"Q")
    translated = translated.replace(u"ணீ", u"Ù")
    translated = translated.replace(u"ணி", u"â")
    translated = translated.replace(u"ணா", u"zh")
    translated = translated.replace(u"ண", u"z")

    # த Family
    translated = translated.replace(u"த்", u"¤")
    translated = translated.replace(u"தௌ", u"bjs")
    translated = translated.replace(u"தோ", u"njh")
    translated = translated.replace(u"தொ", u"bjh")
    translated = translated.replace(u"தை", u"ij")
    translated = translated.replace(u"தே", u"nj")
    translated = translated.replace(u"தெ", u"bj")
    translated = translated.replace(u"தூ", u"ö")
    translated = translated.replace(u"து", u"J")
    translated = translated.replace(u"தீ", u"Ô")
    translated = translated.replace(u"தி", u"Â")
    translated = translated.replace(u"தா", u"jh")
    translated = translated.replace(u"த", u"j")

    # ந Family
    translated = translated.replace(u"ந்", u"ª")
    translated = translated.replace(u"நௌ", u"bes")
    translated = translated.replace(u"நோ", u"neh")
    translated = translated.replace(u"நொ", u"beh")
    translated = translated.replace(u"நை", u"ie")
    translated = translated.replace(u"நே", u"ne")
    translated = translated.replace(u"நெ", u"be")
    translated = translated.replace(u"நூ", u"ü")
    translated = translated.replace(u"நு", u"E")
    translated = translated.replace(u"நீ", u"Ú")
    translated = translated.replace(u"நி", u"ã")
    translated = translated.replace(u"நா", u"eh")
    translated = translated.replace(u"ந", u"e")

    # ன Family
    translated = translated.replace(u"ன்", u"‹")
    translated = translated.replace(u"னௌ", u"bds")
    translated = translated.replace(u"னோ", u"ndh")
    translated = translated.replace(u"னொ", u"bdh")
    translated = translated.replace(u"னை", u"id")
    translated = translated.replace(u"னே", u"nd")
    translated = translated.replace(u"னெ", u"bd")
    translated = translated.replace(u"னூ", u"}")
    translated = translated.replace(u"னு", u"D")
    translated = translated.replace(u"னீ", u"Ü")
    translated = translated.replace(u"னி", u"å")
    translated = translated.replace(u"னா", u"dh")
    translated = translated.replace(u"ன", u"d")

    # ப Family
    translated = translated.replace(u"ப்", u"¥")
    translated = translated.replace(u"பௌ", u"bgs")
    translated = translated.replace(u"போ", u"ngh")
    translated = translated.replace(u"பொ", u"bgh")
    translated = translated.replace(u"பை", u"ig")
    translated = translated.replace(u"பே", u"ng")
    translated = translated.replace(u"பெ", u"bg")
    translated = translated.replace(u"பூ", u"ó")
    translated = translated.replace(u"பு", u"ò")
    translated = translated.replace(u"பீ", u"Õ")
    translated = translated.replace(u"பி", u"Ã")
    translated = translated.replace(u"பா", u"gh")
    translated = translated.replace(u"ப", u"g")

    # ம Family
    translated = translated.replace(u"ம்", u"«")
    translated = translated.replace(u"மௌ", u"bks")
    translated = translated.replace(u"மோ", u"nkh")
    translated = translated.replace(u"மொ", u"bkh")
    translated = translated.replace(u"மை", u"ik")
    translated = translated.replace(u"மே", u"nk")
    translated = translated.replace(u"மெ", u"bk")
    translated = translated.replace(u"மூ", u"_")
    translated = translated.replace(u"மு", u"K")
    translated = translated.replace(u"மீ", u"Û")
    translated = translated.replace(u"மி", u"ä")
    translated = translated.replace(u"மா", u"kh")
    translated = translated.replace(u"ம", u"k")

    # ய Family
    translated = translated.replace(u"ய்", u"Œ")
    translated = translated.replace(u"யௌ", u"bas")
    translated = translated.replace(u"யோ", u"nah")
    translated = translated.replace(u"யொ", u"bah")
    translated = translated.replace(u"யை", u"ia")
    translated = translated.replace(u"யே", u"na")
    translated = translated.replace(u"யெ", u"ba")
    translated = translated.replace(u"யூ", u"ô")
    translated = translated.replace(u"யு", u"Í")
    translated = translated.replace(u"யீ", u"p")
    translated = translated.replace(u"யி", u"æ")
    translated = translated.replace(u"யா", u"ah")
    translated = translated.replace(u"ய", u"a")

    # ர Family
    translated = translated.replace(u"ர்", u"®")
    translated = translated.replace(u"ரௌ", u"bus")
    translated = translated.replace(u"ரோ", u"nuh")
    translated = translated.replace(u"ரொ", u"buh")
    translated = translated.replace(u"ரை", u"iu")
    translated = translated.replace(u"ரே", u"nu")
    translated = translated.replace(u"ரெ", u"bu")
    translated = translated.replace(u"ரூ", u"%")
    translated = translated.replace(u"ரு", u"U")
    translated = translated.replace(u"ரீ", u"ß")
    translated = translated.replace(u"ரி", u"ç")
    translated = translated.replace(u"ரா", u"uh")
    translated = translated.replace(u"ர", u"u")

    # ற Family
    translated = translated.replace(u"ற்", u"‰")
    translated = translated.replace(u"றௌ", u"bws")
    translated = translated.replace(u"றோ", u"nwh")
    translated = translated.replace(u"றொ", u"bwh")
    translated = translated.replace(u"றை", u"iw")
    translated = translated.replace(u"றே", u"nw")
    translated = translated.replace(u"ரெ", u"bu")
    translated = translated.replace(u"றூ", u"ù")
    translated = translated.replace(u"று", u"W")
    translated = translated.replace(u"றீ", u"Ö")
    translated = translated.replace(u"றி", u"¿")
    translated = translated.replace(u"றா", u"wh")
    translated = translated.replace(u"ற", u"w")

    # ல Family
    translated = translated.replace(u"ல்", u"š")
    translated = translated.replace(u"லௌ", u"bys")
    translated = translated.replace(u"லோ", u"nyh")
    translated = translated.replace(u"லொ", u"byh")
    translated = translated.replace(u"லை", u"iy")
    translated = translated.replace(u"லே", u"ny")
    translated = translated.replace(u"லெ", u"by")
    translated = translated.replace(u"லூ", u"ÿ")
    translated = translated.replace(u"லு", u"Y")
    translated = translated.replace(u"லீ", u"Ä")
    translated = translated.replace(u"லி", u"è")
    translated = translated.replace(u"லா", u"yh")
    translated = translated.replace(u"ல", u"y")

    # ள Family
    translated = translated.replace(u"ள்", u"Ÿ")
    translated = translated.replace(u"ளௌ", u"bss")
    translated = translated.replace(u"ளோ", u"nsh")
    translated = translated.replace(u"ளை", u"is")
    translated = translated.replace(u"ளே", u"ns")
    translated = translated.replace(u"ளெ", u"bs")
    translated = translated.replace(u"ளூ", u"q")
    translated = translated.replace(u"ளு", u"S")
    translated = translated.replace(u"ளீ", u"Ç")
    translated = translated.replace(u"ளி", u"ë")
    translated = translated.replace(u"ளா", u"sh")
    translated = translated.replace(u"ள", u"s")

    # ழ Family
    translated = translated.replace(u"ழ்", u"œ")
    translated = translated.replace(u"ழௌ", u"bHs")
    translated = translated.replace(u"ழோ", u"nHh")
    translated = translated.replace(u"ழொ", u"bHh")
    translated = translated.replace(u"ழை", u"iH")
    translated = translated.replace(u"ழே", u"nH")
    translated = translated.replace(u"ழெ", u"bH")
    translated = translated.replace(u"ழூ", u">")
    translated = translated.replace(u"ழு", u"G")
    translated = translated.replace(u"ழீ", u"Æ")
    translated = translated.replace(u"ழி", u"ê")
    translated = translated.replace(u"ழா", u"Hh")
    translated = translated.replace(u"ழ", u"H")

    # வ Family
    translated = translated.replace(u"வ்", u"›")
    translated = translated.replace(u"வௌ", u"bts")
    translated = translated.replace(u"வோ", u"nth")
    translated = translated.replace(u"வொ", u"bth")
    translated = translated.replace(u"வை", u"it")
    translated = translated.replace(u"வே", u"nt")
    translated = translated.replace(u"வெ", u"bt")
    translated = translated.replace(u"வூ", u"ñ")
    translated = translated.replace(u"வு", u"Î")
    translated = translated.replace(u"வீ", u"Å")
    translated = translated.replace(u"வி", u"é")
    translated = translated.replace(u"வா", u"th")
    translated = translated.replace(u"வ", u"t")

    # ஷ Family
    translated = translated.replace(u"ஷ்", u"Z")
    translated = translated.replace(u"ஷௌ", u"bõs")
    translated = translated.replace(u"ஷோ", u"nõh")
    translated = translated.replace(u"ஷொ", u"bõh")
    translated = translated.replace(u"ஷை", u"iõ")
    translated = translated.replace(u"ஷே", u"nõ")
    translated = translated.replace(u"ஷெ", u"bõ")
    translated = translated.replace(u"ஷீ", u"Ê")
    translated = translated.replace(u"ஷி", u"î")
    translated = translated.replace(u"ஷா", u"õh")
    translated = translated.replace(u"ஷ", u"õ")

    # ஸ Family
    translated = translated.replace(u"ஸ்", u"°")
    translated = translated.replace(u"ஸௌ", u"b\[s")
    translated = translated.replace(u"ஸோ", u"n\[h")
    translated = translated.replace(u"ஸொ", u"b\[h")
    translated = translated.replace(u"ஸை", u"i\[")
    translated = translated.replace(u"ஸே", u"n\[")
    translated = translated.replace(u"ஸெ", u"b\[")
    translated = translated.replace(u"ஸீ", u"È")
    translated = translated.replace(u"ஸி", u"ì")
    translated = translated.replace(u"ஸா", u"\[h")
    translated = translated.replace(u"ஸ", u"\[")

    # ஹ Family
    translated = translated.replace(u"ஹ்", u"À")
    translated = translated.replace(u"ஹௌ", u"bAs")
    translated = translated.replace(u"ஹோ", u"nAh")
    translated = translated.replace(u"ஹொ", u"bAh")
    translated = translated.replace(u"ஹை", u"iA")
    translated = translated.replace(u"ஹே", u"nA")
    translated = translated.replace(u"ஹெ", u"bA")
    translated = translated.replace(u"ஹீ", u"Ë")
    translated = translated.replace(u"ஹி", u"ï")
    translated = translated.replace(u"ஹா", u"Ah")
    translated = translated.replace(u"ஹ", u"A")

    unconverted = [i for i in translated if i in source_text and not i in
                    punctuation+whitespace+digits]
    translated_trimed = ''.join([i for i in translated if not i in unconverted])

    if debug:
        return unconverted
    elif filtered:
        return translated_trimed
    else:
        return translated