# -*- coding: utf-8 -*-
from string import punctuation, whitespace, digits


def convertToanu(source_text, filtered=False, debug=False):
    translated = source_text
    
    translated = translated.replace(u"அ", u"¶")
    translated = translated.replace(u"ஆ", u"g")
    translated = translated.replace(u"இ", u"Ö")
    translated = translated.replace(u"ஈ", u"~")
    translated = translated.replace(u"உ", u"c")
    translated = translated.replace(u"ஊ", u"»")
    translated = translated.replace(u"எ", u"¨")
    translated = translated.replace(u"ஏ", u"°")
    translated = translated.replace(u"ஐ", u"n")
    translated = translated.replace(u"ஒ", u"Î")
    translated = translated.replace(u"ஓ", u"{")
    translated = translated.replace(u"ஔ", u"Îe")
    translated = translated.replace(u"ஃ", u"à")
    translated = translated.replace(u"ௐ", u"{D")
    translated = translated.replace(u"ஸ்ரீ", u"p")
    
    translated = translated.replace(u"க்", u"Â")
    translated = translated.replace(u"கௌ", u"Øïe")
    translated = translated.replace(u"கோ", u"¼ïV")
    translated = translated.replace(u"கொ", u"ØïV")
    translated = translated.replace(u"கை", u"çï")
    translated = translated.replace(u"கே", u"¼ï")
    translated = translated.replace(u"கெ", u"Øï")
    translated = translated.replace(u"கூ", u"í")
    translated = translated.replace(u"கு", u"z")
    translated = translated.replace(u"கீ", u"ÿ")
    translated = translated.replace(u"கி", u"þ")
    translated = translated.replace(u"கா", u"ïV")
    translated = translated.replace(u"க", u"ï")
    
    translated = translated.replace(u"ங்", u"º")
    translated = translated.replace(u"ஙௌ", u"Øôe")
    translated = translated.replace(u"ஙோ", u"¼ôV")
    translated = translated.replace(u"ஙொ", u"ØôV")
    translated = translated.replace(u"ஙை", u"çô")
    translated = translated.replace(u"ஙே", u"¼ô")
    translated = translated.replace(u"ஙெ", u"Øô")
    # translated = translated.replace(u"ஙூ", u"dd")
    # translated = translated.replace(u"ஙு", u"dd")
    # translated = translated.replace(u"ஙீ", u"dd")
    # translated = translated.replace(u"ஙி", u"dd")
    translated = translated.replace(u"ஙா", u"ôV")
    translated = translated.replace(u"ங", u"ô")
    
    translated = translated.replace(u"ச்", u"ß")
    translated = translated.replace(u"சௌ", u"ØÄe")
    translated = translated.replace(u"சோ", u"¼ÄV")
    translated = translated.replace(u"சொ", u"ØÄV")
    translated = translated.replace(u"சை", u"çÄ")
    translated = translated.replace(u"சே", u"¼Ä")
    translated = translated.replace(u"செ", u"ØÄ")
    translated = translated.replace(u"சூ", u"ó")
    translated = translated.replace(u"சு", u"·")
    translated = translated.replace(u"சீ", u"æ")
    translated = translated.replace(u"சி", u"E")
    translated = translated.replace(u"சா", u"ÄV")
    translated = translated.replace(u"ச", u"Ä")
    
    translated = translated.replace(u"ஜ்", u"ë")
    translated = translated.replace(u"ஜௌ", u"ØÛe")
    translated = translated.replace(u"ஜோ", u"¼ÛV")
    translated = translated.replace(u"ஜொ", u"ØÛV")
    translated = translated.replace(u"ஜை", u"çÛ")
    translated = translated.replace(u"ஜே", u"¼Û")
    translated = translated.replace(u"ஜெ", u"ØÛ")
    translated = translated.replace(u"ஜூ", u"É")
    translated = translated.replace(u"ஜு", u"h")
    translated = translated.replace(u"ஜீ", u"ý")
    translated = translated.replace(u"ஜி", u"÷")
    translated = translated.replace(u"ஜா", u"ÛV")
    translated = translated.replace(u"ஜ", u"Û")
    
    translated = translated.replace(u"ஞ்", u"Þ")
    translated = translated.replace(u"ஞௌ", u"ØQe")
    translated = translated.replace(u"ஞோ", u"¼QV")
    translated = translated.replace(u"ஞொ", u"ØQV")
    translated = translated.replace(u"ஞை", u"çQ")
    translated = translated.replace(u"ஞே", u"¼Q")
    translated = translated.replace(u"ஞெ", u"ØQ")
    # translated = translated.replace(u"ஞூ", u"dd")
    # translated = translated.replace(u"ஞு", u"dd")
    # translated = translated.replace(u"ஞீ", u"dd")
    # translated = translated.replace(u"ஞி", u"dd")
    translated = translated.replace(u"ஞா", u"QV")
    translated = translated.replace(u"ஞ", u"Q")
    
    translated = translated.replace(u"ட்", u"â")
    translated = translated.replace(u"டௌ", u"Ø¦e")
    translated = translated.replace(u"டோ", u"¼¦V")
    translated = translated.replace(u"டொ", u"Ø¦V")
    translated = translated.replace(u"டை", u"ç¦")
    translated = translated.replace(u"டே", u"¼¦")
    translated = translated.replace(u"டெ", u"Ø¦")
    translated = translated.replace(u"டூ", u"ù")
    translated = translated.replace(u"டு", u"|")
    translated = translated.replace(u"டீ", u"Ï")
    translated = translated.replace(u"டி", u"½")
    translated = translated.replace(u"டா", u"¦V")
    translated = translated.replace(u"ட", u"¦")
    
    translated = translated.replace(u"ண்", u"õ")
    translated = translated.replace(u"ணௌ", u"Øðe")
    translated = translated.replace(u"ணோ", u"¼ðV")
    translated = translated.replace(u"ணொ", u"ØðV")
    translated = translated.replace(u"ணை", u"çð")
    translated = translated.replace(u"ணே", u"¼ð")
    translated = translated.replace(u"ணெ", u"Øð")
    translated = translated.replace(u"ணூ", u"dd")
    translated = translated.replace(u"ணு", u"b")
    translated = translated.replace(u"ணீ", u"§")
    translated = translated.replace(u"ணி", u"è")
    translated = translated.replace(u"ணா", u"ðV")
    translated = translated.replace(u"ண", u"ð")
    
    translated = translated.replace(u"த்", u"Ý")
    translated = translated.replace(u"தௌ", u"Ø>e")
    translated = translated.replace(u"தோ", u"¼>V")
    translated = translated.replace(u"தொ", u"Ø>V")
    translated = translated.replace(u"தை", u"ç>")
    translated = translated.replace(u"தே", u"¼>")
    translated = translated.replace(u"தெ", u"Ø>")
    translated = translated.replace(u"தூ", u"#")
    translated = translated.replace(u"து", u"m")
    translated = translated.replace(u"தீ", u"y")
    translated = translated.replace(u"தி", u"]")
    translated = translated.replace(u"தா", u">V")
    translated = translated.replace(u"த", u">")
    
    translated = translated.replace(u"ந்", u"Í")
    translated = translated.replace(u"நௌ", u"Øåe")
    translated = translated.replace(u"நோ", u"¼åV")
    translated = translated.replace(u"நொ", u"ØåV")
    translated = translated.replace(u"நை", u"çå")
    translated = translated.replace(u"நே", u"¼å")
    translated = translated.replace(u"நெ", u"Øå")
    translated = translated.replace(u"நூ", u"±")
    translated = translated.replace(u"நு", u"O")
    translated = translated.replace(u"நீ", u"À")
    translated = translated.replace(u"நி", u"W")
    translated = translated.replace(u"நா", u"åV")
    translated = translated.replace(u"ந", u"å")
    
    translated = translated.replace(u"ன்", u"[")
    translated = translated.replace(u"னௌ", u"Øªe")
    translated = translated.replace(u"னோ", u"¼ªV")
    translated = translated.replace(u"னொ", u"ØªV")
    translated = translated.replace(u"னை", u"çª")
    translated = translated.replace(u"னே", u"¼ª")
    translated = translated.replace(u"னெ", u"Øª")
    translated = translated.replace(u"னூ", u"û")
    translated = translated.replace(u"னு", u"Ð")
    translated = translated.replace(u"னீ", u"Ì")
    translated = translated.replace(u"னி", u"M")
    translated = translated.replace(u"னா", u"ªV")
    translated = translated.replace(u"ன", u"ª")
    
    translated = translated.replace(u"ப்", u"©")
    translated = translated.replace(u"பௌ", u"ØÃe")
    translated = translated.replace(u"போ", u"¼ÃV")
    translated = translated.replace(u"பொ", u"ØÃV")
    translated = translated.replace(u"பை", u"çÃ")
    translated = translated.replace(u"பே", u"¼Ã")
    translated = translated.replace(u"பெ", u"ØÃ")
    translated = translated.replace(u"பூ", u"¯")
    translated = translated.replace(u"பு", u"A")
    translated = translated.replace(u"பீ", u"¬")
    translated = translated.replace(u"பி", u"¸")
    translated = translated.replace(u"பா", u"ÃV")
    translated = translated.replace(u"ப", u"Ã")
    
    translated = translated.replace(u"ம்", u"D")
    translated = translated.replace(u"மௌ", u"Ø\e")
    translated = translated.replace(u"மோ", u"¼\V")
    translated = translated.replace(u"மொ", u"Ø\V")
    translated = translated.replace(u"மை", u"ç\\")
    translated = translated.replace(u"மே", u"¼\\")
    translated = translated.replace(u"மெ", u"Ø\\")
    translated = translated.replace(u"மூ", u"J")
    translated = translated.replace(u"மு", u"x")
    translated = translated.replace(u"மீ", u"*")
    translated = translated.replace(u"மி", u"t")
    translated = translated.replace(u"மா", u"\V")
    translated = translated.replace(u"ம", u"\\")
    
    translated = translated.replace(u"ய்", u"F")
    translated = translated.replace(u"யௌ", u"ØBe")
    translated = translated.replace(u"யோ", u"¼BV")
    translated = translated.replace(u"யொ", u"ØBV")
    translated = translated.replace(u"யை", u"çB")
    translated = translated.replace(u"யே", u"¼B")
    translated = translated.replace(u"யெ", u"ØB")
    translated = translated.replace(u"யூ", u"R")
    translated = translated.replace(u"யு", u"¥")
    translated = translated.replace(u"யீ", u"X")
    translated = translated.replace(u"யி", u"l")
    translated = translated.replace(u"யா", u"BV")
    translated = translated.replace(u"ய", u"B")
    
    translated = translated.replace(u"ர்", u"ì")
    translated = translated.replace(u"ரௌ", u"Ø«e")
    translated = translated.replace(u"ரோ", u"¼«V")
    translated = translated.replace(u"ரொ", u"Ø«V")
    translated = translated.replace(u"ரை", u"ç«")
    translated = translated.replace(u"ரே", u"¼«")
    translated = translated.replace(u"ரெ", u"Ø«")
    translated = translated.replace(u"ரூ", u"Ô")
    translated = translated.replace(u"ரு", u"ò")
    translated = translated.replace(u"ரீ", u"Z")
    translated = translated.replace(u"ரி", u"ö")
    translated = translated.replace(u"ரா", u"«V")
    translated = translated.replace(u"ர", u"«")
    
    translated = translated.replace(u"ற்", u"u")
    translated = translated.replace(u"றௌ", u"ØÅe")
    translated = translated.replace(u"றோ", u"¼ÅV")
    translated = translated.replace(u"றொ", u"ØÅV")
    translated = translated.replace(u"றை", u"çÅ")
    translated = translated.replace(u"றே", u"¼Å")
    translated = translated.replace(u"ரெ", u"Ø«")
    translated = translated.replace(u"றூ", u"G")
    translated = translated.replace(u"று", u"®")
    translated = translated.replace(u"றீ", u"S")
    translated = translated.replace(u"றி", u"¤")
    translated = translated.replace(u"றா", u"ÅV")
    translated = translated.replace(u"ற", u"Å")
    
    translated = translated.replace(u"ல்", u"_")
    translated = translated.replace(u"லௌ", u"Øée")
    translated = translated.replace(u"லோ", u"¼éV")
    translated = translated.replace(u"லொ", u"ØéV")
    translated = translated.replace(u"லை", u"çé")
    translated = translated.replace(u"லே", u"¼é")
    translated = translated.replace(u"லெ", u"Øé")
    translated = translated.replace(u"லூ", u"Ù")
    translated = translated.replace(u"லு", u"K")
    translated = translated.replace(u"லீ", u"Ü")
    translated = translated.replace(u"லி", u"o")
    translated = translated.replace(u"லா", u"éV")
    translated = translated.replace(u"ல", u"é")
    
    translated = translated.replace(u"ள்", u"^")
    translated = translated.replace(u"ளௌ", u"Øee")
    translated = translated.replace(u"ளோ", u"¼eV")
    translated = translated.replace(u"ளொ", u"ØeV")
    translated = translated.replace(u"ளை", u"çe")
    translated = translated.replace(u"ளே", u"¼e")
    translated = translated.replace(u"ளெ", u"Øe")
    translated = translated.replace(u"ளூ", u"j")
    translated = translated.replace(u"ளு", u"Ó")
    translated = translated.replace(u"ளீ", u"C")
    translated = translated.replace(u"ளி", u"¹")
    translated = translated.replace(u"ளா", u"eV")
    translated = translated.replace(u"ள", u"e")
    
    translated = translated.replace(u"ழ்", u"µ")
    translated = translated.replace(u"ழௌ", u"Øwe")
    translated = translated.replace(u"ழோ", u"¼wV")
    translated = translated.replace(u"ழொ", u"ØwV")
    translated = translated.replace(u"ழை", u"çw")
    translated = translated.replace(u"ழே", u"¼w")
    translated = translated.replace(u"ழெ", u"Øw")
    translated = translated.replace(u"ழூ", u"ñ")
    translated = translated.replace(u"ழு", u"¿")
    translated = translated.replace(u"ழீ", u"Ñ")
    translated = translated.replace(u"ழி", u"a")
    translated = translated.replace(u"ழா", u"wV")
    translated = translated.replace(u"ழ", u"w")
    
    translated = translated.replace(u"வ்", u"Ë")
    translated = translated.replace(u"வௌ", u"Øke")
    translated = translated.replace(u"வோ", u"¼kV")
    translated = translated.replace(u"வொ", u"ØkV")
    translated = translated.replace(u"வை", u"çk")
    translated = translated.replace(u"வே", u"¼k")
    translated = translated.replace(u"வெ", u"Øk")
    translated = translated.replace(u"வூ", u"Æ")
    translated = translated.replace(u"வு", u"¡")
    translated = translated.replace(u"வீ", u"T")
    translated = translated.replace(u"வி", u"s")
    translated = translated.replace(u"வா", u"kV")
    translated = translated.replace(u"வ", u"k")
    
    translated = translated.replace(u"ஷ்", u"i")
    translated = translated.replace(u"ஷௌ", u"Øre")
    translated = translated.replace(u"ஷோ", u"¼rV")
    translated = translated.replace(u"ஷொ", u"ØrV")
    translated = translated.replace(u"ஷை", u"çr")
    translated = translated.replace(u"ஷே", u"¼r")
    translated = translated.replace(u"ஷெ", u"Ør")
    translated = translated.replace(u"ஷூ", u"£")
    translated = translated.replace(u"ஷு", u"×")
    translated = translated.replace(u"ஷீ", u"U")
    translated = translated.replace(u"ஷி", u"´")
    translated = translated.replace(u"ஷா", u"rV")
    translated = translated.replace(u"ஷ", u"r")
    
    translated = translated.replace(u"ஸ்", u"ü")
    translated = translated.replace(u"ஸௌ", u"Øve")
    translated = translated.replace(u"ஸோ", u"¼vV")
    translated = translated.replace(u"ஸொ", u"ØvV")
    translated = translated.replace(u"ஸை", u"çv")
    translated = translated.replace(u"ஸே", u"¼v")
    translated = translated.replace(u"ஸெ", u"Øv")
    translated = translated.replace(u"ஸூ", u"`")
    translated = translated.replace(u"ஸு", u"q")
    translated = translated.replace(u"ஸீ", u"¢")
    translated = translated.replace(u"ஸி", u"L")
    translated = translated.replace(u"ஸா", u"vV")
    translated = translated.replace(u"ஸ", u"v")
    
    translated = translated.replace(u"ஹ்", u"ã")
    translated = translated.replace(u"ஹௌ", u"ØÇe")
    translated = translated.replace(u"ஹோ", u"¼ÇV")
    translated = translated.replace(u"ஹொ", u"ØÇV")
    translated = translated.replace(u"ஹை", u"çÇ")
    translated = translated.replace(u"ஹே", u"¼Ç")
    translated = translated.replace(u"ஹெ", u"ØÇ")
    translated = translated.replace(u"ஹீ", u"ê")
    translated = translated.replace(u"ஹி", u"N")
    translated = translated.replace(u"ஹா", u"ÇV")
    translated = translated.replace(u"ஹ", u"Ç")

    translated = translated.replace(u"க்ஷ்", u"Õ")
    translated = translated.replace(u"க்ஷௌ", u"Ø³e")
    translated = translated.replace(u"க்ஷோ", u"¼³V")
    translated = translated.replace(u"க்ஷொ", u"Ø³V")
    translated = translated.replace(u"க்ஷை", u"ç³")
    translated = translated.replace(u"க்ஷே", u"¼³")
    translated = translated.replace(u"க்ஷெ", u"Ø³")
    translated = translated.replace(u"க்ஷூ", u"f")
    translated = translated.replace(u"க்ஷு", u"Y")
    translated = translated.replace(u"க்ஷீ", u"È")
    translated = translated.replace(u"க்ஷி", u"H")
    translated = translated.replace(u"க்ஷா", u"³V")
    translated = translated.replace(u"க்ஷ", u"³")
    
    unconverted = [i for i in translated if i in source_text and not i in
                    punctuation+whitespace+digits]
    translated_trimed = ''.join([i for i in translated if not i in unconverted])

    if debug:
        return unconverted
    elif filtered:
        return translated_trimed
    else:
        return translated