# -*- coding: utf-8 -*-
from string import punctuation, whitespace, digits


def convertToroman(source_text, filtered=False, debug=False):
    translated = source_text

    # Independent Vowels
    translated = translated.replace(u"ஓ", u"oa")
    translated = translated.replace(u"ஆ", u"aa")
    translated = translated.replace(u"ஔ", u"au")
    translated = translated.replace(u"ஐ", u"ai")
    translated = translated.replace(u"ஏ", u"ae")
    translated = translated.replace(u"அ", u"a")
    # translated = translated.replace(u"ஈ", u"ee")
    # translated = translated.replace(u"ஈ", u"I")
    translated = translated.replace(u"ஈ", u"ii")
    translated = translated.replace(u"இ", u"i")
    # translated = translated.replace(u"ஊ", u"U")
    # translated = translated.replace(u"ஊ", u"oo")
    translated = translated.replace(u"ஊ", u"uu")
    translated = translated.replace(u"உ", u"u")
    # translated = translated.replace(u"ஏ", u"ee")
    translated = translated.replace(u"எ", u"e")
    # translated = translated.replace(u"ஏ", u"E")
    # translated = translated.replace(u"ஓ", u"oo")
    # translated = translated.replace(u"ஓ", u"O")
    translated = translated.replace(u"ஒ", u"o")
    translated = translated.replace(u"ஃ", u"q")
    # translated = translated.replace(u"ஃ", u"H")
    # translated = translated.replace(u"ஃ", u"Ahh")

    # க Family
    # translated = translated.replace(u"கௌ", u"hau")
    # translated = translated.replace(u"கோ", u"hoo")
    # translated = translated.replace(u"கொ", u"ho")
    # translated = translated.replace(u"கை", u"hai")
    # translated = translated.replace(u"கே", u"hee")
    # translated = translated.replace(u"கெ", u"he")
    # translated = translated.replace(u"கூ", u"huu")
    # translated = translated.replace(u"கு", u"hu")
    # translated = translated.replace(u"கீ", u"hii")
    # translated = translated.replace(u"கி", u"hi")
    # translated = translated.replace(u"கா", u"haa")
    # translated = translated.replace(u"க", u"ha")
    # translated = translated.replace(u"க்", u"h")

    # க Family
    translated = translated.replace(u"க்", u"k")
    translated = translated.replace(u"கௌ", u"kau")
    translated = translated.replace(u"கோ", u"koo")
    translated = translated.replace(u"கொ", u"ko")
    translated = translated.replace(u"கை", u"kai")
    translated = translated.replace(u"கே", u"kee")
    translated = translated.replace(u"கெ", u"ke")
    translated = translated.replace(u"கூ", u"kuu")
    translated = translated.replace(u"கு", u"ku")
    translated = translated.replace(u"கீ", u"kii")
    translated = translated.replace(u"கி", u"ki")
    translated = translated.replace(u"கா", u"kaa")
    translated = translated.replace(u"க", u"ka")

    # க Family
    # translated = translated.replace(u"கௌ", u"khau")
    # translated = translated.replace(u"கோ", u"khoo")
    # translated = translated.replace(u"கொ", u"kho")
    # translated = translated.replace(u"கை", u"khai")
    # translated = translated.replace(u"கே", u"khee")
    # translated = translated.replace(u"கெ", u"khe")
    # translated = translated.replace(u"கூ", u"khuu")
    # translated = translated.replace(u"கு", u"khu")
    # translated = translated.replace(u"கீ", u"khii")
    # translated = translated.replace(u"கி", u"khi")
    # translated = translated.replace(u"கா", u"khaa")
    # translated = translated.replace(u"க", u"kha")
    # translated = translated.replace(u"க்", u"kh")

    # க Family
    # translated = translated.replace(u"கௌ", u"gau")
    # translated = translated.replace(u"கோ", u"goo")
    # translated = translated.replace(u"கொ", u"go")
    # translated = translated.replace(u"கை", u"gai")
    # translated = translated.replace(u"கே", u"gee")
    # translated = translated.replace(u"கெ", u"ge")
    # translated = translated.replace(u"கூ", u"guu")
    # translated = translated.replace(u"கு", u"gu")
    # translated = translated.replace(u"கீ", u"gii")
    # translated = translated.replace(u"கி", u"gi")
    # translated = translated.replace(u"கா", u"gaa")
    # translated = translated.replace(u"க", u"ga")
    # translated = translated.replace(u"க்", u"g")

    # க Family
    # translated = translated.replace(u"கௌ", u"cau")
    # translated = translated.replace(u"கோ", u"coo")
    # translated = translated.replace(u"கொ", u"co")
    # translated = translated.replace(u"கை", u"cai")
    # translated = translated.replace(u"கே", u"cee")
    # translated = translated.replace(u"கெ", u"ce")
    # translated = translated.replace(u"கூ", u"cuu")
    # translated = translated.replace(u"கு", u"cu")
    # translated = translated.replace(u"கீ", u"cii")
    # translated = translated.replace(u"கி", u"ci")
    # translated = translated.replace(u"கா", u"caa")
    # translated = translated.replace(u"க", u"ca")
    # translated = translated.replace(u"க்", u"c")

    # ங Family
    translated = translated.replace(u"ங்", u"ng")
    translated = translated.replace(u"ஙௌ", u"ngau")
    translated = translated.replace(u"ஙோ", u"ngoo")
    translated = translated.replace(u"ஙொ", u"ngo")
    translated = translated.replace(u"ஙை", u"ngai")
    translated = translated.replace(u"ஙே", u"ngee")
    translated = translated.replace(u"ஙெ", u"nge")
    translated = translated.replace(u"ஙூ", u"nguu")
    translated = translated.replace(u"ஙு", u"ngu")
    translated = translated.replace(u"ஙீ", u"ngii")
    translated = translated.replace(u"ஙி", u"ngi")
    translated = translated.replace(u"ஙா", u"ngaa")
    translated = translated.replace(u"ங", u"nga")

    # ங Family
    # translated = translated.replace(u"ஙௌ", u"nGau")
    # translated = translated.replace(u"ஙோ", u"nGoo")
    # translated = translated.replace(u"ஙொ", u"nGo")
    # translated = translated.replace(u"ஙை", u"nGai")
    # translated = translated.replace(u"ஙே", u"nGee")
    # translated = translated.replace(u"ஙெ", u"nGe")
    # translated = translated.replace(u"ஙூ", u"nGuu")
    # translated = translated.replace(u"ஙு", u"nGu")
    # translated = translated.replace(u"ஙீ", u"nGii")
    # translated = translated.replace(u"ஙி", u"nGi")
    # translated = translated.replace(u"ஙா", u"nGaa")
    # translated = translated.replace(u"ங", u"nGa")
    # translated = translated.replace(u"ங்", u"nG")

    # ச Family
    translated = translated.replace(u"ச்", u"ch")
    translated = translated.replace(u"சௌ", u"chau")
    translated = translated.replace(u"சோ", u"choo")
    translated = translated.replace(u"சொ", u"cho")
    translated = translated.replace(u"சை", u"chai")
    translated = translated.replace(u"சே", u"chee")
    translated = translated.replace(u"செ", u"che")
    translated = translated.replace(u"சூ", u"chuu")
    translated = translated.replace(u"சு", u"chu")
    translated = translated.replace(u"சீ", u"chii")
    translated = translated.replace(u"சி", u"chi")
    translated = translated.replace(u"சா", u"chaa")
    translated = translated.replace(u"ச", u"cha")

    # ஜ Family
    translated = translated.replace(u"ஜ்", u"j")
    translated = translated.replace(u"ஜௌ", u"jau")
    translated = translated.replace(u"ஜோ", u"joo")
    translated = translated.replace(u"ஜொ", u"jo")
    translated = translated.replace(u"ஜை", u"jai")
    translated = translated.replace(u"ஜே", u"jee")
    translated = translated.replace(u"ஜெ", u"je")
    translated = translated.replace(u"ஜூ", u"juu")
    translated = translated.replace(u"ஜு", u"ju")
    translated = translated.replace(u"ஜீ", u"jii")
    translated = translated.replace(u"ஜி", u"ji")
    translated = translated.replace(u"ஜா", u"jaa")
    translated = translated.replace(u"ஜ", u"ja")

    # ஞ Family
    translated = translated.replace(u"ஞ்", u"nj")
    translated = translated.replace(u"ஞௌ", u"njau")
    translated = translated.replace(u"ஞோ", u"njoo")
    translated = translated.replace(u"ஞொ", u"njo")
    translated = translated.replace(u"ஞை", u"njai")
    translated = translated.replace(u"ஞே", u"njee")
    translated = translated.replace(u"ஞெ", u"nje")
    translated = translated.replace(u"ஞூ", u"njuu")
    translated = translated.replace(u"ஞு", u"nju")
    translated = translated.replace(u"ஞீ", u"njii")
    translated = translated.replace(u"ஞி", u"nji")
    translated = translated.replace(u"ஞா", u"njaa")
    translated = translated.replace(u"ஞ", u"nja")

    # ஞ Family
    # translated = translated.replace(u"ஞௌ", u"nYau")
    # translated = translated.replace(u"ஞோ", u"nYoo")
    # translated = translated.replace(u"ஞொ", u"nYo")
    # translated = translated.replace(u"ஞை", u"nYai")
    # translated = translated.replace(u"ஞே", u"nYee")
    # translated = translated.replace(u"ஞெ", u"nYe")
    # translated = translated.replace(u"ஞூ", u"nYuu")
    # translated = translated.replace(u"ஞு", u"nYu")
    # translated = translated.replace(u"ஞீ", u"nYii")
    # translated = translated.replace(u"ஞி", u"nYi")
    # translated = translated.replace(u"ஞா", u"nYaa")
    # translated = translated.replace(u"ஞ", u"nYa")
    # translated = translated.replace(u"ஞ்", u"nY")

    # ட Family
    # translated = translated.replace(u"டௌ", u"tau")
    # translated = translated.replace(u"டோ", u"too")
    # translated = translated.replace(u"டொ", u"to")
    # translated = translated.replace(u"டை", u"tai")
    # translated = translated.replace(u"டே", u"tee")
    # translated = translated.replace(u"டெ", u"te")
    # translated = translated.replace(u"டூ", u"tuu")
    # translated = translated.replace(u"டு", u"tu")
    # translated = translated.replace(u"டீ", u"tii")
    # translated = translated.replace(u"டி", u"ti")
    # translated = translated.replace(u"டா", u"taa")
    # translated = translated.replace(u"ட", u"ta")
    # translated = translated.replace(u"ட்", u"t")

    # ட Family
    translated = translated.replace(u"ட்", u"d")
    translated = translated.replace(u"டௌ", u"dau")
    translated = translated.replace(u"டோ", u"doo")
    translated = translated.replace(u"டொ", u"do")
    translated = translated.replace(u"டை", u"dai")
    translated = translated.replace(u"டே", u"dee")
    translated = translated.replace(u"டெ", u"de")
    translated = translated.replace(u"டூ", u"duu")
    translated = translated.replace(u"டு", u"du")
    translated = translated.replace(u"டீ", u"dii")
    translated = translated.replace(u"டி", u"di")
    translated = translated.replace(u"டா", u"daa")
    translated = translated.replace(u"ட", u"da")

    # ண Family
    # translated = translated.replace(u"ணௌ", u"Nau")
    # translated = translated.replace(u"ணோ", u"Noo")
    # translated = translated.replace(u"ணொ", u"No")
    # translated = translated.replace(u"ணை", u"Nai")
    # translated = translated.replace(u"ணே", u"Nee")
    # translated = translated.replace(u"ணெ", u"Ne")
    # translated = translated.replace(u"ணூ", u"Nuu")
    # translated = translated.replace(u"ணு", u"Nu")
    # translated = translated.replace(u"ணீ", u"Nii")
    # translated = translated.replace(u"ணி", u"Ni")
    # translated = translated.replace(u"ணா", u"Naa")
    # translated = translated.replace(u"ண", u"Na")
    # translated = translated.replace(u"ண்", u"N")

    # ண Family
    translated = translated.replace(u"ண்", u"nN")
    translated = translated.replace(u"ணௌ", u"nNau")
    translated = translated.replace(u"ணோ", u"nNoo")
    translated = translated.replace(u"ணொ", u"nNo")
    translated = translated.replace(u"ணை", u"nNai")
    translated = translated.replace(u"ணே", u"nNee")
    translated = translated.replace(u"ணெ", u"nNe")
    translated = translated.replace(u"ணூ", u"nNuu")
    translated = translated.replace(u"ணு", u"nNu")
    translated = translated.replace(u"ணீ", u"nNii")
    translated = translated.replace(u"ணி", u"nNi")
    translated = translated.replace(u"ணா", u"nNaa")
    translated = translated.replace(u"ண", u"nNa")

    # த Family
    # translated = translated.replace(u"தௌ", u"dhau")
    # translated = translated.replace(u"தோ", u"dhoo")
    # translated = translated.replace(u"தொ", u"dho")
    # translated = translated.replace(u"தை", u"dhai")
    # translated = translated.replace(u"தே", u"dhee")
    # translated = translated.replace(u"தெ", u"dhe")
    # translated = translated.replace(u"தூ", u"dhuu")
    # translated = translated.replace(u"து", u"dhu")
    # translated = translated.replace(u"தீ", u"dhii")
    # translated = translated.replace(u"தி", u"dhi")
    # translated = translated.replace(u"தா", u"dhaa")
    # translated = translated.replace(u"த", u"dha")
    # translated = translated.replace(u"த்", u"dh")

    # த Family
    translated = translated.replace(u"த்", u"th")
    translated = translated.replace(u"தௌ", u"thau")
    translated = translated.replace(u"தோ", u"thoo")
    translated = translated.replace(u"தொ", u"tho")
    translated = translated.replace(u"தை", u"thai")
    translated = translated.replace(u"தே", u"thee")
    translated = translated.replace(u"தெ", u"the")
    translated = translated.replace(u"தூ", u"thuu")
    translated = translated.replace(u"து", u"thu")
    translated = translated.replace(u"தீ", u"thii")
    translated = translated.replace(u"தி", u"thi")
    translated = translated.replace(u"தா", u"thaa")
    translated = translated.replace(u"த", u"tha")

    # ந Family
    translated = translated.replace(u"ந்", u"N")
    translated = translated.replace(u"நௌ", u"Nau")
    translated = translated.replace(u"நோ", u"Noo")
    translated = translated.replace(u"நொ", u"No")
    translated = translated.replace(u"நை", u"Nai")
    translated = translated.replace(u"நே", u"Nee")
    translated = translated.replace(u"நெ", u"Ne")
    translated = translated.replace(u"நூ", u"Nuu")
    translated = translated.replace(u"நு", u"Nu")
    translated = translated.replace(u"நீ", u"Nii")
    translated = translated.replace(u"நி", u"Ni")
    translated = translated.replace(u"நா", u"Naa")
    translated = translated.replace(u"ந", u"Na")

    # ன Family
    translated = translated.replace(u"ன்", u"n")
    translated = translated.replace(u"னௌ", u"nau")
    translated = translated.replace(u"னோ", u"noo")
    translated = translated.replace(u"னொ", u"no")
    translated = translated.replace(u"னை", u"nai")
    translated = translated.replace(u"னே", u"nee")
    translated = translated.replace(u"னெ", u"ne")
    translated = translated.replace(u"னூ", u"nuu")
    translated = translated.replace(u"னு", u"nu")
    translated = translated.replace(u"னீ", u"nii")
    translated = translated.replace(u"னி", u"ni")
    translated = translated.replace(u"னா", u"naa")
    translated = translated.replace(u"ன", u"na")

    # ப Family
    translated = translated.replace(u"ப்", u"p")
    translated = translated.replace(u"பௌ", u"pau")
    translated = translated.replace(u"போ", u"poo")
    translated = translated.replace(u"பொ", u"po")
    translated = translated.replace(u"பை", u"pai")
    translated = translated.replace(u"பே", u"pee")
    translated = translated.replace(u"பெ", u"pe")
    translated = translated.replace(u"பூ", u"puu")
    translated = translated.replace(u"பு", u"pu")
    translated = translated.replace(u"பீ", u"pii")
    translated = translated.replace(u"பி", u"pi")
    translated = translated.replace(u"பா", u"paa")
    translated = translated.replace(u"ப", u"pa")

    # ப Family
    # translated = translated.replace(u"பௌ", u"bhau")
    # translated = translated.replace(u"போ", u"bhoo")
    # translated = translated.replace(u"பொ", u"bho")
    # translated = translated.replace(u"பை", u"bhai")
    # translated = translated.replace(u"பே", u"bhee")
    # translated = translated.replace(u"பெ", u"bhe")
    # translated = translated.replace(u"பூ", u"bhuu")
    # translated = translated.replace(u"பு", u"bhu")
    # translated = translated.replace(u"பீ", u"bhii")
    # translated = translated.replace(u"பி", u"bhi")
    # translated = translated.replace(u"பா", u"bhaa")
    # translated = translated.replace(u"ப", u"bha")
    # translated = translated.replace(u"ப்", u"bh")

    # ப Family
    # translated = translated.replace(u"பௌ", u"bau")
    # translated = translated.replace(u"போ", u"boo")
    # translated = translated.replace(u"பொ", u"bo")
    # translated = translated.replace(u"பை", u"bai")
    # translated = translated.replace(u"பே", u"bee")
    # translated = translated.replace(u"பெ", u"be")
    # translated = translated.replace(u"பூ", u"buu")
    # translated = translated.replace(u"பு", u"bu")
    # translated = translated.replace(u"பீ", u"bii")
    # translated = translated.replace(u"பி", u"bi")
    # translated = translated.replace(u"பா", u"baa")
    # translated = translated.replace(u"ப", u"ba")
    # translated = translated.replace(u"ப்", u"b")

    # ம Family
    translated = translated.replace(u"ம்", u"m")
    translated = translated.replace(u"மௌ", u"mau")
    translated = translated.replace(u"மோ", u"moo")
    translated = translated.replace(u"மொ", u"mo")
    translated = translated.replace(u"மை", u"mai")
    translated = translated.replace(u"மே", u"mee")
    translated = translated.replace(u"மெ", u"me")
    translated = translated.replace(u"மூ", u"muu")
    translated = translated.replace(u"மு", u"mu")
    translated = translated.replace(u"மீ", u"mii")
    translated = translated.replace(u"மி", u"mi")
    translated = translated.replace(u"மா", u"maa")
    translated = translated.replace(u"ம", u"ma")

    # ய Family
    translated = translated.replace(u"ய்", u"y")
    translated = translated.replace(u"யௌ", u"yau")
    translated = translated.replace(u"யோ", u"yoo")
    translated = translated.replace(u"யொ", u"yo")
    translated = translated.replace(u"யை", u"yai")
    translated = translated.replace(u"யே", u"yee")
    translated = translated.replace(u"யெ", u"ye")
    translated = translated.replace(u"யூ", u"yuu")
    translated = translated.replace(u"யு", u"yu")
    translated = translated.replace(u"யீ", u"yii")
    translated = translated.replace(u"யி", u"yi")
    translated = translated.replace(u"யா", u"yaa")
    translated = translated.replace(u"ய", u"ya")

    # ர Family
    translated = translated.replace(u"ர்", u"r")
    translated = translated.replace(u"ரௌ", u"rau")
    translated = translated.replace(u"ரோ", u"roo")
    translated = translated.replace(u"ரொ", u"ro")
    translated = translated.replace(u"ரை", u"rai")
    translated = translated.replace(u"ரே", u"ree")
    translated = translated.replace(u"ரெ", u"re")
    translated = translated.replace(u"ரூ", u"ruu")
    translated = translated.replace(u"ரு", u"ru")
    translated = translated.replace(u"ரீ", u"rii")
    translated = translated.replace(u"ரி", u"ri")
    translated = translated.replace(u"ரா", u"raa")
    translated = translated.replace(u"ர", u"ra")

    # ற Family
    translated = translated.replace(u"ற்", u"R")
    translated = translated.replace(u"றௌ", u"Rau")
    translated = translated.replace(u"றோ", u"Roo")
    translated = translated.replace(u"றொ", u"Ro")
    translated = translated.replace(u"றை", u"Rai")
    translated = translated.replace(u"றே", u"Ree")
    translated = translated.replace(u"ரெ", u"re")
    translated = translated.replace(u"றூ", u"Ruu")
    translated = translated.replace(u"று", u"Ru")
    translated = translated.replace(u"றீ", u"Rii")
    translated = translated.replace(u"றி", u"Ri")
    translated = translated.replace(u"றா", u"Raa")
    translated = translated.replace(u"ற", u"Ra")

    # ல Family
    translated = translated.replace(u"ல்", u"l")
    translated = translated.replace(u"லௌ", u"lau")
    translated = translated.replace(u"லோ", u"loo")
    translated = translated.replace(u"லொ", u"lo")
    translated = translated.replace(u"லை", u"lai")
    translated = translated.replace(u"லே", u"lee")
    translated = translated.replace(u"லெ", u"le")
    translated = translated.replace(u"லூ", u"luu")
    translated = translated.replace(u"லு", u"lu")
    translated = translated.replace(u"லீ", u"lii")
    translated = translated.replace(u"லி", u"li")
    translated = translated.replace(u"லா", u"laa")
    translated = translated.replace(u"ல", u"la")

    # ள Family
    translated = translated.replace(u"ள்", u"L")
    translated = translated.replace(u"ளௌ", u"Lau")
    translated = translated.replace(u"ளோ", u"Loo")
    translated = translated.replace(u"ளொ", u"Lo")
    translated = translated.replace(u"ளை", u"Lai")
    translated = translated.replace(u"ளே", u"Lee")
    translated = translated.replace(u"ளெ", u"Le")
    translated = translated.replace(u"ளூ", u"Luu")
    translated = translated.replace(u"ளு", u"Lu")
    translated = translated.replace(u"ளீ", u"Lii")
    translated = translated.replace(u"ளி", u"Li")
    translated = translated.replace(u"ளா", u"Laa")
    translated = translated.replace(u"ள", u"La")

    # ழ Family
    translated = translated.replace(u"ழ்", u"z")
    translated = translated.replace(u"ழௌ", u"zau")
    translated = translated.replace(u"ழோ", u"zoo")
    translated = translated.replace(u"ழொ", u"zo")
    translated = translated.replace(u"ழை", u"zai")
    translated = translated.replace(u"ழே", u"zee")
    translated = translated.replace(u"ழெ", u"ze")
    translated = translated.replace(u"ழூ", u"zuu")
    translated = translated.replace(u"ழு", u"zu")
    translated = translated.replace(u"ழீ", u"zii")
    translated = translated.replace(u"ழி", u"zi")
    translated = translated.replace(u"ழா", u"zaa")
    translated = translated.replace(u"ழ", u"za")

    # ழ Family
    # translated = translated.replace(u"ழௌ", u"zhau")
    # translated = translated.replace(u"ழோ", u"zhoo")
    # translated = translated.replace(u"ழொ", u"zho")
    # translated = translated.replace(u"ழை", u"zhai")
    # translated = translated.replace(u"ழே", u"zhee")
    # translated = translated.replace(u"ழெ", u"zhe")
    # translated = translated.replace(u"ழூ", u"zhuu")
    # translated = translated.replace(u"ழு", u"zhu")
    # translated = translated.replace(u"ழீ", u"zhii")
    # translated = translated.replace(u"ழி", u"zhi")
    # translated = translated.replace(u"ழா", u"zhaa")
    # translated = translated.replace(u"ழ", u"zha")
    # translated = translated.replace(u"ழ்", u"zh")

    # வ Family
    translated = translated.replace(u"வ்", u"v")
    translated = translated.replace(u"வௌ", u"vau")
    translated = translated.replace(u"வோ", u"voo")
    translated = translated.replace(u"வொ", u"vo")
    translated = translated.replace(u"வை", u"vai")
    translated = translated.replace(u"வே", u"vee")
    translated = translated.replace(u"வெ", u"ve")
    translated = translated.replace(u"வூ", u"vuu")
    translated = translated.replace(u"வு", u"vu")
    translated = translated.replace(u"வீ", u"vii")
    translated = translated.replace(u"வி", u"vi")
    translated = translated.replace(u"வா", u"vaa")
    translated = translated.replace(u"வ", u"va")

    # வ Family
    # translated = translated.replace(u"வௌ", u"wau")
    # translated = translated.replace(u"வோ", u"woo")
    # translated = translated.replace(u"வொ", u"wo")
    # translated = translated.replace(u"வை", u"wai")
    # translated = translated.replace(u"வே", u"wee")
    # translated = translated.replace(u"வெ", u"we")
    # translated = translated.replace(u"வூ", u"wuu")
    # translated = translated.replace(u"வு", u"wu")
    # translated = translated.replace(u"வீ", u"wii")
    # translated = translated.replace(u"வி", u"wi")
    # translated = translated.replace(u"வா", u"waa")
    # translated = translated.replace(u"வ", u"wa")
    # translated = translated.replace(u"வ்", u"w")

    # ஷ Family
    translated = translated.replace(u"ஷ்", u"sh")
    translated = translated.replace(u"ஷௌ", u"shau")
    translated = translated.replace(u"ஷோ", u"shoo")
    translated = translated.replace(u"ஷொ", u"sho")
    translated = translated.replace(u"ஷை", u"shai")
    translated = translated.replace(u"ஷே", u"shee")
    translated = translated.replace(u"ஷெ", u"she")
    translated = translated.replace(u"ஷூ", u"shuu")
    translated = translated.replace(u"ஷு", u"shu")
    translated = translated.replace(u"ஷீ", u"shii")
    translated = translated.replace(u"ஷி", u"shi")
    translated = translated.replace(u"ஷா", u"shaa")
    translated = translated.replace(u"ஷ", u"sha")

    # ஸ Family
    translated = translated.replace(u"ஸ்", u"s")
    translated = translated.replace(u"ஸௌ", u"sau")
    translated = translated.replace(u"ஸோ", u"soo")
    translated = translated.replace(u"ஸொ", u"so")
    translated = translated.replace(u"ஸை", u"sai")
    translated = translated.replace(u"ஸே", u"see")
    translated = translated.replace(u"ஸெ", u"se")
    translated = translated.replace(u"ஸூ", u"suu")
    translated = translated.replace(u"ஸு", u"su")
    translated = translated.replace(u"ஸீ", u"sii")
    translated = translated.replace(u"ஸி", u"si")
    translated = translated.replace(u"ஸா", u"saa")
    translated = translated.replace(u"ஸ", u"sa")

    # ஹ Family
    translated = translated.replace(u"ஹ்", u"h")
    translated = translated.replace(u"ஹௌ", u"hau")
    translated = translated.replace(u"ஹோ", u"hoo")
    translated = translated.replace(u"ஹொ", u"ho")
    translated = translated.replace(u"ஹை", u"hai")
    translated = translated.replace(u"ஹே", u"hee")
    translated = translated.replace(u"ஹெ", u"he")
    translated = translated.replace(u"ஹீ", u"hii")
    translated = translated.replace(u"ஹி", u"hi")
    translated = translated.replace(u"ஹா", u"haa")
    translated = translated.replace(u"ஹ", u"ha")

    # translated = translated.replace(u"்" , "i")

    unconverted = [i for i in translated if i in source_text and not i in
                    punctuation+whitespace+digits]
    translated_trimed = ''.join([i for i in translated if not i in unconverted])

    if debug:
        return unconverted
    elif filtered:
        return translated_trimed
    else:
        return translated