# -*- coding: utf-8 -*-
from string import punctuation, whitespace, digits


def convertTotam(source_text, filtered=False, debug=False):
    translated = source_text
    # Independent Vowels
    translated = translated.replace(u"அ", u"Ü")
    translated = translated.replace(u"ஆ", u"Ý")
    translated = translated.replace(u"இ", u"Þ")
    translated = translated.replace(u"ஈ", u"ß")
    translated = translated.replace(u"உ", u"à")
    translated = translated.replace(u"ஊ", u"á")
    translated = translated.replace(u"எ", u"â")
    translated = translated.replace(u"ஏ", u"ã")
    translated = translated.replace(u"ஐ", u"ä")
    translated = translated.replace(u"ஒ", u"å")
    translated = translated.replace(u"ஓ", u"æ")
    translated = translated.replace(u"ஔ", u"å÷")
    translated = translated.replace(u"ஃ", u"ç")

    # க Family
    translated = translated.replace(u"க்", u"‚")
    translated = translated.replace(u"கௌ", u"ªè÷")
    translated = translated.replace(u"கோ", u"«è£")
    translated = translated.replace(u"கொ", u"ªè£")
    translated = translated.replace(u"கை", u"¬è")
    translated = translated.replace(u"கே", u"«è")
    translated = translated.replace(u"கெ", u"ªè")
    translated = translated.replace(u"கூ", u"Ã")
    translated = translated.replace(u"கு", u"°")
    translated = translated.replace(u"கீ", u"W")
    translated = translated.replace(u"கி", u"A")
    translated = translated.replace(u"கா", u"è£")
    translated = translated.replace(u"க", u"è")

    # ங Family
    translated = translated.replace(u"ங்", u"ƒ")
    translated = translated.replace(u"ஙௌ", u"ªé÷")
    translated = translated.replace(u"ஙோ", u"«é£")
    translated = translated.replace(u"ஙொ", u"ªé£")
    translated = translated.replace(u"ஙை", u"¬é")
    translated = translated.replace(u"ஙே", u"«é")
    translated = translated.replace(u"ஙெ", u"ªé")
    translated = translated.replace(u"ஙூ", u"Ä")
    translated = translated.replace(u"ஙு", u"±")
    translated = translated.replace(u"ஙீ", u"X")
    translated = translated.replace(u"ஙி", u"B")
    translated = translated.replace(u"ஙா", u"é£")
    translated = translated.replace(u"ங", u"é")

    # ச Family
    translated = translated.replace(u"ச்", u"„")
    translated = translated.replace(u"சௌ", u"ªê÷")
    translated = translated.replace(u"சோ", u"«ê£")
    translated = translated.replace(u"சொ", u"ªê£")
    translated = translated.replace(u"சை", u"¬ê")
    translated = translated.replace(u"சே", u"«ê")
    translated = translated.replace(u"செ", u"ªê")
    translated = translated.replace(u"சூ", u"Å")
    translated = translated.replace(u"சு", u"²")
    translated = translated.replace(u"சீ", u"Y")
    translated = translated.replace(u"சி", u"C")
    translated = translated.replace(u"சா", u"ê£")
    translated = translated.replace(u"ச", u"ê")

    # ஜ Family
    translated = translated.replace(u"ஜ்", u"x")
    translated = translated.replace(u"ஜௌ", u"ªü÷")
    translated = translated.replace(u"ஜோ", u"«ü£")
    translated = translated.replace(u"ஜொ", u"ªü£")
    translated = translated.replace(u"ஜை", u"¬ü")
    translated = translated.replace(u"ஜே", u"«ü")
    translated = translated.replace(u"ஜெ", u"ªü")
    translated = translated.replace(u"ஜூ", u"ü¨")
    translated = translated.replace(u"ஜு", u"ü§")
    translated = translated.replace(u"ஜீ", u"p")
    translated = translated.replace(u"ஜி", u"T")
    translated = translated.replace(u"ஜா", u"ü£")
    translated = translated.replace(u"ஜ", u"ü")

    # ஞ Family
    translated = translated.replace(u"ஞ்", u"…")
    translated = translated.replace(u"ஞௌ", u"ªë\÷")
    translated = translated.replace(u"ஞோ", u"«ë£")
    translated = translated.replace(u"ஞொ", u"ªë£")
    translated = translated.replace(u"ஞை", u"¬ë")
    translated = translated.replace(u"ஞே", u"«ë")
    translated = translated.replace(u"ஞெ", u"ªë")
    translated = translated.replace(u"ஞூ", u"Æ")
    translated = translated.replace(u"ஞு", u"³")
    translated = translated.replace(u"ஞீ", u"Z")
    translated = translated.replace(u"ஞி", u"D")
    translated = translated.replace(u"ஞா", u"ë£")
    translated = translated.replace(u"ஞ", u"ë")

    # ட Family
    translated = translated.replace(u"ட்", u"†")
    translated = translated.replace(u"டௌ", u"ªì÷")
    translated = translated.replace(u"டோ", u"«ì£")
    translated = translated.replace(u"டொ", u"ªì£")
    translated = translated.replace(u"டை", u"¬ì")
    translated = translated.replace(u"டே", u"«ì")
    translated = translated.replace(u"டெ", u"ªì")
    translated = translated.replace(u"டூ", u"Ç")
    translated = translated.replace(u"டு", u"´")
    translated = translated.replace(u"டீ", u"¯")
    translated = translated.replace(u"டி", u"®")
    translated = translated.replace(u"டா", u"ì£")
    translated = translated.replace(u"ட", u"ì")

    # ண Family
    translated = translated.replace(u"ண்", u"‡")
    translated = translated.replace(u"ணௌ", u"ªí÷")
    translated = translated.replace(u"ணோ", u"«í£")
    translated = translated.replace(u"ணொ", u"ªí£")
    translated = translated.replace(u"ணை", u"¬í")
    translated = translated.replace(u"ணே", u"«í")
    translated = translated.replace(u"ணெ", u"ªí")
    translated = translated.replace(u"ணூ", u"È")
    translated = translated.replace(u"ணு", u"µ")
    translated = translated.replace(u"ணீ", u"a")
    translated = translated.replace(u"ணி", u"E")
    translated = translated.replace(u"ணா", u"í£")
    translated = translated.replace(u"ண", u"í")

    # த Family
    translated = translated.replace(u"த்", u"ˆ")
    translated = translated.replace(u"தௌ", u"ªî÷")
    translated = translated.replace(u"தோ", u"«î£")
    translated = translated.replace(u"தொ", u"ªî£")
    translated = translated.replace(u"தை", u"¬î")
    translated = translated.replace(u"தே", u"«î")
    translated = translated.replace(u"தெ", u"ªî")
    translated = translated.replace(u"தூ", u"É")
    translated = translated.replace(u"து", u"¶")
    translated = translated.replace(u"தீ", u"b")
    translated = translated.replace(u"தி", u"F")
    translated = translated.replace(u"தா", u"î£")
    translated = translated.replace(u"த", u"î")

    # ந Family
    translated = translated.replace(u"ந்", u"‰")
    translated = translated.replace(u"நௌ", u"ªï÷")
    translated = translated.replace(u"நோ", u"«ï£")
    translated = translated.replace(u"நொ", u"ªï£")
    translated = translated.replace(u"நை", u"¬ï")
    translated = translated.replace(u"நே", u"«ï")
    translated = translated.replace(u"நெ", u"ªï")
    translated = translated.replace(u"நூ", u"Ë")
    translated = translated.replace(u"நு", u"¸")
    translated = translated.replace(u"நீ", u"c")
    translated = translated.replace(u"நி", u"G")
    translated = translated.replace(u"நா", u"ï£")
    translated = translated.replace(u"ந", u"ï")

    # ன Family
    translated = translated.replace(u"ன்", u"¡")
    translated = translated.replace(u"னௌ", u"ªù÷")
    translated = translated.replace(u"னோ", u"«ù£")
    translated = translated.replace(u"னொ", u"ªù£")
    translated = translated.replace(u"னை", u"¬ù")
    translated = translated.replace(u"னே", u"«ù")
    translated = translated.replace(u"னெ", u"ªù")
    translated = translated.replace(u"னூ", u"Û")
    translated = translated.replace(u"னு", u"Â")
    translated = translated.replace(u"னீ", u"m")
    translated = translated.replace(u"னி", u"Q")
    translated = translated.replace(u"னா", u"ù£")
    translated = translated.replace(u"ன", u"ù")

    # ப Family
    translated = translated.replace(u"ப்", u"Š")
    translated = translated.replace(u"பௌ", u"ªð÷")
    translated = translated.replace(u"போ", u"«ð£")
    translated = translated.replace(u"பொ", u"ªð£")
    translated = translated.replace(u"பை", u"¬ð")
    translated = translated.replace(u"பே", u"«ð")
    translated = translated.replace(u"பெ", u"ªð")
    translated = translated.replace(u"பூ", u"Ì")
    translated = translated.replace(u"பு", u"¹")
    translated = translated.replace(u"பீ", u"d")
    translated = translated.replace(u"பி", u"H")
    translated = translated.replace(u"பா", u"ð£")
    translated = translated.replace(u"ப", u"ð")

    # ம Family
    translated = translated.replace(u"ம்", u"‹")
    translated = translated.replace(u"மௌ", u"ªñ÷")
    translated = translated.replace(u"மோ", u"«ñ£")
    translated = translated.replace(u"மொ", u"ªñ£")
    translated = translated.replace(u"மை", u"¬ñ")
    translated = translated.replace(u"மே", u"«ñ")
    translated = translated.replace(u"மெ", u"ªñ")
    translated = translated.replace(u"மூ", u"Í")
    translated = translated.replace(u"மு", u"º")
    translated = translated.replace(u"மீ", u"e")
    translated = translated.replace(u"மி", u"I")
    translated = translated.replace(u"மா", u"ñ£")
    translated = translated.replace(u"ம", u"ñ")

    # ய Family
    translated = translated.replace(u"ய்", u"Œ")
    translated = translated.replace(u"யௌ", u"ªò÷")
    translated = translated.replace(u"யோ", u"«ò£")
    translated = translated.replace(u"யொ", u"ªò£")
    translated = translated.replace(u"யை", u"¬ò")
    translated = translated.replace(u"யே", u"«ò")
    translated = translated.replace(u"யெ", u"ªò")
    translated = translated.replace(u"யூ", u"Î")
    translated = translated.replace(u"யு", u"»")
    translated = translated.replace(u"யீ", u"f")
    translated = translated.replace(u"யி", u"J")
    translated = translated.replace(u"யா", u"ò£")
    translated = translated.replace(u"ய", u"ªò£")

    # ர Family
    translated = translated.replace(u"ர்", u"˜")
    translated = translated.replace(u"ரௌ", u"ªó÷")
    translated = translated.replace(u"ரோ", u"«ó£")
    translated = translated.replace(u"ரொ", u"ªó£")
    translated = translated.replace(u"ரை", u"¬ó")
    translated = translated.replace(u"ரே", u"«ó")
    translated = translated.replace(u"ரெ", u"ªó")
    translated = translated.replace(u"ரூ", u"Ï")
    translated = translated.replace(u"ரு", u"¼")
    translated = translated.replace(u"ரீ", u"g")
    translated = translated.replace(u"ரி", u"K")
    translated = translated.replace(u"ரா", u"ó£")
    translated = translated.replace(u"ர", u"ó")

    # ற Family
    translated = translated.replace(u"ற்", u"Ÿ")
    translated = translated.replace(u"றௌ", u"ªø÷")
    translated = translated.replace(u"றோ", u"«ø£")
    translated = translated.replace(u"றொ", u"ªø£")
    translated = translated.replace(u"றை", u"¬ø")
    translated = translated.replace(u"றே", u"«ø")
    translated = translated.replace(u"ரெ", u"ªó")
    translated = translated.replace(u"றூ", u"Ú")
    translated = translated.replace(u"று", u"Á")
    translated = translated.replace(u"றீ", u"l")
    translated = translated.replace(u"றி", u"P")
    translated = translated.replace(u"றா", u"ø£")
    translated = translated.replace(u"ற", u"ø")

    # ல Family
    translated = translated.replace(u"ல்", u"™")
    translated = translated.replace(u"லௌ", u"ªô÷")
    translated = translated.replace(u"லோ", u"«ô£")
    translated = translated.replace(u"லொ", u"ªô£")
    translated = translated.replace(u"லை", u"¬ô")
    translated = translated.replace(u"லே", u"«ô")
    translated = translated.replace(u"லெ", u"ªô")
    translated = translated.replace(u"லூ", u"Ö")
    translated = translated.replace(u"லு", u"½")
    translated = translated.replace(u"லீ", u"h")
    translated = translated.replace(u"லி", u"L")
    translated = translated.replace(u"லா", u"ô£")
    translated = translated.replace(u"ல", u"ô")

    # ள Family
    translated = translated.replace(u"ள்", u"œ")
    translated = translated.replace(u"ளௌ", u"ª÷÷")
    translated = translated.replace(u"ளோ", u"«÷£")
    translated = translated.replace(u"ளை", u"¬÷")
    translated = translated.replace(u"ளே", u"«÷")
    translated = translated.replace(u"ளெ", u"ª÷")
    translated = translated.replace(u"ளூ", u"Ù")
    translated = translated.replace(u"ளு", u"À")
    translated = translated.replace(u"ளீ", u"k")
    translated = translated.replace(u"ளி", u"O")
    translated = translated.replace(u"ளா", u"÷£")
    translated = translated.replace(u"ள", u"ª÷£")

    # ழ Family
    translated = translated.replace(u"ழ்", u"›")
    translated = translated.replace(u"ழௌ", u"ªö÷")
    translated = translated.replace(u"ழோ", u"«ö£")
    translated = translated.replace(u"ழொ", u"ªö£")
    translated = translated.replace(u"ழை", u"¬ö")
    translated = translated.replace(u"ழே", u"«ö")
    translated = translated.replace(u"ழெ", u"ªö")
    translated = translated.replace(u"ழூ", u"Ø")
    translated = translated.replace(u"ழு", u"¿")
    translated = translated.replace(u"ழீ", u"j")
    translated = translated.replace(u"ழி", u"N")
    translated = translated.replace(u"ழா", u"ö£")
    translated = translated.replace(u"ழ", u"ö")

    # வ Family
    translated = translated.replace(u"வ்", u"š")
    translated = translated.replace(u"வௌ", u"ªõ÷")
    translated = translated.replace(u"வோ", u"«õ£")
    translated = translated.replace(u"வொ", u"ªõ£")
    translated = translated.replace(u"வை", u"¬õ")
    translated = translated.replace(u"வே", u"«õ")
    translated = translated.replace(u"வெ", u"ªõ")
    translated = translated.replace(u"வூ", u"×")
    translated = translated.replace(u"வு", u"¾")
    translated = translated.replace(u"வீ", u"i")
    translated = translated.replace(u"வி", u"M")
    translated = translated.replace(u"வா", u"õ£")
    translated = translated.replace(u"வ", u"õ")

    # ஷ Family
    translated = translated.replace(u"ஷ்", u"w")
    translated = translated.replace(u"ஷௌ", u"ªû÷")
    translated = translated.replace(u"ஷோ", u"«û£")
    translated = translated.replace(u"ஷொ", u"ªû£")
    translated = translated.replace(u"ஷை", u"¬û")
    translated = translated.replace(u"ஷே", u"«û")
    translated = translated.replace(u"ஷெ", u"ªû")
    translated = translated.replace(u"ஷீ", u"o")
    translated = translated.replace(u"ஷி", u"S")
    translated = translated.replace(u"ஷா", u"û£")
    translated = translated.replace(u"ஷ", u"û")

    # ஸ Family
    translated = translated.replace(u"ஸ்", u"v")
    translated = translated.replace(u"ஸௌ", u"ªú÷")
    translated = translated.replace(u"ஸோ", u"«ú£")
    translated = translated.replace(u"ஸொ", u"ªú£")
    translated = translated.replace(u"ஸை", u"¬ú")
    translated = translated.replace(u"ஸே", u"«ú")
    translated = translated.replace(u"ஸெ", u"ªú")
    translated = translated.replace(u"ஸீ", u"n")
    translated = translated.replace(u"ஸி", u"R")
    translated = translated.replace(u"ஸா", u"ú£")
    translated = translated.replace(u"ஸ", u"ú")

    # ஹ Family
    translated = translated.replace(u"ஹ்", u"y")
    translated = translated.replace(u"ஹௌ", u"ªý÷")
    translated = translated.replace(u"ஹோ", u"«ý£")
    translated = translated.replace(u"ஹொ", u"ªý£")
    translated = translated.replace(u"ஹை", u"¬ý")
    translated = translated.replace(u"ஹே", u"«ý")
    translated = translated.replace(u"ஹெ", u"ªý")
    translated = translated.replace(u"ஹீ", u"q")
    translated = translated.replace(u"ஹி", u"U")
    translated = translated.replace(u"ஹா", u"ý£")
    translated = translated.replace(u"ஹ", u"ý")

    unconverted = [i for i in translated if i in source_text and not i in
                    punctuation+whitespace+digits]
    translated_trimed = ''.join([i for i in translated if not i in unconverted])

    if debug:
        return unconverted
    elif filtered:
        return translated_trimed
    else:
        return translated

