# -*- coding: utf-8 -*-
from string import punctuation, whitespace, digits


def convertToanjal(source_text, filtered=False, debug=False):
    translated = source_text
    # Independent Vowels
    translated = translated.replace(u"அ", u"")
    translated = translated.replace(u"ஆ", u"‚")
    translated = translated.replace(u"இ", u"ƒ")
    translated = translated.replace(u"ஈ", u"„")
    translated = translated.replace(u"உ", u"…")
    translated = translated.replace(u"ஊ", u"†")
    translated = translated.replace(u"எ", u"‡")
    translated = translated.replace(u"ஏ", u"ˆ")
    translated = translated.replace(u"ஐ", u"‰")
    translated = translated.replace(u"ஒ", u"Š")
    translated = translated.replace(u"ஓ", u"‹")
    translated = translated.replace(u"ஔ", u"Šã")
    translated = translated.replace(u"ஃ", u"Œ")

    # க Family
    translated = translated.replace(u"க்", u"")
    translated = translated.replace(u"கௌ", u"—ã")
    translated = translated.replace(u"கோ", u"þ‘")
    translated = translated.replace(u"கொ", u"—‘")
    translated = translated.replace(u"கை", u"€")
    translated = translated.replace(u"கே", u"þ")
    translated = translated.replace(u"கெ", u"—")
    translated = translated.replace(u"கூ", u"˜")
    translated = translated.replace(u"கு", u"")
    translated = translated.replace(u"கீ", u"")
    translated = translated.replace(u"கி", u"Ž")
    translated = translated.replace(u"கா", u"‘")
    translated = translated.replace(u"க", u"")

    # ங Family
    translated = translated.replace(u"ங்", u"›")
    translated = translated.replace(u"ஙௌ", u"—šã")
    translated = translated.replace(u"ஙோ", u"þš‘")
    translated = translated.replace(u"ஙொ", u"—š‘")
    translated = translated.replace(u"ஙை", u"€š")
    translated = translated.replace(u"ஙே", u"þš")
    translated = translated.replace(u"ஙெ", u"—š")
    translated = translated.replace(u"ஙீ", u"š")
    translated = translated.replace(u"ஙி", u"š")
    translated = translated.replace(u"ஙா", u"š‘")
    translated = translated.replace(u"ங", u"š")

    # ச Family
    translated = translated.replace(u"ச்", u"¢")
    translated = translated.replace(u"சௌ", u"—œã")
    translated = translated.replace(u"சோ", u"þœ‘")
    translated = translated.replace(u"சொ", u"—œ‘")
    translated = translated.replace(u"சை", u"€œ")
    translated = translated.replace(u"சே", u"þœ")
    translated = translated.replace(u"செ", u"—œ")
    translated = translated.replace(u"சூ", u"¡")
    translated = translated.replace(u"சு", u"Ÿ")
    translated = translated.replace(u"சீ", u"")
    translated = translated.replace(u"சி", u"")
    translated = translated.replace(u"சா", u"œ‘")
    translated = translated.replace(u"ச", u"œ")

    # ஜ Family
    translated = translated.replace(u"ஜ்", u"ô")
    translated = translated.replace(u"ஜௌ", u"—óó")
    translated = translated.replace(u"ஜோ", u"þó‘")
    translated = translated.replace(u"ஜொ", u"—ó‘")
    translated = translated.replace(u"ஜை", u"€ó")
    translated = translated.replace(u"ஜே", u"þó")
    translated = translated.replace(u"ஜெ", u"—ó")
    translated = translated.replace(u"ஜூ", u"ó•")
    translated = translated.replace(u"ஜு", u"ó”")
    translated = translated.replace(u"ஜீ", u"ó")
    translated = translated.replace(u"ஜி", u"ó")
    translated = translated.replace(u"ஜா", u"ó‘")
    translated = translated.replace(u"ஜ", u"ó")

    # ஞ Family
    translated = translated.replace(u"ஞ்", u"¤")
    translated = translated.replace(u"ஞௌ", u"—£ã")
    translated = translated.replace(u"ஞோ", u"þ£‘")
    translated = translated.replace(u"ஞொ", u"—£‘")
    translated = translated.replace(u"ஞை", u"€£")
    translated = translated.replace(u"ஞே", u"þ£")
    translated = translated.replace(u"ஞெ", u"—£")
    translated = translated.replace(u"ஞீ", u"£")
    translated = translated.replace(u"ஞி", u"£")
    translated = translated.replace(u"ஞா", u"£‘")
    translated = translated.replace(u"ஞ", u"£")

    # ட Family
    translated = translated.replace(u"ட்", u"ª")
    translated = translated.replace(u"டௌ", u"—¥ã")
    translated = translated.replace(u"டோ", u"þ¥‘")
    translated = translated.replace(u"டொ", u"—¥‘")
    translated = translated.replace(u"டை", u"€¥")
    translated = translated.replace(u"டே", u"þ¥")
    translated = translated.replace(u"டெ", u"—¥")
    translated = translated.replace(u"டூ", u"©")
    translated = translated.replace(u"டு", u"¨")
    translated = translated.replace(u"டீ", u"§")
    translated = translated.replace(u"டி", u"¦")
    translated = translated.replace(u"டா", u"¥‘")
    translated = translated.replace(u"ட", u"¥")

    # ண Family
    translated = translated.replace(u"ண்", u"¯")
    translated = translated.replace(u"ணௌ", u"—«ã")
    translated = translated.replace(u"ணோ", u"þ«‘")
    translated = translated.replace(u"ணொ", u"—«‘")
    translated = translated.replace(u"ணை", u"€«")
    translated = translated.replace(u"ணே", u"þ«")
    translated = translated.replace(u"ணெ", u"—«")
    translated = translated.replace(u"ணூ", u"®–")
    translated = translated.replace(u"ணு", u"®")
    translated = translated.replace(u"ணீ", u"−")
    translated = translated.replace(u"ணி", u"¬")
    translated = translated.replace(u"ணா", u"«‘")
    translated = translated.replace(u"ண", u"«")

    # த Family
    translated = translated.replace(u"த்", u"´")
    translated = translated.replace(u"தௌ", u"—°ã")
    translated = translated.replace(u"தோ", u"þ°‘")
    translated = translated.replace(u"தொ", u"—°‘")
    translated = translated.replace(u"தை", u"€°")
    translated = translated.replace(u"தே", u"þ°")
    translated = translated.replace(u"தெ", u"—°")
    translated = translated.replace(u"தூ", u"³–")
    translated = translated.replace(u"து", u"³")
    translated = translated.replace(u"தீ", u"²")
    translated = translated.replace(u"தி", u"±")
    translated = translated.replace(u"தா", u"°‘")
    translated = translated.replace(u"த", u"°")

    # ந Family
    translated = translated.replace(u"ந்", u"¹")
    translated = translated.replace(u"நௌ", u"—µã")
    translated = translated.replace(u"நோ", u"þµ‘")
    translated = translated.replace(u"நொ", u"—µ‘")
    translated = translated.replace(u"நை", u"€µ")
    translated = translated.replace(u"நே", u"þµ")
    translated = translated.replace(u"நெ", u"—µ")
    translated = translated.replace(u"நூ", u"¸–")
    translated = translated.replace(u"நு", u"¸")
    translated = translated.replace(u"நீ", u"ÿ")
    translated = translated.replace(u"நி", u"¶")
    translated = translated.replace(u"நா", u"µ‘")
    translated = translated.replace(u"ந", u"µ")

    # ன Family
    translated = translated.replace(u"ன்", u"ò")
    translated = translated.replace(u"னௌ", u"—îã")
    translated = translated.replace(u"னோ", u"þî‘")
    translated = translated.replace(u"னொ", u"—î‘")
    translated = translated.replace(u"னை", u"€î")
    translated = translated.replace(u"னே", u"þî")
    translated = translated.replace(u"னெ", u"—î")
    translated = translated.replace(u"னூ", u"ñ–")
    translated = translated.replace(u"னு", u"ñ")
    translated = translated.replace(u"னீ", u"ð")
    translated = translated.replace(u"னி", u"ï")
    translated = translated.replace(u"னா", u"î‘")
    translated = translated.replace(u"ன", u"î")

    # ப Family
    translated = translated.replace(u"ப்", u"¿")
    translated = translated.replace(u"பௌ", u"—ºã")
    translated = translated.replace(u"போ", u"þº‘")
    translated = translated.replace(u"பொ", u"—º‘")
    translated = translated.replace(u"பை", u"€º")
    translated = translated.replace(u"பே", u"þº")
    translated = translated.replace(u"பெ", u"—º")
    translated = translated.replace(u"பூ", u"¾")
    translated = translated.replace(u"பு", u"½")
    translated = translated.replace(u"பீ", u"¼")
    translated = translated.replace(u"பி", u"»")
    translated = translated.replace(u"பா", u"º‘")
    translated = translated.replace(u"ப", u"º")

    # ம Family
    translated = translated.replace(u"ம்", u"Å")
    translated = translated.replace(u"மௌ", u"—Àã")
    translated = translated.replace(u"மோ", u"þÀ‘")
    translated = translated.replace(u"மொ", u"—À‘")
    translated = translated.replace(u"மை", u"€À")
    translated = translated.replace(u"மே", u"þÀ")
    translated = translated.replace(u"மெ", u"—À")
    translated = translated.replace(u"மூ", u"Ä")
    translated = translated.replace(u"மு", u"Ã")
    translated = translated.replace(u"மீ", u"Â")
    translated = translated.replace(u"மி", u"Á")
    translated = translated.replace(u"மா", u"À‘")
    translated = translated.replace(u"ம", u"À")

    # ய Family
    translated = translated.replace(u"ய்", u"Ë")
    translated = translated.replace(u"யௌ", u"—Æã")
    translated = translated.replace(u"யோ", u"þÆ‘")
    translated = translated.replace(u"யொ", u"—Æ‘")
    translated = translated.replace(u"யை", u"€Æ")
    translated = translated.replace(u"யே", u"þÆ")
    translated = translated.replace(u"யெ", u"—Æ")
    translated = translated.replace(u"யூ", u"Ê")
    translated = translated.replace(u"யு", u"É")
    translated = translated.replace(u"யீ", u"È")
    translated = translated.replace(u"யி", u"Ç")
    translated = translated.replace(u"யா", u"Æ‘")
    translated = translated.replace(u"ய", u"Æ")

    # ர Family
    translated = translated.replace(u"ர்", u"Ñ")
    translated = translated.replace(u"ரௌ", u"—Ìã")
    translated = translated.replace(u"ரோ", u"þÌ‘")
    translated = translated.replace(u"ரொ", u"—Ì‘")
    translated = translated.replace(u"ரை", u"€Ì")
    translated = translated.replace(u"ரே", u"þÌ")
    translated = translated.replace(u"ரெ", u"—Ì")
    translated = translated.replace(u"ரூ", u"Ð")
    translated = translated.replace(u"ரு", u"Ï")
    translated = translated.replace(u"ரீ", u"Î")
    translated = translated.replace(u"ரி", u"Í")
    translated = translated.replace(u"ரா", u"Ì‘")
    translated = translated.replace(u"ர", u"Ì")

    # ற Family
    translated = translated.replace(u"ற்", u"í")
    translated = translated.replace(u"றௌ", u"—éé")
    translated = translated.replace(u"றோ", u"þé‘")
    translated = translated.replace(u"றொ", u"—é‘")
    translated = translated.replace(u"றை", u"€é")
    translated = translated.replace(u"றே", u"þé")
    translated = translated.replace(u"ரெ", u"—Ì")
    translated = translated.replace(u"றூ", u"ì–")
    translated = translated.replace(u"று", u"ì")
    translated = translated.replace(u"றீ", u"ë")
    translated = translated.replace(u"றி", u"ê")
    translated = translated.replace(u"றா", u"é‘")
    translated = translated.replace(u"ற", u"é")

    # ல Family
    translated = translated.replace(u"ல்", u"Ö")
    translated = translated.replace(u"லௌ", u"—Òã")
    translated = translated.replace(u"லோ", u"þÒ‘")
    translated = translated.replace(u"லொ", u"—Ò‘")
    translated = translated.replace(u"லை", u"€Ò")
    translated = translated.replace(u"லே", u"þÒ")
    translated = translated.replace(u"லெ", u"—Ò")
    translated = translated.replace(u"லூ", u"Õ–")
    translated = translated.replace(u"லு", u"Õ")
    translated = translated.replace(u"லீ", u"Ô")
    translated = translated.replace(u"லி", u"Ó")
    translated = translated.replace(u"லா", u"Ò‘")
    translated = translated.replace(u"ல", u"Ò")

    # ள Family
    translated = translated.replace(u"ள்", u"è")
    translated = translated.replace(u"ளௌ", u"—ãã")
    translated = translated.replace(u"ளோ", u"þã‘")
    translated = translated.replace(u"ளை", u"€ã")
    translated = translated.replace(u"ளே", u"þã")
    translated = translated.replace(u"ளெ", u"—ã")
    translated = translated.replace(u"ளூ", u"ç")
    translated = translated.replace(u"ளு", u"æ")
    translated = translated.replace(u"ளீ", u"å")
    translated = translated.replace(u"ளி", u"ä")
    translated = translated.replace(u"ளா", u"ã‘")
    translated = translated.replace(u"ள", u"ã")

    # ழ Family
    translated = translated.replace(u"ழ்", u"â")
    translated = translated.replace(u"ழௌ", u"—ÝÝ")
    translated = translated.replace(u"ழோ", u"þÝ‘")
    translated = translated.replace(u"ழொ", u"—Ý‘")
    translated = translated.replace(u"ழை", u"€Ý")
    translated = translated.replace(u"ழே", u"þÝ")
    translated = translated.replace(u"ழெ", u"—Ý")
    translated = translated.replace(u"ழூ", u"á")
    translated = translated.replace(u"ழு", u"à")
    translated = translated.replace(u"ழீ", u"ß")
    translated = translated.replace(u"ழி", u"Þ")
    translated = translated.replace(u"ழா", u"Ý‘")
    translated = translated.replace(u"ழ", u"Ý")

    # வ Family
    translated = translated.replace(u"வ்", u"Ü")
    translated = translated.replace(u"வௌ", u"—××")
    translated = translated.replace(u"வோ", u"þ×‘")
    translated = translated.replace(u"வொ", u"—×‘")
    translated = translated.replace(u"வை", u"€×")
    translated = translated.replace(u"வே", u"þ×")
    translated = translated.replace(u"வெ", u"—×")
    translated = translated.replace(u"வூ", u"Û")
    translated = translated.replace(u"வு", u"Ú")
    translated = translated.replace(u"வீ", u"Ù")
    translated = translated.replace(u"வி", u"Ø")
    translated = translated.replace(u"வா", u"×‘")
    translated = translated.replace(u"வ", u"×")

    # ஷ Family
    translated = translated.replace(u"ஷ்", u"è")
    translated = translated.replace(u"ஷௌ", u"öåå")
    translated = translated.replace(u"ஷோ", u"÷åõ")
    translated = translated.replace(u"ஷொ", u"öåõ")
    translated = translated.replace(u"ஷை", u"øå")
    translated = translated.replace(u"ஷே", u"÷å")
    translated = translated.replace(u"ஷெ", u"öå")
    translated = translated.replace(u"ஷீ", u"ç")
    translated = translated.replace(u"ஷி", u"æ")
    translated = translated.replace(u"ஷா", u"åõ")
    translated = translated.replace(u"ஷ", u"å")

    # ஸ Family
    translated = translated.replace(u"ஸ்", u"ø")
    translated = translated.replace(u"ஸௌ", u"—÷÷")
    translated = translated.replace(u"ஸோ", u"þ÷‘")
    translated = translated.replace(u"ஸொ", u"—÷‘")
    translated = translated.replace(u"ஸை", u"€÷")
    translated = translated.replace(u"ஸே", u"þ÷")
    translated = translated.replace(u"ஸெ", u"—÷")
    translated = translated.replace(u"ஸீ", u"÷")
    translated = translated.replace(u"ஸி", u"÷")
    translated = translated.replace(u"ஸா", u"÷‘")
    translated = translated.replace(u"ஸ", u"÷")

    # ஹ Family
    translated = translated.replace(u"ஹ்", u"ú")
    translated = translated.replace(u"ஹௌ", u"—ùù")
    translated = translated.replace(u"ஹோ", u"þù‘")
    translated = translated.replace(u"ஹொ", u"—ù‘")
    translated = translated.replace(u"ஹை", u"€ù")
    translated = translated.replace(u"ஹே", u"þù")
    translated = translated.replace(u"ஹெ", u"—ù")
    translated = translated.replace(u"ஹீ", u"ù")
    translated = translated.replace(u"ஹி", u"ù")
    translated = translated.replace(u"ஹா", u"ù‘")
    translated = translated.replace(u"ஹ", u"ù")

    unconverted = [i for i in translated if i in source_text and not i in
                    punctuation+whitespace+digits]
    translated_trimed = ''.join([i for i in translated if not i in unconverted])

    if debug:
        return unconverted
    elif filtered:
        return translated_trimed
    else:
        return translated