# -*- coding: utf-8 -*-
from string import punctuation, whitespace, digits


def convertToanu(source_text, filtered=False, debug=False):
    translated = source_text
    
    translated = translated.replace(u"அ", u"Ã‚Â¶")
    translated = translated.replace(u"ஆ", u"g")
    translated = translated.replace(u"இ", u"Ãƒâ€“")
    translated = translated.replace(u"ஈ", u"~")
    translated = translated.replace(u"உ", u"c")
    translated = translated.replace(u"ஊ", u"Ã‚Â»")
    translated = translated.replace(u"எ", u"Ã‚Â¨")
    translated = translated.replace(u"ஏ", u"Ã‚Â°")
    translated = translated.replace(u"ஐ", u"n")
    translated = translated.replace(u"ஒ", u"ÃƒÅ½")
    translated = translated.replace(u"ஓ", u"{")
    translated = translated.replace(u"ஔ", u"ÃƒÅ½e")
    translated = translated.replace(u"ஃ", u"ÃƒÂ ")
    translated = translated.replace(u"ௐ", u"--")
    translated = translated.replace(u"ஸ்ரீ", u"p")
    
    translated = translated.replace(u"க்", u"Ãƒâ€š")
    translated = translated.replace(u"கௌ", u"ÃƒËœÃƒÂ¯e")
    translated = translated.replace(u"கோ", u"Ã‚Â¼ÃƒÂ¯V")
    translated = translated.replace(u"கொ", u"ÃƒËœÃƒÂ¯V")
    translated = translated.replace(u"கை", u"ÃƒÂ§ÃƒÂ¯")
    translated = translated.replace(u"கே", u"Ã‚Â¼ÃƒÂ¯")
    translated = translated.replace(u"கெ", u"ÃƒËœÃƒÂ¯")
    translated = translated.replace(u"கூ", u"ÃƒÂ­")
    translated = translated.replace(u"கு", u"z")
    translated = translated.replace(u"கீ", u"ÃƒÂ¿")
    translated = translated.replace(u"கி", u"ÃƒÂ¾")
    translated = translated.replace(u"கா", u"ÃƒÂ¯V")
    translated = translated.replace(u"க", u"ÃƒÂ¯")
    
    translated = translated.replace(u"ங்", u"Ã‚Âº")
    translated = translated.replace(u"ஙௌ", u"ÃƒËœÃƒÂ´e")
    translated = translated.replace(u"ஙோ", u"Ã‚Â¼ÃƒÂ´V")
    translated = translated.replace(u"ஙொ", u"ÃƒËœÃƒÂ´V")
    translated = translated.replace(u"ஙை", u"ÃƒÂ§ÃƒÂ´")
    translated = translated.replace(u"ஙே", u"Ã‚Â¼ÃƒÂ´")
    translated = translated.replace(u"ஙெ", u"ÃƒËœÃƒÂ´")
    translated = translated.replace(u"ஙூ", u"dd")
    translated = translated.replace(u"ஙு", u"dd")
    translated = translated.replace(u"ஙீ", u"dd")
    translated = translated.replace(u"ஙி", u"dd")
    translated = translated.replace(u"ஙா", u"ÃƒÂ´V")
    translated = translated.replace(u"ங", u"ÃƒÂ´")
    
    translated = translated.replace(u"ச்", u"ÃƒÅ¸")
    translated = translated.replace(u"சௌ", u"ÃƒËœÃƒâ€že")
    translated = translated.replace(u"சோ", u"Ã‚Â¼Ãƒâ€žV")
    translated = translated.replace(u"சொ", u"ÃƒËœÃƒâ€žV")
    translated = translated.replace(u"சை", u"ÃƒÂ§Ãƒâ€ž")
    translated = translated.replace(u"சே", u"Ã‚Â¼Ãƒâ€ž")
    translated = translated.replace(u"செ", u"ÃƒËœÃƒâ€ž")
    translated = translated.replace(u"சூ", u"ÃƒÂ³")
    translated = translated.replace(u"சு", u"Ã‚Â·")
    translated = translated.replace(u"சீ", u"ÃƒÂ¦")
    translated = translated.replace(u"சி", u"E")
    translated = translated.replace(u"சா", u"Ãƒâ€žV")
    translated = translated.replace(u"ச", u"Ãƒâ€ž")
    
    translated = translated.replace(u"ஜ்", u"ÃƒÂ«")
    translated = translated.replace(u"ஜௌ", u"ÃƒËœÃƒâ€ºe")
    translated = translated.replace(u"ஜோ", u"Ã‚Â¼Ãƒâ€ºV")
    translated = translated.replace(u"ஜொ", u"ÃƒËœÃƒâ€ºV")
    translated = translated.replace(u"ஜை", u"ÃƒÂ§Ãƒâ€º")
    translated = translated.replace(u"ஜே", u"Ã‚Â¼Ãƒâ€º")
    translated = translated.replace(u"ஜெ", u"ÃƒËœÃƒâ€º")
    translated = translated.replace(u"ஜூ", u"Ãƒâ€°")
    translated = translated.replace(u"ஜு", u"h")
    translated = translated.replace(u"ஜீ", u"ÃƒÂ½")
    translated = translated.replace(u"ஜி", u"ÃƒÂ·")
    translated = translated.replace(u"ஜா", u"Ãƒâ€ºV")
    translated = translated.replace(u"ஜ", u"Ãƒâ€º")
    
    translated = translated.replace(u"ஞ்", u"ÃƒÅ¾")
    translated = translated.replace(u"ஞௌ", u"ÃƒËœQe")
    translated = translated.replace(u"ஞோ", u"Ã‚Â¼QV")
    translated = translated.replace(u"ஞொ", u"ÃƒËœQV")
    translated = translated.replace(u"ஞை", u"ÃƒÂ§Q")
    translated = translated.replace(u"ஞே", u"Ã‚Â¼Q")
    translated = translated.replace(u"ஞெ", u"ÃƒËœQ")
    translated = translated.replace(u"ஞூ", u"dd")
    translated = translated.replace(u"ஞு", u"dd")
    translated = translated.replace(u"ஞீ", u"dd")
    translated = translated.replace(u"ஞி", u"dd")
    translated = translated.replace(u"ஞா", u"QV")
    translated = translated.replace(u"ஞ", u"Q")
    
    translated = translated.replace(u"ட்", u"ÃƒÂ¢")
    translated = translated.replace(u"டௌ", u"ÃƒËœÃ‚Â¦e")
    translated = translated.replace(u"டோ", u"Ã‚Â¼Ã‚Â¦V")
    translated = translated.replace(u"டொ", u"ÃƒËœÃ‚Â¦V")
    translated = translated.replace(u"டை", u"ÃƒÂ§Ã‚Â¦")
    translated = translated.replace(u"டே", u"Ã‚Â¼Ã‚Â¦")
    translated = translated.replace(u"டெ", u"ÃƒËœÃ‚Â¦")
    translated = translated.replace(u"டூ", u"ÃƒÂ¹")
    translated = translated.replace(u"டு", u"|")
    translated = translated.replace(u"டீ", u"Ãƒ")
    translated = translated.replace(u"டி", u"Ã‚Â½")
    translated = translated.replace(u"டா", u"Ã‚Â¦V")
    translated = translated.replace(u"ட", u"Ã‚Â¦")
    
    translated = translated.replace(u"ண்", u"ÃƒÂµ")
    translated = translated.replace(u"ணௌ", u"ÃƒËœÃƒÂ°e")
    translated = translated.replace(u"ணோ", u"Ã‚Â¼ÃƒÂ°V")
    translated = translated.replace(u"ணொ", u"ÃƒËœÃƒÂ°V")
    translated = translated.replace(u"ணை", u"ÃƒÂ§ÃƒÂ°")
    translated = translated.replace(u"ணே", u"Ã‚Â¼ÃƒÂ°")
    translated = translated.replace(u"ணெ", u"ÃƒËœÃƒÂ°")
    translated = translated.replace(u"ணூ", u"dd")
    translated = translated.replace(u"ணு", u"b")
    translated = translated.replace(u"ணீ", u"Ã‚Â§")
    translated = translated.replace(u"ணி", u"ÃƒÂ¨")
    translated = translated.replace(u"ணா", u"ÃƒÂ°V")
    translated = translated.replace(u"ண", u"ÃƒÂ°")
    
    translated = translated.replace(u"த்", u"Ãƒ")
    translated = translated.replace(u"தௌ", u"ÃƒËœ>e")
    translated = translated.replace(u"தோ", u"Ã‚Â¼>V")
    translated = translated.replace(u"தொ", u"ÃƒËœ>V")
    translated = translated.replace(u"தை", u"ÃƒÂ§>")
    translated = translated.replace(u"தே", u"Ã‚Â¼>")
    translated = translated.replace(u"தெ", u"ÃƒËœ>")
    translated = translated.replace(u"தூ", u"#")
    translated = translated.replace(u"து", u"m")
    translated = translated.replace(u"தீ", u"y")
    translated = translated.replace(u"தி", u"]")
    translated = translated.replace(u"தா", u">V")
    translated = translated.replace(u"த", u">")
    
    translated = translated.replace(u"ந்", u"Ãƒ")
    translated = translated.replace(u"நௌ", u"ÃƒËœÃƒÂ¥e")
    translated = translated.replace(u"நோ", u"Ã‚Â¼ÃƒÂ¥V")
    translated = translated.replace(u"நொ", u"ÃƒËœÃƒÂ¥V")
    translated = translated.replace(u"நை", u"ÃƒÂ§ÃƒÂ¥")
    translated = translated.replace(u"நே", u"Ã‚Â¼ÃƒÂ¥")
    translated = translated.replace(u"நெ", u"ÃƒËœÃƒÂ¥")
    translated = translated.replace(u"நூ", u"Ã‚Â±")
    translated = translated.replace(u"நு", u"O")
    translated = translated.replace(u"நீ", u"Ãƒâ‚¬")
    translated = translated.replace(u"நி", u"W")
    translated = translated.replace(u"நா", u"ÃƒÂ¥V")
    translated = translated.replace(u"ந", u"ÃƒÂ¥")
    
    translated = translated.replace(u"ன்", u"[")
    translated = translated.replace(u"னௌ", u"ÃƒËœÃ‚Âªe")
    translated = translated.replace(u"னோ", u"Ã‚Â¼Ã‚ÂªV")
    translated = translated.replace(u"னொ", u"ÃƒËœÃ‚ÂªV")
    translated = translated.replace(u"னை", u"ÃƒÂ§Ã‚Âª")
    translated = translated.replace(u"னே", u"Ã‚Â¼Ã‚Âª")
    translated = translated.replace(u"னெ", u"ÃƒËœÃ‚Âª")
    translated = translated.replace(u"னூ", u"ÃƒÂ»")
    translated = translated.replace(u"னு", u"Ãƒ")
    translated = translated.replace(u"னீ", u"ÃƒÅ’")
    translated = translated.replace(u"னி", u"M")
    translated = translated.replace(u"னா", u"Ã‚ÂªV")
    translated = translated.replace(u"ன", u"Ã‚Âª")
    
    translated = translated.replace(u"ப்", u"Ã‚Â©")
    translated = translated.replace(u"பௌ", u"ÃƒËœÃƒÆ’e")
    translated = translated.replace(u"போ", u"Ã‚Â¼ÃƒÆ’V")
    translated = translated.replace(u"பொ", u"ÃƒËœÃƒÆ’V")
    translated = translated.replace(u"பை", u"ÃƒÂ§ÃƒÆ’")
    translated = translated.replace(u"பே", u"Ã‚Â¼ÃƒÆ’")
    translated = translated.replace(u"பெ", u"ÃƒËœÃƒÆ’")
    translated = translated.replace(u"பூ", u"Ã‚Â¯")
    translated = translated.replace(u"பு", u"A")
    translated = translated.replace(u"பீ", u"Ã‚Â¬")
    translated = translated.replace(u"பி", u"Ã‚Â¸")
    translated = translated.replace(u"பா", u"ÃƒÆ’V")
    translated = translated.replace(u"ப", u"ÃƒÆ’")
    
    translated = translated.replace(u"ம்", u"D")
    translated = translated.replace(u"மௌ", u"ÃƒËœ\e")
    translated = translated.replace(u"மோ", u"Ã‚Â¼\V")
    translated = translated.replace(u"மொ", u"ÃƒËœ\V")
    translated = translated.replace(u"மை", u"ÃƒÂ§\\")
    translated = translated.replace(u"மே", u"Ã‚Â¼\\")
    translated = translated.replace(u"மெ", u"ÃƒËœ\\")
    translated = translated.replace(u"மூ", u"J")
    translated = translated.replace(u"மு", u"x")
    translated = translated.replace(u"மீ", u"*")
    translated = translated.replace(u"மி", u"t")
    translated = translated.replace(u"மா", u"\V")
    translated = translated.replace(u"ம", u"\\")
    
    translated = translated.replace(u"ய்", u"F")
    translated = translated.replace(u"யௌ", u"ÃƒËœBe")
    translated = translated.replace(u"யோ", u"Ã‚Â¼BV")
    translated = translated.replace(u"யொ", u"ÃƒËœBV")
    translated = translated.replace(u"யை", u"ÃƒÂ§B")
    translated = translated.replace(u"யே", u"Ã‚Â¼B")
    translated = translated.replace(u"யெ", u"ÃƒËœB")
    translated = translated.replace(u"யூ", u"R")
    translated = translated.replace(u"யு", u"Ã‚Â¥")
    translated = translated.replace(u"யீ", u"X")
    translated = translated.replace(u"யி", u"l")
    translated = translated.replace(u"யா", u"BV")
    translated = translated.replace(u"ய", u"B")
    
    translated = translated.replace(u"ர்", u"ÃƒÂ¬")
    translated = translated.replace(u"ரௌ", u"ÃƒËœÃ‚Â«e")
    translated = translated.replace(u"ரோ", u"Ã‚Â¼Ã‚Â«V")
    translated = translated.replace(u"ரொ", u"ÃƒËœÃ‚Â«V")
    translated = translated.replace(u"ரை", u"ÃƒÂ§Ã‚Â«")
    translated = translated.replace(u"ரே", u"Ã‚Â¼Ã‚Â«")
    translated = translated.replace(u"ரெ", u"ÃƒËœÃ‚Â«")
    translated = translated.replace(u"ரூ", u"Ãƒâ€")
    translated = translated.replace(u"ரு", u"ÃƒÂ²")
    translated = translated.replace(u"ரீ", u"Z")
    translated = translated.replace(u"ரி", u"ÃƒÂ¶")
    translated = translated.replace(u"ரா", u"Ã‚Â«V")
    translated = translated.replace(u"ர", u"Ã‚Â«")
    
    translated = translated.replace(u"ற்", u"u")
    translated = translated.replace(u"றௌ", u"ÃƒËœÃƒâ€¦e")
    translated = translated.replace(u"றோ", u"Ã‚Â¼Ãƒâ€¦V")
    translated = translated.replace(u"றொ", u"ÃƒËœÃƒâ€¦V")
    translated = translated.replace(u"றை", u"ÃƒÂ§Ãƒâ€¦")
    translated = translated.replace(u"றே", u"Ã‚Â¼Ãƒâ€¦")
    translated = translated.replace(u"ரெ", u"ÃƒËœÃ‚Â«")
    translated = translated.replace(u"றூ", u"G")
    translated = translated.replace(u"று", u"Ã‚Â®")
    translated = translated.replace(u"றீ", u"S")
    translated = translated.replace(u"றி", u"Ã‚Â¤")
    translated = translated.replace(u"றா", u"Ãƒâ€¦V")
    translated = translated.replace(u"ற", u"Ãƒâ€¦")
    
    translated = translated.replace(u"ல்", u"_")
    translated = translated.replace(u"லௌ", u"ÃƒËœÃƒÂ©e")
    translated = translated.replace(u"லோ", u"Ã‚Â¼ÃƒÂ©V")
    translated = translated.replace(u"லொ", u"ÃƒËœÃƒÂ©V")
    translated = translated.replace(u"லை", u"ÃƒÂ§ÃƒÂ©")
    translated = translated.replace(u"லே", u"Ã‚Â¼ÃƒÂ©")
    translated = translated.replace(u"லெ", u"ÃƒËœÃƒÂ©")
    translated = translated.replace(u"லூ", u"Ãƒâ„¢")
    translated = translated.replace(u"லு", u"K")
    translated = translated.replace(u"லீ", u"ÃƒÅ“")
    translated = translated.replace(u"லி", u"o")
    translated = translated.replace(u"லா", u"ÃƒÂ©V")
    translated = translated.replace(u"ல", u"ÃƒÂ©")
    
    translated = translated.replace(u"ள்", u"^")
    translated = translated.replace(u"ளௌ", u"ÃƒËœee")
    translated = translated.replace(u"ளோ", u"Ã‚Â¼eV")
    translated = translated.replace(u"ளொ", u"ÃƒËœeV")
    translated = translated.replace(u"ளை", u"ÃƒÂ§e")
    translated = translated.replace(u"ளே", u"Ã‚Â¼e")
    translated = translated.replace(u"ளெ", u"ÃƒËœe")
    translated = translated.replace(u"ளூ", u"j")
    translated = translated.replace(u"ளு", u"Ãƒâ€œ")
    translated = translated.replace(u"ளீ", u"C")
    translated = translated.replace(u"ளி", u"Ã‚Â¹")
    translated = translated.replace(u"ளா", u"eV")
    translated = translated.replace(u"ள", u"e")
    
    translated = translated.replace(u"ழ்", u"Ã‚Âµ")
    translated = translated.replace(u"ழௌ", u"ÃƒËœwe")
    translated = translated.replace(u"ழோ", u"Ã‚Â¼wV")
    translated = translated.replace(u"ழொ", u"ÃƒËœwV")
    translated = translated.replace(u"ழை", u"ÃƒÂ§w")
    translated = translated.replace(u"ழே", u"Ã‚Â¼w")
    translated = translated.replace(u"ழெ", u"ÃƒËœw")
    translated = translated.replace(u"ழூ", u"ÃƒÂ±")
    translated = translated.replace(u"ழு", u"Ã‚Â¿")
    translated = translated.replace(u"ழீ", u"Ãƒâ€˜")
    translated = translated.replace(u"ழி", u"a")
    translated = translated.replace(u"ழா", u"wV")
    translated = translated.replace(u"ழ", u"w")
    
    translated = translated.replace(u"வ்", u"Ãƒâ€¹")
    translated = translated.replace(u"வௌ", u"ÃƒËœke")
    translated = translated.replace(u"வோ", u"Ã‚Â¼kV")
    translated = translated.replace(u"வொ", u"ÃƒËœkV")
    translated = translated.replace(u"வை", u"ÃƒÂ§k")
    translated = translated.replace(u"வே", u"Ã‚Â¼k")
    translated = translated.replace(u"வெ", u"ÃƒËœk")
    translated = translated.replace(u"வூ", u"Ãƒâ€ ")
    translated = translated.replace(u"வு", u"Ã‚Â¡")
    translated = translated.replace(u"வீ", u"T")
    translated = translated.replace(u"வி", u"s")
    translated = translated.replace(u"வா", u"kV")
    translated = translated.replace(u"வ", u"k")
    
    translated = translated.replace(u"ஷ்", u"i")
    translated = translated.replace(u"ஷௌ", u"ÃƒËœre")
    translated = translated.replace(u"ஷோ", u"Ã‚Â¼rV")
    translated = translated.replace(u"ஷொ", u"ÃƒËœrV")
    translated = translated.replace(u"ஷை", u"ÃƒÂ§r")
    translated = translated.replace(u"ஷே", u"Ã‚Â¼r")
    translated = translated.replace(u"ஷெ", u"ÃƒËœr")
    translated = translated.replace(u"ஷூ", u"Ã‚Â£")
    translated = translated.replace(u"ஷு", u"Ãƒâ€”")
    translated = translated.replace(u"ஷீ", u"U")
    translated = translated.replace(u"ஷி", u"Ã‚Â´")
    translated = translated.replace(u"ஷா", u"rV")
    translated = translated.replace(u"ஷ", u"r")
    
    translated = translated.replace(u"ஸ்", u"ÃƒÂ¼")
    translated = translated.replace(u"ஸௌ", u"ÃƒËœve")
    translated = translated.replace(u"ஸோ", u"Ã‚Â¼vV")
    translated = translated.replace(u"ஸொ", u"ÃƒËœvV")
    translated = translated.replace(u"ஸை", u"ÃƒÂ§v")
    translated = translated.replace(u"ஸே", u"Ã‚Â¼v")
    translated = translated.replace(u"ஸெ", u"ÃƒËœv")
    translated = translated.replace(u"ஸூ", u"`")
    translated = translated.replace(u"ஸு", u"q")
    translated = translated.replace(u"ஸீ", u"Ã‚Â¢")
    translated = translated.replace(u"ஸி", u"L")
    translated = translated.replace(u"ஸா", u"vV")
    translated = translated.replace(u"ஸ", u"v")
    
    translated = translated.replace(u"ஹ்", u"ÃƒÂ£")
    translated = translated.replace(u"ஹௌ", u"ÃƒËœÃƒâ€¡e")
    translated = translated.replace(u"ஹோ", u"Ã‚Â¼Ãƒâ€¡V")
    translated = translated.replace(u"ஹொ", u"ÃƒËœÃƒâ€¡V")
    translated = translated.replace(u"ஹை", u"ÃƒÂ§Ãƒâ€¡")
    translated = translated.replace(u"ஹே", u"Ã‚Â¼Ãƒâ€¡")
    translated = translated.replace(u"ஹெ", u"ÃƒËœÃƒâ€¡")
    translated = translated.replace(u"ஹீ", u"ÃƒÂª")
    translated = translated.replace(u"ஹி", u"N")
    translated = translated.replace(u"ஹா", u"Ãƒâ€¡V")
    translated = translated.replace(u"ஹ", u"Ãƒâ€¡")

    translated = translated.replace(u"க்ஷ்", u"Ãƒâ€¢")
    translated = translated.replace(u"க்ஷௌ", u"ÃƒËœÃ‚Â³e")
    translated = translated.replace(u"க்ஷோ", u"Ã‚Â¼Ã‚Â³V")
    translated = translated.replace(u"க்ஷொ", u"ÃƒËœÃ‚Â³V")
    translated = translated.replace(u"க்ஷை", u"ÃƒÂ§Ã‚Â³")
    translated = translated.replace(u"க்ஷே", u"Ã‚Â¼Ã‚Â³")
    translated = translated.replace(u"க்ஷெ", u"ÃƒËœÃ‚Â³")
    translated = translated.replace(u"க்ஷூ", u"f")
    translated = translated.replace(u"க்ஷு", u"Y")
    translated = translated.replace(u"க்ஷீ", u"ÃƒË†")
    translated = translated.replace(u"க்ஷி", u"H")
    translated = translated.replace(u"க்ஷா", u"Ã‚Â³V")
    translated = translated.replace(u"க்ஷ", u"Ã‚Â³")
    
    unconverted = [i for i in translated if i in source_text and not i in
                    punctuation+whitespace+digits]
    translated_trimed = ''.join([i for i in translated if not i in unconverted])

    if debug:
        return unconverted
    elif filtered:
        return translated_trimed
    else:
        return translated